[채드] 뷰 챌린지 미션 2, 3단계 제출합니다.
woowacourse/android-paint pull request #100
Opened 2024-10-03 17:57 UTC by dpcks0509

호두 안녕하세요~~
이번에도 좋은 리뷰 부탁드립니다!! 

#### 선택 요구 사항
- 지우개 모드 : 특정 라인 지우기
- 전체 그림을 지우는 기능 구현
- 취소(undo) 기능 구현
- 태블릿 디바이스의 세로(portrait)화면 대응 시 ConstraintLayout만 활용하여 구현

### 태블릿 - 세로
![태블릿 세로](https://github.com/user-attachments/assets/ed336210-1742-4418-8cc6-3d9692410957)

### 태블릿 - 가로
![태블릿 가로](https://github.com/user-attachments/assets/4eaa12d8-5577-4f02-9767-07117b828831)

### 다크모드
![다크모드](https://github.com/user-attachments/assets/c8113a7e-b129-46eb-ad62-8d969f1e9007)

### 시연 영상
https://github.com/user-attachments/assets/d7a7ce64-8759-45c5-ae35-a6b138b862df

2024-10-05 09:45 UTC, Junyoung-WON requested changes
2, 3 단계 빠르게 구현해주셨네요! 고생하셨습니다!! 🎉
UI도 깔끔하고 예쁘게 만들어 주신 것 같아요~
그리고 이번 단계를 구현하기 위해 여러 많은 고민이 들어간 것이 느껴졌습니다!

생각해볼 만한 부분을 코멘트로 남겨드렸습니다. 제가 아직 미션을 진행 중이라, 깊게는 피드백을 드리지 못했어요.
저도 미션을 마저 하고 공부를 하면서, 피드백이 필요할 부분들이 생기면 수시로 다시 찾아오겠습니다!

마지막 미션인 만큼, 끝까지 파이팅입니다!! 😆

2024-10-05 09:45 UTC, Junyoung-WON commented on app/src/main/java/woowacourse/paint/PaintBoard.kt
> +        setLayerType(LAYER_TYPE_HARDWARE, null)
위 코드는 GPU 가속 설정을 하는 코드로 알고 있어요.
해당 코드가 필요한 이유가 무엇일까요?

2024-10-05 09:45 UTC, Junyoung-WON commented on app/src/main/java/woowacourse/paint/PaintBoard.kt
> +        }
매번 draw를 호출할 때 마다 기존에 그려진 그림들을 모두 새로 그리게 됩니다.
그린 그림이 정말 많다면 그만큼 렌더링에 들어가는 비용이 커져서 성능 저하가 발생할 수 있을 것 같아요.
GPU 가속의 경우 일부 사양이 좋지 않은 기기는 오히려 성능을 악화시킬 수 있다고 합니다.
이 문제를 어떻게 극복할 수 있을까요?

저도 1단계 미션에서 받은 피드백이고, 아마 채드도 주위 크루에게 이야기를 들었을 수도 있는데요!
이에 대한 채드의 의견과 생각이 궁금합니다! 채드와 이야기 나누며 어떤 방법이 좋을지 함께 고민해보고 싶어요.
코드로 반영하지 않아도 좋으니 천천히 코멘트를 달아주시면 감사하겠습니다!

2024-10-05 09:45 UTC, Junyoung-WON commented on app/src/main/java/woowacourse/paint/PaintBoard.kt
> +            }
`DrawingMode`를 직접 확인해서 `paint`에 `style`과 `xfermode`를 적용하지 않고,
`DrawingMode`가 `paint`를 가져와 스스로 `style`과 `xfermode`를 변경하도록 하면
코드를 더 깔끔하게 둘 수 있을 것 같아요!

```kotlin
private fun applyDrawingMode() {
    drawingMode.setPaintMode(paint)
}
```

2024-10-05 09:45 UTC, Junyoung-WON commented on app/src/main/java/woowacourse/paint/action/PaintBoardAction.kt
> +}
그림판의 Action을 sealed interface로 구분하여 삭제, 취소를 정의하셨군요! 👍

2024-10-05 09:45 UTC, Junyoung-WON commented on app/src/main/java/woowacourse/paint/adapter/PaintDrawingModelHolder.kt
> +class PaintDrawingModelHolder(private val binding: ItemPaintDrawingModeBinding) :
클래스 이름에 오타가 난 것 같아요....!!
Mode 인데 Model 로 되어있네요!

2024-10-05 09:45 UTC, Junyoung-WON commented on app/src/main/java/woowacourse/paint/adapter/PaintDrawingModelHolder.kt
> +        binding.actionHandler = actionHandler
지금 구현에서는 그리기 모드의 개수가 정해져있고, 추가 삭제가 일어나지도 않기 때문에 RecyclerView에서 ViewHolder를 재사용한다는 동작이 일어나지 않죠!
그래서 handler를 ViewHolder 에서 바인딩을 하여도 큰 상관은 없습니다.

하지만 이벤트 리스너나 핸들러를 bindViewHolder 시점에 바인딩 하는 것은 안티 패턴입니다!

2024-10-05 09:45 UTC, Junyoung-WON commented on app/src/main/java/woowacourse/paint/model/DrawingMode.kt
> +) {
`DrawingMode` 에 따라 `Paint`의 `style` 및 `xfermode` 가 다르게 정의되어 있다면, 각 모드에 따른 `style`과 `xfermode` 값을 `DrawingMode`가 함께 가지고 있는 것은 어떨까요?
그렇게 한다면 `PaintBoard`가 아닌, `DrawingMode`가 스스로 `paint`에 대한 설정을 변경할 수 있을 것 같아요!

```kotlin
enum class DrawingMode(
    @DrawableRes val drawableRes: Int,
    @StringRes val stringRes: Int,
    val paintStyle: Style,
    val xfermode: Xfermode,
) {
    // ...
    companion object {
        fun setPaintMode(paint: Paint) { 
            // 스스로 paint를 설정
        }
    }
}
```

2024-10-05 09:45 UTC, Junyoung-WON commented on app/src/main/java/woowacourse/paint/uimodel/DrawingModeUiModel.kt
> +data class DrawingModeUiModel(val drawingMode: DrawingMode, val isChecked: Boolean)
UI 모델 도입 편안합니다~ ☺️

2024-10-05 09:45 UTC, Junyoung-WON commented on app/src/main/java/woowacourse/paint/util/PaintBindingAdapter.kt
> +}
이렇게도 TextView 에 drawable을 붙이고 색상 등을 변경할 수 있군요...! 신기하네요!!

2024-10-05 09:45 UTC, Junyoung-WON commented on app/src/main/java/woowacourse/paint/util/PaintBindingAdapter.kt
BindingAdapter를 적극적으로 잘 활용해주셨군요! 😃

2024-10-05 09:45 UTC, Junyoung-WON commented on app/src/main/res/layout/activity_paint.xml
> +            android:layout_marginHorizontal="@dimen/paint_horizontal_margin"
그리기 모드와 선 굵기, 색상 선택 리스트 모두 공통된 `paint_horizontal_margin` 값으로 좌 우 마진이 들어가야 한다면,
세 개의 View를 하나의 Layout으로 묶어 두어 Layout에 `paint_horizontal_margin` 마진을 주는 것도 좋을 것 같아요!

만약 위 세 View가 다른 화면 크기에서도 마진 이외에도 동일한 배치로 이루어져있다면, 해당 레이아웃을 따로 빼는 것도 재사용이나 관리 측면에서 좋겠네요..!

2024-10-06 10:36 UTC, dpcks0509 commented on app/src/main/java/woowacourse/paint/adapter/PaintDrawingModelHolder.kt
> +class PaintDrawingModelHolder(private val binding: ItemPaintDrawingModeBinding) :
앗 오타가 있었군요! 수정하였습니다!

2024-10-06 11:38 UTC, dpcks0509 commented on app/src/main/java/woowacourse/paint/adapter/PaintDrawingModelHolder.kt
> +        binding.actionHandler = actionHandler
이때까지 bind 함수에서 계속 actionHandler를 받는 방식을 사용하였는데 안티 패턴인줄 모르고 사용했네요!
actionHandler가 하나로 고정되어 있는데 호두 말처럼 viewHolder의 재사용이 발생한다면 계속 bind에서 동일한 actionHandler를 넣어주게 되니 안좋은 방법인 것 같습니다. onCreateViewHolder에서 actionHandler를 넣어주도록 수정하겠습니다!

만약 actionHandler가 하나로 고정되어 있지 않고 2개 이상이 존재하고 상황에 따라서 다른 actionHandler를 넘겨줘야한다면 bindViewHolder에서 actionHandler를 onCreateViewHolder가 아니라 onBindViewHolder에서 넘겨주는게 맞을까요?

2024-10-06 12:01 UTC, dpcks0509 commented on app/src/main/res/layout/activity_paint.xml
> +            android:layout_marginHorizontal="@dimen/paint_horizontal_margin"
굵기, 색상, 브러쉬 변경 ConstraintLayout 으로 감싸도록 수정하였습니다!

2024-10-06 12:04 UTC, dpcks0509 commented on app/src/main/java/woowacourse/paint/PaintBoard.kt
> +        setLayerType(LAYER_TYPE_HARDWARE, null)
이 코드가 없으면 지우개 모드를 하였을때 검은색이 나오더라구요. 그래서 저 코드를 제거하고 지우개 모드일때 paint의 색상을 white로 변경시켜서 덮어 씌우는 방법도 생각해봤는데, 그러면 drawing이 지워지는게 아니라 흰색의 drawing이 계속 drawings에 추가가 돼서 onDraw할때 계속 지우기 위해 필요한 drawing도 계속 그려줘야한다는 단점때문에 채택하지 못했습니다!

2024-10-06 12:16 UTC, dpcks0509 commented on app/src/main/java/woowacourse/paint/PaintBoard.kt
> +        }
이 부분도 onDraw 함수가 호출될때 마다 계속 모든 drawings를 새로 그려줘야하기 때문에 새로 추가되는 것만 그리게 하는 방법을 생각해보았는데 아직까지는 해결방안을 찾이 못했네요,, ㅠ

2024-10-06 12:30 UTC, Junyoung-WON commented on app/src/main/java/woowacourse/paint/adapter/PaintDrawingModelHolder.kt
> +        binding.actionHandler = actionHandler
제 피드백의 의미를 잘 파악해주셨군요!! 👍 채드가 이해한 것이 맞습니다~
뷰홀더로 감싸지는 아이템들을 클릭했을 때 모두 동일한 동작을 하기를 기대하고 있다면,
처음 ViewHolder를 만들어낼 때에 클릭 이벤트를 한번만 bind 하면 되니까요!
그래 ViewHolder에 매번 bind를 하는 과정에서 동일한 클릭 이벤트를 함께 bind하는 것이 안티 패턴이라고 합니다.

> 만약 actionHandler가 하나로 고정되어 있지 않고 2개 이상이 존재하고 상황에 따라서 다른 actionHandler를 넘겨줘야한다면

음... 이 경우에는 onBindViewHolder에서 넘겨주는 것도 방법이 될 것 같구요!
상황에 따라 각각 이벤트 리스너를 넘겨주어야 한다면, 다른 ViewType으로 구분하여 구현하는 것도 방법이 될 수 있을 것 같아요!

사실 추상화를 잘 적용한다면 위 문제도 깔끔하게 해결이 되지 않을까 싶습니다..!

```kotlin
sealed interface ActionHandler {
    interface OneActionHandler : ActionHandler

    interface TheOtherActionHandler: ActionHandler
}
```

2024-10-06 13:08 UTC, dpcks0509 commented on app/src/main/java/woowacourse/paint/model/DrawingMode.kt
> +) {
```kotlin
enum class DrawingMode(
    @DrawableRes val drawableRes: Int,
    @StringRes val stringRes: Int,
    val paintStyle: Paint.Style,
    val xferMode: PorterDuffXfermode?

) {
    PEN(R.drawable.ic_pen, R.string.drawing_mode_pen, Paint.Style.STROKE, null),
    SQUARE(R.drawable.ic_square, R.string.drawing_mode_square, Paint.Style.FILL, null),
    CIRCLE(R.drawable.ic_circle, R.string.drawing_mode_circle, Paint.Style.FILL, null),
    ERASER(
        R.drawable.ic_eraser,
        R.string.drawing_mode_eraser,
        Paint.Style.STROKE,
        PorterDuffXfermode(PorterDuff.Mode.CLEAR)
    ), ;
}
``` 

이렇게 수정하였습니다! 기존에 코드가 훨씬 깔끔해진 것 같네요!

2024-10-06 13:10 UTC, dpcks0509 commented on app/src/main/java/woowacourse/paint/PaintBoard.kt
> +            }
```kotlin
private fun applyDrawingMode() {
        paint.style = drawingMode.paintStyle
        paint.xfermode = drawingMode.xferMode
    }
``` 
enum class 안에 각각의 요소들을 넣어두고 이렇게 하나의 코드로 설정가능하게 수정하였습니다!

2024-10-07 08:09 UTC, Junyoung-WON commented on app/src/main/java/woowacourse/paint/PaintBoard.kt
> +        setLayerType(LAYER_TYPE_HARDWARE, null)
수정테이프처럼 배경색과 같은 색상으로 덮어쓰는 것으로 지우개를 구현했을 때의 단점을 잘 고민해주셨네요!!
이런 단점 때문에 강의자료에 나온 방식으로 지우개를 구현해주셨군요~ 👍

지우개 기능을 구현할 때의 내부 동작 방식이 궁금하여, 가볍게 딥다이브를 해보았습니다!
잠깐 공부해본 내용을 공유해드릴게요! ~~그냥 TMI니까 재미로 봐주세요!~~

채드가 코드로 구현해준 지우개 기능은 `Paint`의 `transfer mode` 를 `PoterDuffXfermode`의 `CLEAR` 모드로 변경하여, `Canvas` 에 그려진 `Path`들을 모두 투명화 처리합니다.
결과적으로 터치된 영역의 모든 `Path` 들의 픽셀이 모두 투명해지면서, 지우개로 지워지는 듯한 효과를 얻은 것이죠!

`transfer mode` 는 말 그대로 **변환 모드**입니다.
예시를 들어볼게요! 실생활에서 물감으로 그림을 그릴 때, 이미 그려져있는 그림 위에 다른 색깔로 칠하게 되면, 이미 그려진 그림의 물감 색과 새로 칠한 물감의 색이 섞여 다른 색깔이 나타나겠죠?

안드로이드도 마찬가지입니다. (아마 다른 시스템도 마찬가지일 것 같아요!)
안드로이드 시스템이 화면에 그림을 그릴 때,
**기존에 화면에 나타나있는**(`Path` 영역에 존재하는) **픽셀**과 
**새로 그리려고 하는 픽셀**을 _**조합**_ 하여 새로운 픽셀로 나타냅니다.
이 때 두 픽셀을 **어떻게 조합할 것인가** 에 대한 연산 방식이 `Paint`의 속성으로 정의된 `transfer mode` 이고, 코드 상에서는 `Xfermode`라는 클래스로 나타납니다. ~~요상한 네이밍 때문에 이해가 더 어렵네요!~~

`PoterDuffXfermode` 라는 것은 일반적으로 많이 사용되는 `Xfermode` 이며, 이 클래스의 네이밍은 Thomas Porter 와 Tom Duff 라는 분들이 옛날에 낸 논문으로부터 비롯되었다고 합니다.
즉 해당 논문에 기재된 픽셀 연산 방식들을 코드에서 구현하는 클래스인거죠.
논문의 12가지 연산 방식들 중 하나가, 우리가 사용하는 `CLEAR` Mode 입니다! (새로 그릴 픽셀과 기존의 픽셀을 모두 투명화 처리한다고 하네요.)

문제는 이 `PorterDuffMode` 를 사용할 때에는 **하드웨어 가속이 필요**합니다.
하드웨어 가속 설정이 되어있지 않으면, `픽셀과 픽셀을 혼합하는 연산이 제대로 지원되지 않고`,
때문에 `Canvas` 상의 픽셀들을 투명하게 만드는 연산(`CLEAR` Mode)도 제대로 동작하지 않는다고 합니다.
그래서 투명해지는 대신 검은색으로 나타나게 되는 것이라고 합니다!

2024-10-07 08:57 UTC, Junyoung-WON approved these changes
안녕하세요, 채드!!
미션 너무너무너무 고생하셨습니다~~! 😆
UI 도 정말 예쁘게 신경써서 만들어주시고, 추상화에도 신경을 많이 써주신 것이 느껴졌어요!
앱을 잘 만들어 주신 덕에 리뷰하는 맛이 넘쳤던 미션이었습니다! 얻어간 지식도 많네요...!
너무 감사드려요! 🙇‍♂️

그리고 리뷰가 늦어져서 죄송합니다...! 중간에 지우개 동작 방식에 관해서 딥다이브를 하는 바람에...ㅎㅎ
죄송한 마음에 딥다이브한 내용을 코멘트에 남겨놓았으니, 재미로 한번 읽어봐주시면 감사하겠습니다!

마지막 뷰 챌린지 미션까지 정말 고생 많으셨어요!!! 🥳

2024-10-07 08:57 UTC, Junyoung-WON commented on app/src/main/java/woowacourse/paint/model/DrawingMode.kt
> +    val xferMode: PorterDuffXfermode?,
저의 의견을 반영해주셔서 `DrawingMode`가 `Paint`의 스타일, 트랜스퍼 모드 등의 속성들을 가지고 있도록 해주셨군요...!
저도 채드처럼 구현을 해냈습니다. 확실히 코드가 많이 간결해진 것이 보였어요!
하지만 다른 여러 기능이나 속성들이 추가되는 경우에는 더더욱 관리가 어려워진다는 단점이 있을 것 같았어요..!

아마 도구 패널들의 기능을 더 작게 나누어서 관리한다면 어느 정도는 해결할 수 있지 않을까 생각합니다!

2024-10-07 08:57 UTC, Junyoung-WON commented on app/src/main/java/woowacourse/paint/model/DrawingMode.kt
> +    }
저는 동반객체의 메서드로 paint 객체를 받아서 해당 paint에 style과 transfermode를 직접 설정하게 해보았어요!
```kotlin
    companion object {
        fun DrawingMode.setPaintStyle(paint: Paint) {
            paint.style = this.paintStyle
            paint.xfermode = this.xfermode
        }
    }
```

코드는 더 간결해졌지만, 이 방식이 괜찮은가? 는 잘 모르겠네요...!

2024-10-07 08:57 UTC, Junyoung-WON commented on app/src/main/java/woowacourse/paint/model/Drawing.kt
> +data class Drawing(val path: Path, val paint: Paint, val drawingMode: DrawingMode)
`Drawing` 에 그리기 모드가 함께 들어가있네요!
이 친구를 조금 더 객체지향적으로 개선해본다면, 각 모드에 따라 자신이 그리는 방식을 스스로 구분짓도록 해도 괜찮을 것 같아요!
즉, `path`를 이용하여 그리는 동작을 `Drawing` 객체가 스스로 구현하고, 외부에서는 단순히 `drawing`에게 그림을 그려달라고만 명령하는 것이죠!

2024-10-07 08:57 UTC, Junyoung-WON commented on app/src/main/res/layout/activity_paint.xml
> +            android:layout_marginHorizontal="@dimen/paint_horizontal_margin"
도구 패널에 들어가는 View 들을 하나의 레이아웃으로 묶고, 공통된 마진을 갖도록 리팩터링해주셨군요! 👍

나중에 더 개선해본다면, 해당 `ConstraintLayout`을 다른 layout 파일로 분리하여 관리할 수도 있을 것 같네요!
xml의 코드 중복을 많이 줄일 수 있을 것 같아요~

2024-10-07 08:57 UTC, Junyoung-WON commented on app/src/main/res/values-night/colors.xml
> +    <color name="white">#FF000000</color>
다크모드에 대응하기 위해, 단순히 black 과 white 색상의 참조 값(실제 색상)을 반대로 둔다면 함께 작업하는 동료 개발자의 입장에서는 혼란이 있을 수 있을 것 같아요!

조금 더 명시적인 이름을 사용하고, 상황과 컴포넌트에 따른 색상들을 더 세분화하여 관리한다면 유지 보수도 수월해지고, 코드를 함께 작업하는 동료 개발자도 작업하는 데 어려움이 줄어들 것 같습니다!

```xml
    <!-- 기본 색상(values/colors.xml) -->
    <color name="drawing_board_background">@color/white</color>
    <color name="tools_panel_background">@color/gray</color>
    <color name="tools_panel_primary">@color/dark_gray</color>
    <color name="tools_panel_primary_variant">@color/semi_black</color>

    <!-- 다크모드 색상(values-night/colors.xml) -->
    <color name="drawing_board_background">@color/semi_black</color>
    <color name="tools_panel_background">@color/light_gray</color>
    <color name="tools_panel_primary">@color/gray</color>
    <color name="tools_panel_primary_variant">@color/dark_gray</color>
```

2024-10-07 08:57 UTC, Junyoung-WON commented on app/src/main/java/woowacourse/paint/PaintActivity.kt
나중에 Configuration Change 에 대응하여, 그림이 사라지는 것을 방지하는 방법을 고민해서 리팩터링 해보아도 좋을 것 같아요!
저도 이 부분을 해내고 싶었는데, 시간이 없군요...ㅎㅎ
Application과 싱글톤 객체를 활용하면 간단하게 구현할 수 있지 않을까 생각합니다...!

2024-10-07 08:58 UTC, merged

2024-10-07 10:57 UTC, Junyoung-WON commented on app/src/main/java/woowacourse/paint/PaintBoard.kt
> +        setLayerType(LAYER_TYPE_HARDWARE, null)
그래서 사실은, 저희가 구현한 지우개는 정말로 지워지는 것이 아니라,
지우개로 그린 부분들을 모두 투명하게 만드는 또 하나의 `Path` 입니다...!

> onDraw할때 계속 지우기 위해 필요한 drawing도 계속 그려줘야한다

그래서 이 부분은 지금의 구현에서도 마찬가지인 문제점입니다.
지워진 것이 아니라, 지워진 것 처럼 보이는 것입니다!

그래서 이미 지웠다고 생각한 그림판에 사실은 보이지만 않는 이전의 `Path` 들이 모두 남아있는 것이기 때문에,
마찬가지로 불필요한 그리기 연산이 들어가게 되고 메모리 공간을 차지하고 있습니다.

저도 여기에 대해 공부를 하면서 이번에 알게 된 사실입니다...!
그렇다면 어떻게 해야 정말로 `Path`를 지울 수 있을까요?

2024-10-09 05:57 UTC, junjange commented on app/src/main/java/woowacourse/paint/PaintBoard.kt
> +        setLayerType(LAYER_TYPE_HARDWARE, null)
오오 너무 좋은데요??

2024-10-09 05:59 UTC, gaeun5744 commented on app/src/main/java/woowacourse/paint/PaintBoard.kt
> +        setLayerType(LAYER_TYPE_HARDWARE, null)
대박이다 방명록 남기고 갑니다

2024-10-09 06:20 UTC, chaehyuns commented on app/src/main/java/woowacourse/paint/PaintBoard.kt
> +        setLayerType(LAYER_TYPE_HARDWARE, null)
따봉 남길게요~

2024-10-09 06:28 UTC, murjune commented on app/src/main/java/woowacourse/paint/PaintBoard.kt
> +        setLayerType(LAYER_TYPE_HARDWARE, null)
배워갑니다 호교수님!

2024-10-09 06:31 UTC, hxeyexn commented on app/src/main/java/woowacourse/paint/PaintBoard.kt
> +        setLayerType(LAYER_TYPE_HARDWARE, null)
> 가볍게 딥다이브를 해보았습니다!

호두의 기만..

2024-10-09 06:31 UTC, kimhm0728 commented on app/src/main/java/woowacourse/paint/PaintBoard.kt
> +        setLayerType(LAYER_TYPE_HARDWARE, null)
역시 갓두!