[에디] 뷰 챌린지 미션 2, 3단계 제출합니다.
woowacourse/android-paint pull request #105
Opened 2024-10-06 11:57 UTC by junjange

케이엠 이번에도 잘 부탁드립니다!!!!! 🫡

# 구현 사항
- 사용자가 그림을 그릴 수 있도록 커스텀 뷰를 생성했습니다.
- 사용자가 선택한 브러시(펜, 직사각형, 원, 지우개)를 통해 그림을 그릴 수 있도록 구현했습니다.
- 펜으로 그린 모든 선은 하나의 Path로 처리하고, 직사각형과 원은 각각 하나의 개별 Path로 관리하여 리스트에 저장했습니다.

2024-10-07 06:59 UTC, kmkim2689 requested changes
에디 안녕하세요!! 🦊
2, 3단계 미션도 수고 많으셨습니다 😄

코드가 대체로 간단하고 가독성 좋게 작성되어 리뷰하기 너무 편했습니다ㅎㅎ
리뷰할 때마다 항상 감탄하게 되네요!
그리고 저와 구현하신 방식이 달라 신기하기도 했고 재미있었습니다!

몇 가지 피드백 남겨보았는데, 참고 부탁드리겠습니다!
그 중에서는 에디의 생각이 궁금한 질문들도 있는데, 의견 같이 나눠보면 좋을 것 같아요!

그럼 뷰 챌린지 끝까지 화이팅입니다! 👍

2024-10-07 06:59 UTC, kmkim2689 commented on README.md
> +- [x] 다크모드
PR 상에서는 상태바 색상이 잘 나와있는데, 저의 에뮬 상에서는 다크모드에서 상태바 색상이 보라색으로 나타나고 있습니다!!
무슨 이유인지 모르겠지만 theme.xml(night) 파일에서 상태바 색상이 colorPrimaryVariant로 되어있는데, 한 번 확인해보시면 좋을 것 같아 말씀드려 봅니다!

```
<resources xmlns:tools="http://schemas.android.com/tools">
    <!-- Base application theme. -->
    <style name="Theme.Paint" parent="Theme.MaterialComponents.DayNight.DarkActionBar">
        <!-- ... -->
        <!-- Status bar color. -->
        <item name="android:statusBarColor">?attr/colorPrimaryVariant</item>
    </style>
</resources>
```

![image](https://github.com/user-attachments/assets/6160776b-f503-42fa-a4f6-9fe259420b3f)

2024-10-07 06:59 UTC, kmkim2689 commented on app/src/main/java/woowacourse/paint/model/Brush.kt
> +    }
다크모드에서 지우개를 사용하면 아래와 같은 결과가 나옵니다! 😂 
지우개의 색상을 지정하기 보다는 `xfermode` 같은 다른 방법을 사용해보시는 것을 제안드리고 싶습니다!

![image](https://github.com/user-attachments/assets/adaf6965-c5a9-466d-9511-27980c1351a8)

2024-10-07 06:59 UTC, kmkim2689 commented on app/src/main/res/layout-w600dp/activity_main.xml
> +        android:layout_height="match_parent">
lms 상에서 다음과 같은 요구사항을 확인할 수 있었는데,
> 태블릿 세로 화면에서는 도구 패널의 폭을 줄인다.

현재는 아래와 같이 태블릿이 세로 방향으로 사용될 때 가로 모드에서 나와야 할 레이아웃이 나오고 있는 상태입니다...! 😹 
휴대폰, 태블릿 세로, 태블릿 가로 세 경우가 보여져야 하는 레이아웃이 전부 다르더라고요!
> 태블릿 가로 화면에서는 도구 패널을 왼쪽 상단으로 옮긴다.

![image](https://github.com/user-attachments/assets/fde6b5e8-504a-40de-abc5-7b8da387f201)

아무래도 너비의 기준을 600dp로 가져가서 생긴 문제가 아닌가 싶은데, 시연에서 사용되는 태블릿의 세로 길이(짧은 쪽)가 800dp임을 고려해 보았을 때 레이아웃 너비의 기준을 바꿔보는 것은 어떨지 제안드리고 싶습니다!

2024-10-07 06:59 UTC, kmkim2689 commented on app/src/main/java/woowacourse/paint/model/BrushStyle.kt
> +)
현재 `BrushType` 데이터의 변화 발생 시 copy() 메소드를 사용하여 방어적 복사를 하고 계신데, `brushType` 프로퍼티를 가변으로 설정하신 이유를 알 수 있을까요?! 🤔 
실제로 불변으로 변경하여도 프로그램 실행에는 문제가 없긴 해서요...!

2024-10-07 06:59 UTC, kmkim2689 commented on app/src/main/java/woowacourse/paint/model/Brush.kt
> +    }
* 단순한 의견 제시로, 미션과 연관성이 적기에 반영하실 필요 없는 피드백입니다.

함수가 하는 일을 보면 단순히 paint의 style만을 변경하는데, 함수 이름들을 보면서 "paint 스타일을 채우는 것으로 변경하는 것이 브러쉬를 사각형으로 그리도록 설정하는 것으로 볼 수 있는 것인가?!"하는 생각이 들었습니다.

함수명을 더 직관적으로 변경하거나 함수의 구조를 바꿔보는 것도 좋을 것 같아요!

2024-10-07 06:59 UTC, kmkim2689 commented on app/src/main/java/woowacourse/paint/ui/DrawingView.kt
> +            }
`ACTION_UP`에서 brush 객체의 move 함수를 호출하시는 이유를 알 수 있을까요?!
이름으로만 보았을 때는 `ACTION_MOVE`에서 호출되어야 할 것 같기도 하고, 실제 구현체를 보니 `ACTION_UP` 분기에서 move를 호출하지 않아도 동작이 정상적으로 이뤄질 것 같아 말씀드려봅니다! 😂

2024-10-07 06:59 UTC, kmkim2689 commented on app/src/main/java/woowacourse/paint/ui/DrawingView.kt
> +    }
* 의견 제시로, 반영할 필요 없는 피드백입니다.

사각형이랑 원일 때만 `brushHistory` 리스트에 브러쉬 기록이 추가되는데, 펜은 그렇지 않는 것 같네요! 😂 

혹시 그 기준이 어떻게 되는지 알 수 있을까요?.?

제가 이해한 바가 맞다면 액티비티에서 init하는 과정 중 DrawingView에 Brush를 넘겨줄 때 그 BrushStyle의 기본값이 `PEN`이고, 처음에 넘겨받은 brushStyle을 brushHistory에 처음으로 추가해주기 때문에 따로 분기처리를 추가하지 않으신 것으로 보이는데요!!

사실 처음 `DrawingView` 코드만 보았을 때는 이러한 과정은 해당 View를 사용할 개발자가 이해하기 힘들 수 있겠다는 생각이 들었던 것 같아요!
만약 개발자가 brushStyle로 초기에 PEN이 아닌 다른 도형을 넘겨준다면, 동작에도 문제가 발생할 것 같습니다.
이러한 측면에서 보았을 때 저였으면 처음에 `brushHistory`를 빈 상태로 놔두고 PEN에 대한 분기도 추가할 것 같은데요!

여유 되신다면 에디의 의견도 한 번 부탁드리겠습니다! 🦊

2024-10-07 06:59 UTC, kmkim2689 commented on app/src/main/java/woowacourse/paint/ui/DrawingView.kt
> +        )
지난 단계 리뷰와 연관이 있는 피드백일 것 같습니다! 😆

지난 단계와는 달리 이번 단계에서는 히스토리를 관리하기 위한 리스트가 추가되었네요! 뷰를 계속 동적으로 추가하는 방식에 기록 리스트를 관리하는 방식이 혼합된 것으로 보여요!!

한 번 시험을 해보고 싶어, 아래와 같이 뷰가 생성될 때마다 + 그림이 그려지는 것이 완료될 때마다 어떤 객체(hashCode)에서 어떤 히스토리를 가지고 있는지 로깅을 진행해 보았습니다!
```
// MainActivity.kt
private fun addView() {
    drawingView = DrawingView(context = this, brushStyle = brushStyle)
    binding.constraintPaintBoard.addView(drawingView)
    println("view with style ${brushStyle.brushType} added : ${drawingView.hashCode()}")
}

// DrawingView.kt
@SuppressLint("ClickableViewAccessibility")
override fun onTouchEvent(event: MotionEvent): Boolean {
    // ...
    when (event.action) {
        // ...

        MotionEvent.ACTION_UP -> {
            saveBrush(brush)
            println("${this.hashCode()} $brushHistory")
        }
        // ...
    }
}
```

그랬더니, 다음과 같은 결과가 나오더군요!
```
// 이상한 유저가 굵기를 슬라이더로 이리저리 조절해 보았을 때
view with style PEN added : 43593482
view with style PEN added : 68364236
view with style PEN added : 101730837
view with style PEN added : 1168019
view with style PEN added : 108110544
view with style PEN added : 182313673
view with style PEN added : 201915854
view with style PEN added : 142410991
view with style PEN added : 76946428
view with style PEN added : 22602373
view with style PEN added : 263923930
view with style PEN added : 197067019
view with style PEN added : 203881448
... 무수히 많은 객체 생성
```

```
// 한 페인트 스타일 종류로 같은 사각형을 이리저리 추가해 보았을 때
view with style RECTANGLE added : 219562747
219562747 [Brush(path=android.graphics.Path@4052f18, paint=android.graphics.Paint@f1e8d71), Brush(path=android.graphics.Path@580d756, paint=android.graphics.Paint@f1e8d71)]
219562747 [Brush(path=android.graphics.Path@4052f18, paint=android.graphics.Paint@f1e8d71), Brush(path=android.graphics.Path@580d756, paint=android.graphics.Paint@f1e8d71), Brush(path=android.graphics.Path@bfc13d7, paint=android.graphics.Paint@f1e8d71)]
219562747 [Brush(path=android.graphics.Path@4052f18, paint=android.graphics.Paint@f1e8d71), Brush(path=android.graphics.Path@580d756, paint=android.graphics.Paint@f1e8d71), Brush(path=android.graphics.Path@bfc13d7, paint=android.graphics.Paint@f1e8d71), 
... n개의 사각형
```

여기서 펜의 굵기 / 색상 / 브러쉬가 자주 변경되는 경우 + 한 세팅의 브러쉬로 무수히 많은 그림을 그리는 ~~최악의~~ 조합이 발생하는 경우를 가정해보고 싶습니다.

개인적으로는 뷰 객체의 무수한 생성과 더불어 한 번 onDraw가 발생할 때 거대한 규모의 `brushHistory` 리스트를 계속 순회해야 할 것 같아 성능 측면에서 조금 우려를 느꼈습니다.

저는 이것을 극복하기 위해 `비트맵 캐싱`이라는 방식을 적용해보았는데요!
에디는 어떻게 이 성능 상 한계를 극복하실지 아이디어를 들어보고 싶습니다! 🤔

2024-10-07 06:59 UTC, kmkim2689 commented on app/src/main/java/woowacourse/paint/model/Brush.kt
> +    ): Float = sqrt((endX - startX).toDouble().pow(2.0) + (endY - startY).toDouble().pow(2.0)).toFloat()
오호!! 원의 중심을 기준으로 원을 그릴 수 있도록 한 것이 신기했는데, 해당 함수들이 이것을 구현해내는 것인 것 같네요! 👍

2024-10-07 06:59 UTC, kmkim2689 commented on app/src/main/java/woowacourse/paint/ui/MainActivity.kt
>      private fun addView() {
* 반영하실 필요 없는 단순 궁금증입니다! 😅 

동적으로 View를 추가하는 방식을 사용했을 때, 현재의 지우개 방식 말고 사용자가 한 번 그린 단위 별로 지우는 것을 구현하고자 한다면 어떻게 구현할 수 있을까요?!

2024-10-08 05:17 UTC, junjange commented on app/src/main/java/woowacourse/paint/ui/DrawingView.kt
> +        )
저도 비트맵 캐싱 방식을 사용할 것 같습니다!
성능 면에서는 확실하지 않지만, 결국 View든 Path든 어디엔가 캐싱을 해야 할 것 같아요. 현재 제가 구현한 로직은 미션의 지우개 기능을 구현하기엔 적합하지 않은 것 같고(view를 add만 하고 따로 관리하고 있지 않아서!!!,,), Path를 저장하거나 비트맵으로 저장하는 방식이 가장 좋은 방법일 것 같습니다.

2024-10-08 05:18 UTC, junjange commented on app/src/main/java/woowacourse/paint/ui/MainActivity.kt
>      private fun addView() {
위에서 언급했듯이 bitmap과 bitmap에 위치를 캐싱하고, 사용자가 터치한 위치에 있는 bitmap을 제거할 것 같아요!!

2024-10-08 05:29 UTC, junjange commented on app/src/main/java/woowacourse/paint/ui/DrawingView.kt
> +    }
> 사각형이랑 원일 때만 brushHistory 리스트에 브러쉬 기록이 추가되는데, 펜은 그렇지 않는 것 같네요! 😂
> 혹시 그 기준이 어떻게 되는지 알 수 있을까요?.?

펜은 하나의 Path에서만 뷰를 그리기 때문에 따로 추가하는 로직을 작성하지 않았습니다. 그 외 도형들은 사용자의 터치 이후에 뷰를 그려야하기 때문에 Path를 저장하고 새롭게 추가할 수 있도록 구현했습니다!!

2024-10-08 05:33 UTC, junjange commented on app/src/main/java/woowacourse/paint/ui/DrawingView.kt
> +            }
헉 그러네요!! 지우도록 하겠습니다!!

2024-10-08 05:47 UTC, junjange commented on app/src/main/java/woowacourse/paint/model/BrushStyle.kt
> +)
실수로 바꾼 것 같아요!!,, 수정하도록 하겠습니다!!

2024-10-08 05:52 UTC, junjange commented on app/src/main/res/layout-w600dp/activity_main.xml
> +        android:layout_height="match_parent">
네네!! 개선했습니다!!

2024-10-08 10:32 UTC, kmkim2689 approved these changes
에디 이번 뷰 챌린지 미션 정말 수고 많으셨습니다!

피드백 반영 잘 해주셨네요!
의견 제시 적극적으로 해주신 덕에 새로운 관점에서 많이 배울 수 있었습니다 😄

마지막으로 코멘트 하나 남겨드렸는데, 참고 한 번 부탁드리겠습니다.
앞으로도 응원하겠습니다!!

2024-10-08 10:32 UTC, kmkim2689 commented on app/src/main/java/woowacourse/paint/model/Brush.kt
> -            color = Color.WHITE
브러쉬를 지우개로 바꾼 후, 다시 펜으로 바꾸면 브러쉬 굵기로 설정한 값과 상관 없이 지우개의 굵기대로 펜이 그려지는 문제가 있습니다 😂 펜으로 다시 변경하였을 때 슬라이더에 맞는 굵기 조정이 필요할 것 같아요!

2024-10-08 10:32 UTC, merged