[채채] 뷰 챌린지 미션 2, 3단계 제출합니다.
woowacourse/android-paint pull request #112
Opened 2024-10-07 07:13 UTC by chaehyuns

안녕하세요 벼리~~
오랜만이에요!!
다음주전에는 꼭 얼굴 또 보자구요,,,

<img width="450" alt="스크린샷 2024-10-07 오후 4 09 53" src="https://github.com/user-attachments/assets/e8717d21-9f88-45a0-a080-b10f56cdd4f3">

<img width="200" alt="image" src="https://github.com/user-attachments/assets/b359fa90-1e14-4aed-8c85-2a972c6f3ce2">

<img width="200" alt="image" src="https://github.com/user-attachments/assets/d95cbde5-86ad-4de9-a887-9506cd4438e2">

2024-10-07 08:12 UTC, woowahan-leah commented
과연 그들이 얼굴을 볼 날이 올까요

2024-10-07 12:56 UTC, gaeun5744 requested changes
안녕하세요 채채~ 
2, 3단계 미션도 고생 많았습니다 🥰

> 오랜만이에요!!
다음주전에는 꼭 얼굴 또 보자구요,,,

저희 얼굴본지 4일밖에 안되었는데, 벌써 제가 그리운가 보네요.
저도 채채가 그립습니다. 
그러니 한글날 수요일에 선릉캠에 오세요.

2024-10-07 12:56 UTC, gaeun5744 commented on app/src/main/java/woowacourse/paint/model/ShapeType.kt
> +}
`ShapeType`은 4가지지만, 구현된 `Shape`는 3가지네요..! (SquareShape,PathShape,CircleShape)
둘을 일관성있게 통일하는게 좋아 보입니다!

2024-10-07 12:56 UTC, gaeun5744 commented on app/src/main/java/woowacourse/paint/coustom/DrawingView.kt
> +                            else -> PathShape(Path().apply { moveTo(pointX, pointY) })
`PathShape`를 단순히 path를 감싸는 포장지로 쓰고있는 느낌이 드네요..! 
`moveTo` 메서드도 `PathShape`가 수행하도록 바꾸는건 어떨까요?!

2024-10-07 12:56 UTC, gaeun5744 commented on app/src/main/java/woowacourse/paint/coustom/DrawingView.kt
> +            }
만약 `Shape`에 따라 초기값이 서로 달라진다면 어떨까요?!
`INITIAL_WIDTH`에 대한 초기값도 각 객체가 가질 수 있도록 수정해주세요~

2024-10-07 12:56 UTC, gaeun5744 commented on app/src/main/java/woowacourse/paint/model/PathShape.kt
> +    }
`PathShape`를 지우개와 펜으로 둘다 사용하는 이유는, 둘의 로직이 비슷해 보여서일 것이라 생각합니다!

저는 개인적으로, 색깔은 도형의 `속성`이라 생각해서 `shape`의 속성으로 두었어요~ 
그러면 지우개와 펜은 완전히 다른 로직을 가진 객체가 될 것 같습니다!! (이건 설계를 갈아엎어야 하는 부분이라 넘어가주셔도 됩니다~)

2024-10-07 12:56 UTC, gaeun5744 commented on app/src/main/java/woowacourse/paint/model/CircleShape.kt
> +        canvas.drawCircle(centerX, centerY, radius, paint)
path가 아니라 canvas에 바로 도형을 그릴 수 있는건 처음 알았네요..!
새로운거 배워갑니당🥰

2024-10-07 12:56 UTC, gaeun5744 commented on app/src/main/java/woowacourse/paint/model/SquareShape.kt
> +) : Shape {
전체적으로 가변객체로 이루어져 있네요! 불변객체로 바꿔도 좋을 것 같아요~

2024-10-07 12:56 UTC, gaeun5744 commented on README.md
> +- 구현 예시를 참고하여 다크모드 전환 시 그림판 보드의 색상과 상태바 색상이 검은색으로 바뀌어야 한다.
영상을 보니, 다크모드로 전환시 상태바가 여전히 보라색이네요..!

2024-10-07 12:56 UTC, gaeun5744 commented on app/src/main/java/woowacourse/paint/coustom/DrawingView.kt
> +                    } else {
`ShapeType.ERASER`를 when 문에 두어도 잘 작동하는데, 따로 둔 이유가 궁금합니다!

2024-10-07 12:56 UTC, gaeun5744 commented on app/src/main/java/woowacourse/paint/model/Shape.kt
> +}
추상화를 잘 해주셨어요!!! 👍👍

2024-10-07 12:56 UTC, gaeun5744 commented on app/src/main/java/woowacourse/paint/coustom/DrawingView.kt
> +    private fun resetShape() {
메서드가 직관적이라 읽고 이해하기 좋네요...! 
리뷰하기 편했습니다

2024-10-10 01:45 UTC, chaehyuns commented on app/src/main/java/woowacourse/paint/model/SquareShape.kt
> +) : Shape {
헉 그렇네요! 알려주셔서 감사해요~

2024-10-10 01:50 UTC, chaehyuns commented on app/src/main/java/woowacourse/paint/model/SquareShape.kt
> +) : Shape {
[b3e7217](https://github.com/woowacourse/android-paint/pull/112/commits/b3e7217720c7e413195384a72f915fb6ca070eb4)

2024-10-10 02:20 UTC, chaehyuns commented on app/src/main/java/woowacourse/paint/model/ShapeType.kt
> +}
객체를 먼저 구현하고 drawing view 를 구현하다보니 통일성있게 코드를 작성하지 못했네요! 
벼리의 의견을 토대로 변경해보겠습니다!

2024-10-10 02:51 UTC, chaehyuns commented on app/src/main/java/woowacourse/paint/coustom/DrawingView.kt
> +            }
좋은 의견 감사해요 벼링~ 🌾 [2c38301](https://github.com/woowacourse/android-paint/pull/112/commits/2c383012a860e4061d5af2bb5aa3d5d59d015689)

코드가 깔끔해졌서요!

2024-10-10 02:52 UTC, chaehyuns commented on app/src/main/java/woowacourse/paint/model/PathShape.kt
> +    }
저도 이부분에 대해서 고민을 했었어요! 
현재는 로직이 비슷해보이나 추후 변경 가능 성을 생각하면 지우개와 펜을 분리해보는 것도 좋을 것 같습니다~

2024-10-10 02:56 UTC, chaehyuns commented on README.md
> +- 구현 예시를 참고하여 다크모드 전환 시 그림판 보드의 색상과 상태바 색상이 검은색으로 바뀌어야 한다.
헉 상태바와 타이틀바가 햇갈렸네요!
올바르게 수정했습니다! [43faa65](https://github.com/woowacourse/android-paint/pull/112/commits/43faa651832cb3e93b73b93a1227a9da9b244eba)

2024-10-10 04:30 UTC, chaehyuns commented on app/src/main/java/woowacourse/paint/coustom/DrawingView.kt
> +                    } else {
코드를 수정하다보니 이 부부을 놓친 것 같아요 벼리 감사합니당~

2024-10-10 05:33 UTC, gaeun5744 approved these changes
안녕하세요 채채~ 
리뷰 너무 잘 반영해주셨습니다! 고생 많으셨어요~
다음 미션을 위해 approve 하겠습니다! 다음 미션도 파이팅!!

2024-10-10 05:34 UTC, merged