[해나] 뷰 챌린지 미션 2, 3단계 제출합니다.
woowacourse/android-paint pull request #113
Opened 2024-10-07 07:32 UTC by hxeyexn

안녕하세요 서기!
2, 3단계 미션 제출합니다! 리뷰 잘 부탁드리겠습니다~

## 시연 영상
https://github.com/user-attachments/assets/a7448f17-1209-4169-ab5b-cbf5b3ef6d27

<br>

## 태블릿 세로모드 
|대응 전|대응 후|
|:---:|:---:|
|![태블릿 세로모드 대응전](https://github.com/user-attachments/assets/b85d2f60-14de-47cb-bed5-e79ab74b6e81)|![태블릿 세로모드 대응 후](https://github.com/user-attachments/assets/58249512-b454-48cf-95a2-1e9e802ca304)|

<br>

## 태블릿 가로모드
|대응 전|대응 후|
|:---:|:---:|
|![태블릿 가로모드 대응 전](https://github.com/user-attachments/assets/56aac662-4639-4991-9194-50a949195da7)|![태블릿 가로모드 대응 후](https://github.com/user-attachments/assets/0cab129d-455b-4df5-ac50-2d06ee78e28d)|

<br>

## 다크모드 대응
<img src = "https://github.com/user-attachments/assets/a62c9975-424e-49ae-8e0b-a613a05819b8" width="270" height= "555">

2024-10-07 08:53 UTC, Namyunsuk requested changes
안녕하세요 해나!!
2, 3단계 구현 수고 많으셨습니다!! 너무 잘 구현해주셨네요👍👍👍

저랑 다르게 구현해 주신 부분들이 있어서 재밌었네요😃
코멘트 몇개 남겼으니 확인해 보시면 될 것 같아요!

미션 끝까지 화이팅이에요!💪💪

2024-10-07 08:53 UTC, Namyunsuk commented on app/src/main/java/woowacourse/paint/BrushHandler.kt
> +}
브러쉬를 선택했을 때 동작을 인터페이스로 정의해주셨네요!

2024-10-07 08:53 UTC, Namyunsuk commented on README.md
> +- [x] 다크 모드 대응
README작성 굿~~~👍

2024-10-07 08:53 UTC, Namyunsuk commented on app/src/main/java/woowacourse/paint/drawingboard/Drawing.kt
> +class Drawing(val path: Path, val paint: Paint) {
Line에서 Drawing으로 재탄생 했네용

2024-10-07 08:53 UTC, Namyunsuk commented on app/src/main/java/woowacourse/paint/drawingboard/DrawingBoard.kt
> +                if (removeItemIndex != INVALID_INDEX) drawings.removeAt(removeItemIndex)
지우개 기능을 저와 다르게 구현해주셔서 신기했어요! 이렇게도 할 수 있네요..
그런데 실제로 사용을 해보는데 에뮬이어서 그런지 몰라도 지우개가 잘 작동하지 않는 것 같아요..! 한번 확인해보시면 좋을 것 같아용

2024-10-07 08:53 UTC, Namyunsuk commented on app/src/main/java/woowacourse/paint/MainActivity.kt
> +        setupToolPanel(style = Paint.Style.STROKE, visibleState = View.VISIBLE)
펜을 클릭할 때만 `RangeSlider`보이도록 하셨네요ㅋㅋㅋㅋ
ui ux에 진심인 해나...
lms에 있는 예제보다 더 괜찮은 것 같기도 하네요ㅎㅎ

2024-10-07 08:53 UTC, Namyunsuk commented on app/src/main/java/woowacourse/paint/drawingboard/DrawingBoard.kt
> +
Drawing으로 그린 그림들과 `BrushType`을 DrawingBoard가 같이 가지고 있는게 조금 어색할 수 있을 것 같아요..!
`BrushType`과 각 타입에 따른 동작을 Drawing이 하도록 하는 것은 어떨까요?

2024-10-09 06:47 UTC, hxeyexn commented on app/src/main/java/woowacourse/paint/MainActivity.kt
> +        setupToolPanel(style = Paint.Style.STROKE, visibleState = View.VISIBLE)
도형이랑 지우개를 사용할 때는 RangeSlider가 하는 역할이 없어서 자꾸 눈에 거슬리더라구요,,, ㅎㅎ

2024-10-09 18:42 UTC, hxeyexn commented
안녕하세요 서기!!
프로젝트 이슈가 발생해서 리뷰 반영이 늦었네요..! 

> Drawing으로 그린 그림들과 BrushType을 DrawingBoard가 같이 가지고 있는게 조금 어색할 수 있을 것 같아요..!
> BrushType과 각 타입에 따른 동작을 Drawing이 하도록 하는 것은 어떨까요?

위 코멘트를 반영하다보니 욕심(?)이 생겨서 변경점이 너무 많아졌습니다.. 
주요 변경사항은 아래와 같습니다!

### 1. Brush Type 변경 책임
Brush Type을 변경하는 책임을 Drawing Board에서  Brush Type이 가지도록 변경했습니다.
> 관련 커밋 : [7d8fec0](https://github.com/woowacourse/android-paint/pull/113/commits/7d8fec0d106308fac74512c7b2d98bd608bc5fea)

### 2. Drawings 객체 구현
Drawings 객체를 구현해 그림들을 보관하도록 변경했습니다.
방어적 복사를 이용해 Drawings 객체 내의 원본 drawings는 외부에서 변경하지 못하도록 구현했습니다.
> 관련 커밋 : [c7428a7](https://github.com/woowacourse/android-paint/pull/113/commits/c7428a769711b9738365dc1507c8a7888849f529)

### 3. BrushType 타입에 따른 동작을 Drawing이 하도록 변경
> 관련 커밋 : [c968d0a](https://github.com/woowacourse/android-paint/pull/113/commits/c968d0ab1d53c58aa955441461d3053e86af5d6c)

### 4. Pen, Circle, Rectangle, Eraser 객체 구현
- Drawing을 추상 클래스로 변경했습니다.
- 각 BrushType에 맞는 그림을 그리는 로직들을 각각의 객체(Pen, Circle, Rectangle, Eraser)가 가지도록 변경했습니다.
> 관련 커밋 : [8fe081a](https://github.com/woowacourse/android-paint/pull/113/commits/8fe081a72472b0528def13a58f86a11e0e561727)

### 5. 지우개 버그
> 지우개 기능을 저와 다르게 구현해주셔서 신기했어요! 이렇게도 할 수 있네요..
그런데 실제로 사용을 해보는데 에뮬이어서 그런지 몰라도 지우개가 잘 작동하지 않는 것 같아요..! 한번 확인해보시면 좋을 것 같아용

확인해보니 굵기가 얇은 선이 지워지지 않는 버그가 있었습니다! 

`computeBounds()`는 주어진 Path 객체의 경계를 계산해서 RectF에 저장하는 역할을 해주는 데, Path가 너무 얇을 때에는 터치된 위치와 해당 선의 영역이 정확히 일치하기 어려워서 발생한 버그입니다. 

해당 버그를 해결하기 위해 `inset` 메서드를 이용해서 RectF 주변에 padding을 주어 더 넓은 영역이 선택될 수 있게 변경했습니다. 
<img width="641" alt="image" src="https://github.com/user-attachments/assets/d8e043c4-a311-4a94-b289-480afecc5867">

추가로 지우개 동작이 좀 더 자연스러울 수 있도록 기본 선의 굵기를 1f에서 10f로 설정했습니다.

반영 커밋: [42a25c6](https://github.com/woowacourse/android-paint/pull/113/commits/42a25c6fd4909c8ff976d313207d70d0e08067e2), [8d821a8](https://github.com/woowacourse/android-paint/pull/113/commits/8d821a8faf707d26d5e96a49a62fbc0d9af2ed9b), [5aa71b7](https://github.com/woowacourse/android-paint/pull/113/commits/5aa71b7564d2ec084451d419bdcb9e590a390b2f)

2024-10-09 18:43 UTC, hxeyexn commented on app/src/main/java/woowacourse/paint/drawingboard/DrawingBoard.kt
> +                if (removeItemIndex != INVALID_INDEX) drawings.removeAt(removeItemIndex)
확인해보니 굵기가 얇은 선이 지워지지 않는 버그가 있었습니다!

`computeBounds()`는 주어진 Path 객체의 경계를 계산해서 RectF에 저장하는 역할을 해주는 데, Path가 너무 얇을 때에는 터치된 위치와 해당 선의 영역이 정확히 일치하기 어려워서 발생한 버그입니다.

해당 버그를 해결하기 위해 `inset `메서드를 이용해서 RectF 주변에 padding을 주어 더 넓은 영역이 선택될 수 있게 변경했습니다.
<img width="648" alt="image" src="https://github.com/user-attachments/assets/83519e0b-d164-4c4d-aa42-881a2658ff0d">

추가로 지우개 동작이 좀 더 자연스러울 수 있도록 기본 선의 굵기를 1f에서 10f로 설정했습니다.

2024-10-09 18:46 UTC, hxeyexn commented on app/src/main/java/woowacourse/paint/drawingboard/DrawingBoard.kt
> +
brush type 변경 책임을 BrushType에 부여하고 BrushType과 각 타입에 따른 동작을 Drawing이 하도록 변경했습니다!

반영 커밋 : [7d8fec0](https://github.com/woowacourse/android-paint/pull/113/commits/7d8fec0d106308fac74512c7b2d98bd608bc5fea) , [c968d0a](https://github.com/woowacourse/android-paint/pull/113/commits/c968d0ab1d53c58aa955441461d3053e86af5d6c)

2024-10-10 08:40 UTC, Yunseok-Nam approved these changes
안녕하세요 해나🦋
변경 사항이 많으셨을 텐데 너무 잘 구현해 주셨네요👍
각 타입별로 객체를 만들어 주신게 인상깊었어요😊

이번 미션 정말 고생 많으셨습니다!!
다음 미션을 위해 여기서 마무리 할게요!!
다음 미션도 화이팅!💪

2024-10-10 08:40 UTC, Yunseok-Nam commented on app/src/main/java/woowacourse/paint/BrushType.kt
> +    }
오호 이제 BrushTyped에서 타입을 관리해주네요

2024-10-10 08:40 UTC, Yunseok-Nam commented on app/src/main/java/woowacourse/paint/drawingboard/Drawing.kt
> +                    Drawings.removeDrawing(removeItemIndex)
이제 Drawing이 그림을 그리는 주체가 되었네요!
훨씬 자연스러워 진 것 같아요👍👍

2024-10-10 08:40 UTC, Yunseok-Nam commented on app/src/main/java/woowacourse/paint/drawingboard/Eraser.kt
> +            if (newBounds.contains(x, y)) return index
padding으로 오류 해결해주셨네요!
사용해보니깐 이제 잘 지워지네요ㅎㅎ
고생하셨숨다👍👍👍

2024-10-10 08:40 UTC, Yunseok-Nam commented on app/src/main/java/woowacourse/paint/drawingboard/Eraser.kt
> +            bounds.inset(PADDING, PADDING)
오 inset메서드로 한번에 처리할 수 있나보네요

2024-10-10 08:40 UTC, merged