[멘델] 뷰 챌린지 미션 1단계 제출합니다.
woowacourse/android-paint pull request #15
Opened 2023-09-29 16:17 UTC by rhthrhrl0

안녕하세요 빅스~ 이번 미션 잘부탁드립니다~ :) 
스텝1의 기본 요구 사항만 구현하고 추가적인 기능은 없고, LMS에 나온 사진대로 만들어봤습니다.

색 변동의 유연성을 위해, 하단 색상 선택 리스트는 리사이클러뷰로 구현했습니다.
또한, 해당 리사이클러뷰의 BoardColorItem의 isSelected 속성은 일단 만들어 두기만 하고, 그걸 실제로 뷰로 보여주고 있진 않습니다(위에 체크박스 하나 놔서 적용 유무를 시각적으로 보여주게 하려다가, 스텝2가 디자인이 어떻게 나올지 몰라서 내비뒀습니다).

제가 이번에 만든 커스텀뷰는 PaintBoard 입니다. 저는 커스텀뷰를 만들 때, xml에 데이터바인딩을 지원하고 또한 코드상으로도 속성 변경이 되는 것을 권장해서, 바인딩 어댑터를 사용해서 속성 정의를 했습니다. 물론 별도로 지정해주지 않아도 각자 기본값이 존재하기 때문에 유저가 필요하다면, 사용하면 되도록 만들었습니다.

빅스와 추가적으로 하고 싶은 얘기는 커스텀뷰의 회전 대응과 관련된 내용입니다. 빅스가 회전대응을 한 것으로 들었던 것 같은데, 저는 SavedState와 뷰모델 둘 중 어디에서 저장해줘야 할지 고민하다가 그림을 많이 그리면 데이터가 너무 커질까 싶어서, 뷰모델에 저장하고 복구하는 방식을 선택했습니다. 혹시 빅스는 어떻게 하셨는지와 해당 방식을 선택한 이유가 궁금하네요!

남은 추석 연휴 잘보내세요 빅스~~ 👍 
![image](https://github.com/woowacourse/android-paint/assets/67176829/bc054a1e-7736-4249-bf22-e5dbb85a8338)

2023-09-30 12:48 UTC, briandr97 requested changes
### 화면 회전에 대한 답변
사실 저는 화면 회전에 대응하지 않았습니다. 현재 화면이 회전되면 그림판이 초기화 됩니다. 고려해야할 것들이 많아보여서 대응하지 않았는데요. 고려사항들에 대해 말씀드리겠습니다.

구성 변경에 대응하기 위해 SavedState와 ViewModel을 고려하셨고 ViewModel을 적용하셨다고 하셨는데, 사실 이렇게 해도 문제가 발생합니다.
저장된 Path의 좌표들이 세로 화면을 기준이기 때문이죠. 가로 화면이 되었을 때는 예상과는 조금은 다른 그림을 마주하게 될 겁니다.

그러므로 SavedState를 사용하던, ViewModel을 사용하던 화면 회전에 완벽하게 대응하기 위해선 가로모드와 세로모드를 구분해야합니다.
가로모드와 세로모드를 구분하고 (아마도 onSizeChanged에서의 값들을 통해) 처음 시작한 모드로 고정해야 할 것 같습니다.
즉, 세로모드로 시작했다면 가로로 화면 회전을 했을 때도 양 옆에 여백을 주고 세로 캔버스를 보여줘야 할 것 같습니다.

생각보다 해야할 것들이 많을 것 같아서 저도 생각만하고 구현하지는 않았습니다.
SavedState와 ViewModel 중 어디에 저장해야할지도 많이 고민했는데 아직 답을 내리지는 못했습니다. (ViewModel에 Path를 보관하기 싫어서..)

### 코멘트
저는 xml에서 추가 속성을 지정하게 하진 않았는데 멘델 덕분에 볼 수 있어서 좋았습니다.
화면 회전에 대한 부분은 다음에 같이 얘기해봐도 재밌을 것 같네요~!

2023-09-30 12:48 UTC, briandr97 commented on app/src/main/java/woowacourse/paint/customView/PaintBoard.kt
> +    }
`PaintBoard`에 대한 attrs를 따로 두어 xml에서 속성들을 지정할 수 있도록 한 점이 재밌었습니다.
xml에서 지정되지 않는 경우까지 생각한 것도 좋았습니다.

2023-09-30 12:48 UTC, briandr97 commented on app/src/main/java/woowacourse/paint/customView/PaintBoard.kt
> +        get() = Path(_drawingPath)
현재는 이미 그려진 `drawnPaths`와 현재 그리는 중인 `drawingPaths` 이렇게 두 가지로 나뉘어져 있는데 두 가지를 하나로 합치고 `drawingPaths`를 `drawnPaths`의 마지막 원소로 볼 수도 있을 것 같습니다! 또 `drawnPaths`를 일급 컬렉션으로 묶어볼 수도 있을 것 같아요!

2023-09-30 12:48 UTC, briandr97 commented on app/src/main/java/woowacourse/paint/customView/PaintBoard.kt
> +    private var defaultStrokeWidth: Float = (minStrokeWidth + maxStrokeWidth) / 2
저는 strokeWidth의 min, max, default 값을 그냥 하드코딩으로 넣어주었는데 이렇게 min과 max를 지정하고 그에 따라 default값도 변경되는 점이 좋았습니다.

2023-09-30 12:48 UTC, briandr97 commented on app/src/main/java/woowacourse/paint/customView/PaintBoard.kt
> +    override fun onDraw(canvas: Canvas?) {
`onDraw`의 인자를 `canvas: Canvas`로 nullable하지 않도록 변경해볼 수 있을 것 같습니다

2023-09-30 12:48 UTC, briandr97 commented on app/src/main/java/woowacourse/paint/customView/PaintBoard.kt
> +            }
`onTouchEvent`의 **ACTION_UP**에서도 `lineTo`를 호출해주면 좋을 것 같습니다.
현재는 드래그를 하지 않고 클릭을 하면 아무것도 그려지지 않는 상황인데 **ACTION_UP**에서도 `lineTo`를 호출해준다면 클릭했을 때 점이 찍힐 것입니다!

2023-09-30 12:48 UTC, briandr97 commented on app/src/main/java/woowacourse/paint/ui/main/MainViewModel.kt
> +        get() = _appliedColor
이번 요구사항에서는 색상 변경을 눌러야 색상이 변경돼서 어쩔 수 없이 이렇게 됐지만, 멘델이 말한대로 isSelected 속성을 사용하게 된다면 하나로 합칠 수 있겠네요~!

2023-09-30 13:07 UTC, boogi-woogi requested changes
꼼꼼히 작성해주신 테스트 코드와, 도메인 분리가 인상적이었습니다!!

베르의 코드를 보고 이번 미션에서 생각하지 않았던 부분들에 대해 생각해볼 수 있어서 좋았습니다.

궁금한점 위주로 코멘트 남겼습니다~ (개인적으로 지금 단계에서 더 고칠 부분들은 없다고 생각합니다ㅋㅋㅋ) 남은 추석 연휴 잘 보내세용:smile:

2023-10-01 12:19 UTC, rhthrhrl0 commented on app/src/main/java/woowacourse/paint/customView/PaintBoard.kt
> +            }
헉 생각해보니, 그걸 안해주고 있었네요... 감사합니다~

2023-10-01 16:27 UTC, rhthrhrl0 commented on app/src/main/java/woowacourse/paint/customView/PaintBoard.kt
> +        get() = Path(_drawingPath)
drawnPaths로 통합하는 것 좋은 것 같습니다! 또한, 말씀해주신대로, PaintBoard의 역할이 너무 많아진 것 같아서, 일급 컬렉션을 관리하는 클래스와 페인트 정보를 관리하는 클래스를 PaintBoard로부터 분리했습니다.

2023-10-01 16:35 UTC, rhthrhrl0 commented
> ### 화면 회전에 대한 답변
> 사실 저는 화면 회전에 대응하지 않았습니다. 현재 화면이 회전되면 그림판이 초기화 됩니다. 고려해야할 것들이 많아보여서 대응하지 않았는데요. 고려사항들에 대해 말씀드리겠습니다.
> 
> 구성 변경에 대응하기 위해 SavedState와 ViewModel을 고려하셨고 ViewModel을 적용하셨다고 하셨는데, 사실 이렇게 해도 문제가 발생합니다. 저장된 Path의 좌표들이 세로 화면을 기준이기 때문이죠. 가로 화면이 되었을 때는 예상과는 조금은 다른 그림을 마주하게 될 겁니다.
> 
> 그러므로 SavedState를 사용하던, ViewModel을 사용하던 화면 회전에 완벽하게 대응하기 위해선 가로모드와 세로모드를 구분해야합니다. 가로모드와 세로모드를 구분하고 (아마도 onSizeChanged에서의 값들을 통해) 처음 시작한 모드로 고정해야 할 것 같습니다. 즉, 세로모드로 시작했다면 가로로 화면 회전을 했을 때도 양 옆에 여백을 주고 세로 캔버스를 보여줘야 할 것 같습니다.
> 
> 생각보다 해야할 것들이 많을 것 같아서 저도 생각만하고 구현하지는 않았습니다. SavedState와 ViewModel 중 어디에 저장해야할지도 많이 고민했는데 아직 답을 내리지는 못했습니다. (ViewModel에 Path를 보관하기 싫어서..)
> 
> ### 코멘트
> 저는 xml에서 추가 속성을 지정하게 하진 않았는데 멘델 덕분에 볼 수 있어서 좋았습니다. 화면 회전에 대한 부분은 다음에 같이 얘기해봐도 재밌을 것 같네요~!

저도 가로 세로 화면 비율에 대한 대응은 아직 생각하지 않았습니다!  만약 다음 미션들에서 이것에 대한 대응이 필요해진다면, 그때 다시 이 주제로 얘기를 해보죠!!

2023-10-01 18:50 UTC, briandr97 approved these changes
짧은 시간에 구조적으로 많은 변화가 있었네요!
`PaintBoard`에 쏠려있던 역할들을 각각의 객체로 나누면서 더 좋아진 것 같다고 느낍니다.
제가 생각했던 (생각만 했던) 구조와도 많이 흡사해서 놀라기도 하고 제 생각이 이상하진 않았구나 라는 안도감도 함께 느낍니다.

제 생각만 몇 가지 남겼고 이미 1단계는 너무나도 잘 충족하신 것 같아서 이만 머지하도록 하겠습니다!
혹시나 질문들에 답변 달아주시게 되신다면 달고 알려주시면 감사하겠습니다!

2023-10-01 18:50 UTC, briandr97 commented on app/src/main/java/woowacourse/paint/util/TypedArrayExt.kt
> +    getInt(index, -1).let { if (it >= 0) enumValues<T>()[it] else default }
맨날 Enum 내부에서 values만 호출해봤는데 enumValues라는게 있었군요 신기하네요!

2023-10-01 18:50 UTC, briandr97 commented on app/src/main/java/woowacourse/paint/customView/content/Content.kt
> +}
`Content`를 인터페이스로 만들면서 `Stroke` 뿐만 아니라 다른 것들도 추가적으로 만들 수 있도록 만들어주신 부분 너무 좋습니다. 다만 제 생각과 조금 다른 부분이 있어서 말씀고자합니다. 함께 이야기해봐요!

(이 부분에 대해서는 저도 아직 상상일 뿐이라 확신하진 못하지만) 현재는 **ACTION_MOVE**와 **ACTION_UP**일 경우 같은 행동이 일어나므로 `action`함수 하나로 가능했지만, 다른 `ContentType`이 추가될 경우 각 `MotionEvent`별로 다른 행동이 일어날 수도 있지 않을까요?

그래서 `Content`인터페이스에서 `action`보다 각 `MotionEvent`별로 함수를 갖는것은 어떨까? 하는 생각을 해봤습니다. 멘델은 어떻게 생각하시나요?

2023-10-01 18:50 UTC, briandr97 commented on app/src/main/java/woowacourse/paint/customView/PaintBoard.kt
>          }
저도 `ContentType`과 비슷한 역할을 하는 녀석을 떠올렸었습니다.
`ContentType`과 같은 역할을 떠올렸던 이유는 앞으로 선 뿐만 아니라 `Rect`, `Oval`과 같은 도형들도 추가될 수 있다고 생각했기 때문입니다.
그래서 저는 `ContentType`이 현재 사용중인 툴(선, 사각형, 원 등)에 따라 동적으로 변하는 모습을 생각했었습니다.
그런데 멘델의 구조에서는 `ContentType`이 xml 속성을 통해 정적으로 지정되는 것 같아서 질문을 남깁니다~! 

주제넘게 제가 예상해보자면 멘델은 이 그림판 코드를 누군가 사용할 수도 있는 라이브러리로 생각하고, 다른 개발자가 선을 그리는 그림판이 아닌 도형 등 다른 무언가를 그리는 그림판을 만들 수도 있다고 생각하신 것 같습니다. 즉, 한 그림판에 선, 도형 툴이 모두 있는 것이 아니고 선 그림판, 도형 그림판을 따로 만들 수 있도록 만드신 것 같습니다. 혹시 맞을까요?

2023-10-01 18:51 UTC, merged

2023-10-01 19:35 UTC, rhthrhrl0 commented on app/src/main/java/woowacourse/paint/customView/content/Content.kt
> +}
저는 그래서 일단은 action 메소드에 event 내용 전체를 넘겨주고 있습니다. 이벤트의 액션 종류가 너무 많아서, 어떤 것들은 또 다른 액션 요소가 필요할 수 있다고 생각이 들어서, 그냥 각 Content 구현체들 별로, 자신이 필요한 액션인지 판단하고, 처리해주면 될 것 같다고 생각했습니다. 실제로 현재 Stroke 같은 경우, when 문으로 처리해주고 있습니다.
![image](https://github.com/woowacourse/android-paint/assets/67176829/0aef018f-f14a-4cfb-98be-d2fb34bb00e5)

2023-10-01 19:37 UTC, rhthrhrl0 commented on app/src/main/java/woowacourse/paint/util/TypedArrayExt.kt
> +    getInt(index, -1).let { if (it >= 0) enumValues<T>()[it] else default }
저도 스택 오버플로우를 찾다가 이번에 처음 알게됐습니다!

2023-10-01 19:45 UTC, rhthrhrl0 commented on app/src/main/java/woowacourse/paint/customView/PaintBoard.kt
>          }
앗 정적으로 지정하는 것이 아닙니다! 저도 빅스랑 똑같이 생각했습니다! 현재 contentType이 데이터바인딩으로 뷰모델의 라이브데이터와 연결되어있습니다. 
![image](https://github.com/woowacourse/android-paint/assets/67176829/d463df5b-5859-4d27-8782-aa28e12c54a2)

만약 xml상에서 데이터바인딩 포맷( "@{ }" )을 사용한다면, PaintBoard에 있는 아래 프로퍼티의 세터가 호출됩니다.
그리고, PaintBoard의 생성자에 넘어오는  attrs를 활용해서 아무리 찾아도 찾아지지 않습니다.

그리고, 만약 xml상에서, 아래사진처럼, 정적으로 지정해준다면 
![image](https://github.com/woowacourse/android-paint/assets/67176829/ce083ef3-572d-41a8-bfa4-e3344e2f4751)
이때는 setter가 아니라 그냥 attrs 속성으로 넘어가게 되고, typedArray에서 찾을 수 있습니다. 


혹시 데이터바인딩을 안쓰고, 뷰바인딩을 사용하는 개발자가 초기 타입을 설정하고 싶다면, 사용하라고 이렇게 만들었습니다.