[빅스] 뷰 챌린지 미션 1단계 제출합니다.
woowacourse/android-paint pull request #18
Opened 2023-09-29 20:54 UTC by briandr97

멧돼지 안녕하세요~ 이렇게 뵙니 또 새롭네요!
멧돼지의 몽둥이 리뷰 기다리고 있습니다!
멧돼지가 절 잘 때리기 위해서 설명을 조금 드리겠습니다.

### 요구사항
- [x] 화면에 자유 곡선을 그릴 수 있다.
- [x] 도구 패널을 추가한다.
- [x] 브러시 색상을 변경할 수 있다. (브러시 색상은 빨, 주, 노, 초, 파로 한정)
- [x] 브러시 굵기를 변경할 수 있다.

### 추가 구현 사항
- [x] 지우개 기능 추가
- [x] 뒤로가기 기능 추가
- [x] 그림판 이미지 저장 기능 추가

- - -
* 그림판에 대한 핵심 구현 기능은 `PaintBoard`클래스에 있습니다.
* 상단에 펜, 지우개, 뒤로가기, 이미지저장 버튼이 있는 툴바가 현재는 `MainActivity`에 있는데, 그림판과 툴바를 합쳐서 하나의 커스텀뷰로 만들까 생각도 해봤습니다만.. 이미지 저장 기능이 누구의 역할일지에 대해 고민하다가 일단 1차는 이대로 제출하기로 결정했습니다.
* 화면 회전에 대응하는 부분도 고려는 해봤지만 아직까지 마땅한 해결책이 떠오르지 않아 패스했습니다. 멧돼지가 생각해본 해결책이 있다면 공유해주시면 감사하겠습니다!
* 사각형이나 원과 같은 도형을 그릴 수 있는 방안도 고려해봤지만 뒤로가기 기능에서 많은 변경이 생길 것 같아 우선 패스했습니다.

- - -
* 지우개
지우개 기능을 추가하였습니다.
사실 지우개 버튼만 삽입하고 펜 색상을 배경색으로 일치시킬 뿐입니다. 그래서 지우개 두께 조절은 펜에서 함께 하고있습니다.

* 뒤로가기
뒤로 가기 기능을 추가하였습니다.
Path와 해당 Path에 적용된 Paint를 하나의 Line으로 들고있고 뒤로가기를 할 경우 리스트에서 마지막 라인을 삭제합니다.

* 그림판 이미지 저장 기능 추가
그림판에 그린 그림을 이미지로 저장할 수 있는 기능을 추가하였습니다.
PaintBoard내에서 자체적으로 Canvas를 하나 생성하고, 이미지 저장을 원할 시 해당 Canvas를 통해 Line들을 비트맵에 그려서 반환합니다.
그럼 BitmapSaver를 통해 Bitmap을 파일로 저장합니다.
위 기능은 미션과 연관이 없으므로 리뷰해주지 않으셔도 됩니다.

- - -
이해를 돕기 위해 gif 파일을 첨부합니다. (배경색은 흰색인데 gif로 변환하는 과정에서 체크로 깨지네요)
펜을 이용하기 위해 태블릿에 그려봤습니다!

![revert](https://github.com/woowacourse/android-paint/assets/78788847/8a770fef-27fe-4362-90af-1d909b78a84a){: width="100" height="300"}
![eraser](https://github.com/woowacourse/android-paint/assets/78788847/b2919cd1-65f6-4b1c-b767-453b871d0743){: width="100" height="300"}
![writing](https://github.com/woowacourse/android-paint/assets/78788847/d5ac1dd0-57f1-4c95-b3d7-decc8197a0b5){: width="100" height="300"}
![save](https://github.com/woowacourse/android-paint/assets/78788847/8609b6ff-95a3-4a86-a0b0-b34d43c3b523){: width="100" height="300"}

2023-10-03 16:58 UTC, 2chang5 requested changes
고생하셨습니다!!!!!

2023-10-03 16:58 UTC, 2chang5 commented on app/build.gradle.kts
> +        minSdk = 29
오 sdk를 올리신 이유가 있을까요? 29라면 상당히 높다고 생각됩니다.

2023-10-03 16:58 UTC, 2chang5 commented on app/src/main/java/woowacourse/paint/BitmapSaver.kt
> +            put(MediaStore.Images.Media.DATE_TAKEN, System.currentTimeMillis())
하나는 초단위로 넣어주고 하나는 밀리초 단위로 넣어주신 이유가있나요? 궁금합니다!!!

2023-10-03 16:58 UTC, 2chang5 commented on app/src/main/java/woowacourse/paint/BitmapSaver.kt
> +            put(MediaStore.MediaColumns.RELATIVE_PATH, Environment.DIRECTORY_PICTURES)
혹시 RELATIVE_PATH 때문에 minsdk 를 29로 올리신건가요? 29는 많이 높다고 생각해서 버전 대응을 하시는게 좋지않을까 싶습니다.(물론 저도 이부분이 생소해서 ㅋㅋㅋㅋ 조언을 드리기가 힘드네요)

2023-10-03 16:58 UTC, 2chang5 commented on app/src/main/java/woowacourse/paint/BitmapSaver.kt
> +        val result = bitmap.compress(Bitmap.CompressFormat.JPEG, 100, outputStream)
개인적인 취향일수 있지만 저같은경우는 Bitmap.CompressFormat.JPEG, 100 요런상수들은 companion Object에 상수로 지정하면 한눈에 더들어오더라고요. 특히 이렇게 한가지형식 밖에 없을때는 더더욱 그런것 같습니다.

2023-10-03 16:58 UTC, 2chang5 commented on app/src/main/java/woowacourse/paint/BitmapSaver.kt
> +        return Result.failure(IllegalStateException("이미지 저장에 실패했습니다"))
현재 이미지를 저장하는 단계가 두가지라고 판단됩니다.
1.Uri를 획득한다.
2.저장한다.
이때 각단계가 개별적으로 실패할 수있는 상황이라고 생각합니다.
하지만 현재같은경우 둘중 어디서 실패해도 이미지 저장에 실패했습니다 라는 문구 하나만 개발자 혹은 사용자가 받게될것입니다.
물론 사용자에게 uri가 null값으로 넘어왔다 이런 것들을 노출할 필요는 없겠지만
개발자의 디버깅을 위해 null 로 넘어왔을때 간단한 로깅이라도 찍어준다면 실패상황에 대응이 더 빠를수 있다고 생각합니다.

결론은 각각의 오류상황을 개발자가 전달받을수있도록 분기하고 로그를 찍어주면 좋을것 같습니다.

2023-10-03 16:58 UTC, 2chang5 commented on app/src/main/java/woowacourse/paint/MainActivity.kt
> +    }
함수명과 행동의 매칭이 어렵다고 생각합니다. convertToolSelected 라는 함수명을 통해 펜와 지우개를 연상하기 어려웠어서 좀더 고민해보시면 좋을것 같습니다.

2023-10-03 16:58 UTC, 2chang5 commented on app/src/main/java/woowacourse/paint/MainActivity.kt
> +        val posY = binding.clCanvasTop.bottom + binding.clCanvasTop.height
posY라는 변수가 무엇을 뜻하나요? 변수명을통해서 추론하기 힘든 부분인것 같습니다.

2023-10-03 16:58 UTC, 2chang5 commented on app/src/main/java/woowacourse/paint/MainActivity.kt
> +            .onFailure { message = "이미지 저장에 실패했습니다." }
message의 경우 상수화 시켜놓으시면 어떠실까요?

2023-10-03 16:58 UTC, 2chang5 commented on app/src/main/java/woowacourse/paint/paintboard/FileNameDialog.kt
DialogFragment 같은 컴포넌트를 사용하지않고 이렇게 다이얼로그를 생성하신 이유가 있으실까요? 저는 이렇게 사용해본적이 없어서 신기하네요 ㅎㅎㅎ

2023-10-03 16:58 UTC, 2chang5 commented on app/src/main/java/woowacourse/paint/paintboard/PaintBoard.kt
> +    }
섬세하네요👍

2023-10-03 16:58 UTC, 2chang5 commented on app/src/main/java/woowacourse/paint/paintboard/PaintMode.kt
> +}
이렇게 사용된다면 enum class와 같은것 아닌가요? enum 클래스 대신 사용하신 이유가 있을까요?

2023-10-03 16:58 UTC, 2chang5 commented on app/src/main/java/woowacourse/paint/paintboard/line/Lines.kt
> +    val lines: List<Line> = _lines
이왕 방어하는거 toList까지 붙이는건 어떨까요? 레벨1의 추억이 새록새록하네요

2023-10-03 16:58 UTC, 2chang5 commented on app/src/main/java/woowacourse/paint/paintboard/line/Lines.kt
> +    }
이 함수를 추가적으로 나누신 이유가 있으신까요? 현재 상황에서는 drawingLine를 단순호출하는 형태라 필요가 없어보입니다!!!

2023-10-03 16:58 UTC, 2chang5 commented on app/src/main/java/woowacourse/paint/paintboard/PaintBoard.kt
> +    private val lines = Lines()
이 부분에서 추상화가 필요할것 같다고 생각합니다.
현재는 line만 구현해서 사용하셨는데요 다른 기능들을 추가하지 않더라도 일단 추후 도입 가능성을 위해서 추상화하면 좋은 부분이라고 생각합니다.

1. line,도형,bitmap 등등 Canvas 에 적용할 수 있는 것들을 포괄하는 추상화된 인터페이스를 생성하는것이 좋아보입니다.
이를 통하여 추후 다른 기능들이 추가되더라도 revert등등의 기능을 코드의 변화없이 가져갈 수 있다고 생각합니다.
(공통적인 부분은 인터페이스에서 명시해서 가져가야할것 같습니다. -> 이들을 관리하는 자료구조에서 순회하면서 같은 작업을 거칠수 있어야 해야 효율이 난다고 생각합니다.)
2. 현재 Lines를 통해서 line을 list 형태로 가지고 있는데 위에서 말씀드린 추상화 계층을 관리한다면 공통적인 로직들을 쉽게 다룰 수 있을것 같습니다. 하지만 현재 있는 로직들은 위치를 이동해야할수 있다고 생각합니다.

2023-10-03 16:58 UTC, 2chang5 commented on app/src/main/java/woowacourse/paint/paintboard/PaintBoard.kt
> +    }
깔끔하네요 코드가 정말 알잘딱합니다!!! 하지만 추상화, 드래그, 핀치줌 등등 더 많은것들을 적용한다면 onTouchEvent가 복잡해질것 같아서 line관련 로직은 line내부에서 전부 처리하는등 좀더 방법이 필요할것 같다고 생각합니다. (줌이랑 드래그 적용하니까 여기가 한바가지가 나오더라고요 ㅠㅠ)

2023-10-03 16:58 UTC, 2chang5 commented on app/src/main/java/woowacourse/paint/paintboard/PaintBoard.kt
> +        strokeCap = Paint.Cap.ROUND
이거 좋네요 훔쳐가겠습니다

2023-10-03 16:58 UTC, 2chang5 commented on app/src/main/java/woowacourse/paint/paintboard/line/LinesBitmap.kt
> +        return Bitmap.createBitmap(w, h, Bitmap.Config.ARGB_8888)
투명도 지원 지켜보겠습니다 ^^

2023-10-03 16:58 UTC, 2chang5 commented on app/src/main/java/woowacourse/paint/paintboard/pentool/PenColorAdapter.kt
> +    class PenColorViewHolder(
물론 비현실적일수 있지만 뷰홀더 같은경우 재활용의 가능성이 있을 수 있으니 종속적이어 보이게 Adapter 내부에 존재하는것보다 외부로 분리해내는것에 대해 어떻게 생각하시나요?

2023-10-03 16:58 UTC, 2chang5 commented on app/src/main/java/woowacourse/paint/paintboard/pentool/PenColorAdapter.kt
> +            binding.viewRvItemColorColor.backgroundTintList =
ColorColor 네이밍이 불편하군요 크흠 ...

2023-10-03 16:58 UTC, 2chang5 commented on app/src/main/java/woowacourse/paint/paintboard/pentool/PenColors.kt
> +    private var currentPosition: Int = 0
@ColorRes어노테이션 적용이 적절한건가요?

2023-10-03 16:58 UTC, 2chang5 commented on app/src/main/java/woowacourse/paint/paintboard/pentool/PenColors.kt
> +    private var currentPosition: Int = 0
currentPenColor 에 적용하는것이 적절한것 같습니다!!

2023-10-03 16:58 UTC, 2chang5 commented on app/src/main/res/layout/activity_main.xml
> +        </androidx.constraintlayout.widget.ConstraintLayout>
이 부분도 커스텀뷰로 묶어버리면 나중에 편할수도 있다고 생각합니다. 뷰 크기를 늘리면 이런 펜툴 은 것들이 화면을 sticky하게 쫓아다니게 하는부분도 생각보다 복잡해서 하나만 관리할 수 있도록 커스텀뷰로 관리해보는 방향을 고려해보시는것도 좋을것 같습니다.

2023-10-07 10:57 UTC, briandr97 commented on app/src/main/java/woowacourse/paint/BitmapSaver.kt
> +            put(MediaStore.Images.Media.DATE_TAKEN, System.currentTimeMillis())
`DATE_TAKEN` 값은 milli second 단위까지 기록되고 `DATE_ADDED`, `DATE_MODIFIED`는 second 단위까지만 기록됩니다!

2023-10-07 11:02 UTC, briandr97 commented on app/src/main/java/woowacourse/paint/BitmapSaver.kt
> +            put(MediaStore.MediaColumns.RELATIVE_PATH, Environment.DIRECTORY_PICTURES)
네 아마 그랬던 것 같은데 26으로 내려도 잘 되네요 다시 내렸습니다!

2023-10-07 11:02 UTC, briandr97 commented on app/build.gradle.kts
> +        minSdk = 29
https://github.com/woowacourse/android-paint/pull/18#discussion_r1349505282

2023-10-07 11:45 UTC, briandr97 commented on app/src/main/java/woowacourse/paint/BitmapSaver.kt
> +        val result = bitmap.compress(Bitmap.CompressFormat.JPEG, 100, outputStream)
저는 개인적으로 위와 같이 한번만 사용되고 압축 비율과 같은 값일 때는 숫자가 바로 보이는 것이 직관적이라고 느껴집니다. 코드를 보고 바로 몇 퍼센트인지 알 수 있으니까요!

하지만 여러 의견을 경험해보고자 리뷰를 반영해봤습니다!

2023-10-07 11:45 UTC, briandr97 commented on app/src/main/java/woowacourse/paint/BitmapSaver.kt
> +        return Result.failure(IllegalStateException("이미지 저장에 실패했습니다"))
리뷰를 반영하여 로그를 찍어주었습니다.
이런 상황에서 로그를 작성해보는게 처음이라 보시고 개선 사항이 있다면 말씀해주시면 감사하겠습니다!

2023-10-07 11:50 UTC, briandr97 commented on app/src/main/java/woowacourse/paint/MainActivity.kt
> +    }
`convertButtonIsSelected`로 바꿔봤는데 저도 썩 마음에 들지는 않습니다. 혹시 추천해주실만한 네이밍 있으실까요?

2023-10-07 11:56 UTC, briandr97 commented on app/src/main/java/woowacourse/paint/MainActivity.kt
> +        val posY = binding.clCanvasTop.bottom + binding.clCanvasTop.height
보여줄 PenToolDialog의 Y좌표를 뜻합니다!

```kotlin
private fun showPenToolDialog() {
    val coordinateY = binding.clCanvasTop.bottom + binding.clCanvasTop.height
    penToolDialog.setCoordinateY(coordinateY)
    penToolDialog.show()
}
```
와 같이 조금 더 명시적으로 바꿔보았습니다.
조금 더 의미가 와닿을까요?

2023-10-07 11:58 UTC, DYGames commented on app/src/main/java/woowacourse/paint/MainActivity.kt
> +    }
toogleDrawToolSelection() 어떤가요

2023-10-07 12:00 UTC, briandr97 commented on app/src/main/java/woowacourse/paint/MainActivity.kt
> +            .onFailure { message = "이미지 저장에 실패했습니다." }
사용자에게 보여질 글자라 strings로 리소스화 하였습니다!

2023-10-07 15:32 UTC, briandr97 commented on app/src/main/java/woowacourse/paint/paintboard/FileNameDialog.kt
별 생각없이 Dialog를 사용했는데 저도 리뷰 덕분에 좀 찾아보니 `DialogFragment`를 사용하는 것이 더 권장되는 방법이네요.
`DialogFragmnet`는 기본적으로 `Fragment`여서 Activity에서 관리해주기 때문에 더 편리하다고 하네요!
아직 체감은 안되지만,, 두 개의 다이얼로그 모두 변경해주었습니다!

2023-10-07 15:38 UTC, briandr97 commented on app/src/main/java/woowacourse/paint/paintboard/PaintMode.kt
> +}
맞습니다. 별 다른 이유가 없어 enum class로 변경하였습니다.

2023-10-07 15:43 UTC, briandr97 commented on app/src/main/java/woowacourse/paint/paintboard/line/Lines.kt
> +    val lines: List<Line> = _lines
`lines`를 현재 외부에서 사용하지 않아 우선 삭제하였습니다.
더불어 `currentLine`도 private으로 변경했습니다.

2023-10-07 15:45 UTC, briandr97 commented on app/src/main/java/woowacourse/paint/paintboard/line/Lines.kt
> +    }
현재 Lines에서는 필요가 없는 상태입니다. 그러나 추후 같은 인터페이스를 구현하게 될 Rect나 Oval 등의 도형이 추가되었을 때는 finish에 대한 항목이 생길 것 같아서 우선 저런식으로 만들어두었습니다.

2023-10-07 15:47 UTC, briandr97 commented on app/src/main/java/woowacourse/paint/paintboard/PaintBoard.kt
> +    private val lines = Lines()
맞습니다. 저도 추후 도형 등이 추가되면 하나의 인터페이스로 관리할 예정이었습니다.
그러나 1단계에서 너무 욕심을 부리다보니 나중에 힘이 빠져 일단 저렇게 두었네요.
마침 2단계에서 해당 기능들이 요구사항이니 2단게에서 구현해도 될까요?

2023-10-07 15:48 UTC, briandr97 commented on app/src/main/java/woowacourse/paint/paintboard/PaintBoard.kt
> +    }
감사합니다! 줌이나 드래그는 생각해보지 못했는데 그런 부분도 있었군요!
추상화는 저도 생각해본 부분이라 아마 2단계에서 추상체를 만들면서 선, 도형 등 그려지는 모든 것들이 하나로 추상화 될 예정입니다!

2023-10-07 15:49 UTC, briandr97 commented on app/src/main/java/woowacourse/paint/paintboard/PaintBoard.kt
> +        strokeCap = Paint.Cap.ROUND
저도 어디서 보고 온 것입니다 ㅋㅋ 마음껏~!~!

2023-10-07 15:49 UTC, briandr97 commented on app/src/main/java/woowacourse/paint/paintboard/line/LinesBitmap.kt
> +        return Bitmap.createBitmap(w, h, Bitmap.Config.ARGB_8888)
ㅋㅋㅋ 형광펜 가보자잇

2023-10-07 15:54 UTC, briandr97 commented on app/src/main/java/woowacourse/paint/paintboard/pentool/PenColorAdapter.kt
> +    class PenColorViewHolder(
저는 뷰홀더를 재활용한다는 측면은 사실 잘 고려하지 않습니다.
지금까지 수많은 리사이클러뷰를 만들며서 뷰홀더를 재활용할만한 상황이 한 번도 없었기 때문입니다.
또한 당장은 같더라도 추후에는 조금씩 변경될 수 있으므로 뷰홀더는 재사용하지 않는 것이 좋아보입니다.

하지만 뷰홀더를 외부로 분리하는 경우도 있는데요, 어댑터나 뷰홀더의 코드가 길어지면 그렇습니다.
코드가 길어져 보기가 어렵다면 분리합니다. 다만 그렇지 않다면 한 곳에 있는 것이 코드를 이해하기 훨씬 빨라서 짧다면 한 곳에 놓는 것을 선호합니다.

다만 멧돼지의 시선을 따라 변경해보았습니다!

2023-10-07 15:56 UTC, briandr97 commented on app/src/main/java/woowacourse/paint/paintboard/pentool/PenColorAdapter.kt
> +            binding.viewRvItemColorColor.backgroundTintList =
컴포넌트 접두사: view
위치: RvItemColor
설명: Color

입니다 ㅋㅋ

2023-10-07 16:01 UTC, briandr97 commented on app/src/main/java/woowacourse/paint/paintboard/pentool/PenColors.kt
> +    private var currentPosition: Int = 0
어랏.. 실수로 잘못 적용한 것 같습니다. 감사합니다~
지웠습니다!

2023-10-07 16:02 UTC, briandr97 commented on app/src/main/res/layout/activity_main.xml
> +        </androidx.constraintlayout.widget.ConstraintLayout>
좋은 제안 감사합니다. 추후 시간이 생기면 도전해보겠습니다!

2023-10-09 03:12 UTC, 2chang5 commented on app/src/main/java/woowacourse/paint/BitmapSaver.kt
> +        return Result.failure(IllegalStateException("이미지 저장에 실패했습니다"))
예쁘게 잘 처리하셨다고 생각합니다, 몇가지 조언을 드리자면 
1. TAG같은경우 클래스 명을 사용하는것이 목적이라면 `this.javaClass.name`이런식으로 사용하는것이 추후 클래스의 명칭이 변경되었을때를 대비할 수 있다고 생각합니다.
2. 메시지를 명시적으로 표시하는것이 좋을 수 있다고 생각합니다. 에러를 접하는 시점이 당장 이 기능을 만드는 시점이라면 간소화된 에러메시지도 얼추 파악할 수 있습니다.
하지만 시간이 많이 지난 시점에 만난 에러메시지를 throwable 에 붙어있는 기본메시지 등으로 만난경우 에러의 원인을 파악하기 굉장히 힘든경우가 빈번합니다. 이를 대비하기 위해 에러메시지는 꼼꼼할수록 좋다고 생각됩니다.

2023-10-09 03:13 UTC, 2chang5 commented on app/src/main/java/woowacourse/paint/MainActivity.kt
> +    }
코건이 제시한 DrawTool 이라는 단어가 직관적이네요  ㅎㅎㅎ

2023-10-09 03:14 UTC, 2chang5 commented on app/src/main/java/woowacourse/paint/MainActivity.kt
> +        val posY = binding.clCanvasTop.bottom + binding.clCanvasTop.height
네 좋습니다!!! 축약어만 아니라면 어떤것도 좋은것 같습니다.

2023-10-09 03:16 UTC, 2chang5 approved these changes
고생하셨씁니다 빡스 다음미션 후딱하세요

2023-10-09 03:16 UTC, merged