[코건] 뷰 챌린지 미션 1단계 제출합니다.
woowacourse/android-paint pull request #2
Opened 2023-09-26 08:46 UTC by DYGames

안녕하세요 산쿤 ㅋ

### 미션 요구 사항
- 자유 곡선
    - 부드러운 곡선
    - 한번 터치시 점
- 도구 패널
    - 브러시 색상 변경
    - 굵기 변경

추가 요구 사항 (self)
- 굵기
- 색상 정보 저장
- 부드러운 곡선
- 일회 터치시 점
를 구현했습니다.

```kotlin
class PaintPath(data: List<Pair<Path, Paint>> = emptyList())
```

이렇게 저장했서요. 이렇게 한 이유는 그린거 되돌리기나 그림 정보 전송을 위함입니다.

원래는 기존에 그린 정보를 Bitmap으로 캐싱하고 그 위에 Path로 Draw하려 했는데 오히려 연산이 더 들것 같아서 현재 방식이 낫다고 생각했어요.

산군도 화팅ㅋ

<img width="200" alt="image" src="https://github.com/woowacourse/android-paint/assets/14182640/a58545c2-31c7-4e02-9a54-a28d8b689fa3">

2023-09-30 05:49 UTC, s9hn requested changes
늦어서 죄송합니다 덕분에 즐거운 추석이었읍니다
오늘 약속 재밌게 보내시고 질문있으면 언제든 단톡주세요

코건건코 즐추~

2023-09-30 05:49 UTC, s9hn commented on app/src/main/res/layout/view_palette.xml
> +        android:background="?attr/selectableItemBackgroundBorderless"
오 리플 넣어줄생각은 못했는데 섬세한남자네요

2023-09-30 05:49 UTC, s9hn commented on app/src/main/java/woowacourse/paint/palette/PaletteViewHolder.kt
> +class PaletteViewHolder(val binding: ViewPaletteBinding, onClick: (Int) -> Unit) :
onClick으로 넘겨주는 인자가 무엇인지 명시해줘도 좋아보입니다

2023-09-30 05:49 UTC, s9hn commented on app/src/main/java/woowacourse/paint/palette/PaletteAdapter.kt
> +class PaletteAdapter(private val data: List<Int>, private val onClickPalette: (Int) -> Unit) :
아이템을 어댑터가 소지하고있는것에 대해 어떻게 생각하시나요

2023-09-30 05:49 UTC, s9hn commented on app/src/main/java/woowacourse/paint/palette/PaletteAdapter.kt
> +        if (holder.binding.paletteImageButton.drawable != null) DrawableCompat.setTint(
어댑터에서 뷰홀더가 소지하고 있는 뷰를 직접 참조하는 이유가 있나요?

2023-09-30 05:49 UTC, s9hn commented on app/src/main/java/woowacourse/paint/PaintView.kt
> +                startTouch(event.x, event.y)
startTouch 함수네이밍이 좀 더 구체적인것은 어떨까요? 현재 Touch에 관한 네이밍들은 MotionEvent.Action_Down, ACTION_Move 들과 별 다를바가 없어보입니다

2023-09-30 05:49 UTC, s9hn commented on app/src/main/java/woowacourse/paint/PaintView.kt
> +            pointX, pointY
ㅋㅋ 정답맞았군

2023-09-30 05:49 UTC, s9hn commented on app/src/main/java/woowacourse/paint/PaintView.kt
> +        paths.add(currentPath to currentPaint)
오 터치가 끝난시점에 저장해줄생각은 못해봤는데 하나 먹고갑니다

2023-09-30 05:49 UTC, s9hn commented on app/src/main/java/woowacourse/paint/PaintPath.kt
> +class PaintPath(data: List<Pair<Path, Paint>> = emptyList()) {
객체로 관리하기 좋으네요

2023-09-30 05:49 UTC, s9hn commented on app/src/main/res/layout/activity_main.xml
> +            app:color="@{color}"
이거 어디서참조하고있는 속성인가요 width랑 app:color

2023-09-30 05:49 UTC, s9hn commented on app/src/main/java/woowacourse/paint/MainActivity.kt
> +            Color.RED, Color.argb(255, 255, 128, 0), Color.YELLOW, Color.GREEN, Color.BLUE
enum rr

2023-09-30 05:49 UTC, s9hn commented on app/src/main/java/woowacourse/paint/MainActivity.kt
> +        binding = DataBindingUtil.setContentView(this, R.layout.activity_main)
오호
DataBindingUtil 이용해서 바인딩 초기화해주는 이유가 있으십니까

2023-09-30 06:03 UTC, s9hn commented on app/src/main/java/woowacourse/paint/MainActivity.kt
> +            Color.RED, Color.argb(255, 255, 128, 0), Color.YELLOW, Color.GREEN, Color.BLUE
컬러는 도메인인가요?

2023-09-30 06:17 UTC, DYGames commented on app/src/main/java/woowacourse/paint/MainActivity.kt
> +            Color.RED, Color.argb(255, 255, 128, 0), Color.YELLOW, Color.GREEN, Color.BLUE
색은 이넘으로 구별해야 할 만한 정보가 아니라고 생각합니다.
런타임에도 색 정보를 가변적으로 가감을 할 수있어야 하지 않을까요

2023-09-30 06:19 UTC, DYGames commented on app/src/main/res/layout/activity_main.xml
> +            app:color="@{color}"
커스텀뷰에 setColor()

2023-09-30 06:19 UTC, DYGames commented on app/src/main/java/woowacourse/paint/PaintPath.kt
> +class PaintPath(data: List<Pair<Path, Paint>> = emptyList()) {
객체지향 체조원칙

2023-09-30 06:20 UTC, DYGames commented on app/src/main/java/woowacourse/paint/PaintView.kt
> +        paths.add(currentPath to currentPaint)
그럼 언제해주셨죠?

2023-09-30 06:20 UTC, DYGames commented on app/src/main/java/woowacourse/paint/PaintView.kt
> +            pointX, pointY
ㅋㅋ굿

2023-09-30 06:21 UTC, DYGames commented on app/src/main/res/layout/view_palette.xml
> +        android:background="?attr/selectableItemBackgroundBorderless"
기본이쥬 ㅋ

2023-10-01 17:48 UTC, DYGames commented on app/src/main/java/woowacourse/paint/MainActivity.kt
> +            Color.RED, Color.argb(255, 255, 128, 0), Color.YELLOW, Color.GREEN, Color.BLUE
비즈니스 로직에서 컬러 다룰 일 있으면 도메인에서 처리해야겠쥬

2023-10-01 17:49 UTC, DYGames commented on app/src/main/java/woowacourse/paint/MainActivity.kt
> +        binding = DataBindingUtil.setContentView(this, R.layout.activity_main)
그냥 했는데요..

2023-10-01 18:04 UTC, DYGames commented on app/src/main/java/woowacourse/paint/palette/PaletteAdapter.kt
> +class PaletteAdapter(private val data: List<Int>, private val onClickPalette: (Int) -> Unit) :
생각해봤는데 이 리사이클러뷰가 보여줘야할 최종적인 형태의 UI State들을 가진건 괜찮을 것 같은데요

2023-10-01 18:04 UTC, DYGames commented on app/src/main/java/woowacourse/paint/palette/PaletteAdapter.kt
> +        if (holder.binding.paletteImageButton.drawable != null) DrawableCompat.setTint(
아차차 수정했습니다

ViewHolder에 bind()를 만들었습니다.

2023-10-01 18:16 UTC, DYGames commented on app/src/main/java/woowacourse/paint/PaintView.kt
> +                startTouch(event.x, event.y)
몹시 타당.

startPaint()
drawDot()
movePaint()
cacheCurrentPaint()

으로 변경하였습니다.

2023-10-01 18:17 UTC, DYGames commented on app/src/main/java/woowacourse/paint/palette/PaletteViewHolder.kt
> +class PaletteViewHolder(val binding: ViewPaletteBinding, onClick: (Int) -> Unit) :
onClickPalette로 변경하였습니다.

2023-10-01 18:20 UTC, DYGames commented on app/src/main/java/woowacourse/paint/MainActivity.kt
> +            Color.RED, Color.argb(255, 255, 128, 0), Color.YELLOW, Color.GREEN, Color.BLUE
아키텍쳐 패턴의 관점에서 보면 모델의 역할이라고 생각이 들고, 따라서 분리했습니다~

2023-10-01 18:25 UTC, DYGames commented on app/src/main/java/woowacourse/paint/MainActivity.kt
> +            Color.RED, Color.argb(255, 255, 128, 0), Color.YELLOW, Color.GREEN, Color.BLUE
따라서 기존 안드로이드 의존이 있던 PaintPath 클래스도 POJO 객체로 표현할 수 있게 하고 매핑하는 계층을 두었습니다~

2023-10-02 17:47 UTC, DYGames commented
안녕하세요 ㅋ

리뷰 잘 봤습니다 ㅎ

리뷰 반영하면서 추가적으로 PaintPath, 선 자체를 POJO로 표현할 수 있는 도메인 계층을 두었고 따라서 매퍼랑 뷰모델도 두었습니다.

이게 뭐 아키텍쳐 패턴을 적용했다고 말하긴 뭐하긴 하네요.

감사합니다~

2023-10-02 18:49 UTC, DYGames commented
또 많이 한 고민.. 디깅룸하면서도 계속 했던 고민이지만.
커스텀 뷰는 그 자체로 캡슐화되어 있어야 한다고 생각합니다.
따라서 어느정도 내부에서 동작의 흐름이 전부 이루어져도 됩니다.

그래서 터치 이벤트가 발생했을 때 매번 ViewModel -> Domain으로 이동하는 것이 아닌 내부에서 적절히 처리하고 정말 ViewModel이 필요한 시점에서만 (사실 커스텀 뷰는 뷰모델을 모르지만) 이동시켜줬습니다.

산군은 어떻게 생각하세요? ㅋ

2023-10-03 08:51 UTC, s9hn approved these changes
> 또 많이 한 고민.. 디깅룸하면서도 계속 했던 고민이지만.
> 커스텀 뷰는 그 자체로 캡슐화되어 있어야 한다고 생각합니다.
> 따라서 어느정도 내부에서 동작의 흐름이 전부 이루어져도 됩니다.
> 
> 그래서 터치 이벤트가 발생했을 때 매번 ViewModel -> Domain으로 이동하는 것이 아닌 내부에서 적절히 처리하고 정말 ViewModel이 필요한 시점에서만 (사실 커스텀 뷰는 뷰모델을 모르지만) 이동시켜줬습니다.

저도 동의합니다! 
근데 커스텀뷰만 캡슐화를 위해 객체분리가 지양되는 것은 저는 반대입니다!
제가 생각하는 커스텀뷰는 xml에서 사용될 그냥 뷰 그 자체이기때문에, 관련 속성을 제외하고는 분리해주는 게 가독성이 더 좋지않나 생각합니다!

2023-10-03 08:51 UTC, s9hn commented on app/src/main/java/woowacourse/paint/domain/Points.kt
> +data class Points(val value: List<Point> = emptyList())
ㅋㅋ진짜 무친 객체들의 향연 잘봤습니다

2023-10-03 08:51 UTC, s9hn commented on app/src/main/java/woowacourse/paint/view/MainActivity.kt
> +        binding = DataBindingUtil.setContentView(this, R.layout.activity_main)
별차이는 없구요 그냥 id 아냐 모르냐 차이긴합니다. 구글 공식문서에선 뷰바인딩 선언방식을 권장하긴합니다

2023-10-03 08:51 UTC, s9hn commented on app/src/main/java/woowacourse/paint/view/MainActivity.kt
> +    }
init함수가 꼭 필요한가요?? 
color와 width의 초기값을 객체들이 처음부터 들고있을수는 없나요?
뷰모델.addLine을 굳이 해줘야하는 이유가 무엇인가요? 처음부터 들고있는건 이상한가요?

2023-10-03 08:51 UTC, s9hn commented on app/src/main/java/woowacourse/paint/view/PaintView.kt
> +    }
onAddLine할때마다 기존데이터+ 새로운데이터로 새롭게 RichPaths를 만들어줄수밖에 없나요?
데이터 클래스의 생성비용은 적지않은 편인데, 더 좋은 방법은 없을까요?

2023-10-03 08:51 UTC, s9hn commented on app/src/main/java/woowacourse/paint/view/PaintView.kt
> +                movePaint(event.x + EPSILON, event.y + EPSILON)
여기서 앱실론은 보정값인가요? 어떤경우에 필요한건가요?

2023-10-03 08:51 UTC, s9hn commented on app/src/main/java/woowacourse/paint/view/PaintView.kt
> +                return true
얘는 왜 따로 리턴 해주나요?

2023-10-03 08:51 UTC, s9hn commented on app/src/main/java/woowacourse/paint/view/model/RichPaths.kt
> +data class RichPaths(val data: List<Pair<Path, Paint>> = emptyList())
이름..좀 어려워요..

2023-10-03 08:51 UTC, s9hn commented on app/src/main/java/woowacourse/paint/view/model/mapper/PointsMapper.kt
> +            else listOf(Point(pathSegment.end.x, pathSegment.end.y))
Path와 관련된 메서드들 처음봤음다 .
덕분에 공부는 했는데 조큼 어렵군요
왜 else쪽에선 시작점에 대해선 Point를 받지않나요?
제가 이해가 좀 부족해서 그럴 수 있는데, 가능하면 간단하게 설명해주실수 있나용

2023-10-03 08:51 UTC, s9hn commented on app/src/main/java/woowacourse/paint/view/palette/PaletteAdapter.kt
> +class PaletteAdapter(private val data: List<Int>, private val onClickPalette: (Int) -> Unit) :
ㅋㅋ onClick에 대한 구체적인 네이밍도 좋지만
제가 의도한건 넘겨주는 인수에 대한 네이밍이였습니다

2023-10-03 08:51 UTC, s9hn commented on app/src/main/java/woowacourse/paint/view/palette/PaletteViewHolder.kt
> +class PaletteViewHolder(private val binding: ViewPaletteBinding, onClickPalette: (Int) -> Unit) :
```
onClickPalette:(color :Int) -> Unit
onClickPalette:(something: Int) -> Unit
```

다른 개발자가 보았을 때 인수로 넘겨주는 Int, adapterPosition이 무엇인지에 대한 명시요!

2023-10-03 08:57 UTC, merged

2023-10-03 09:01 UTC, DYGames commented on app/src/main/java/woowacourse/paint/view/MainActivity.kt
> +    }
color와 width의 초기값 -> 커스텀 뷰의 역할이 아닌 커스텀 뷰를 사용하는 곳 (Activity)에서 지정해줘야 할 것
뷰모델의 addLine 하는 람다를 이곳에서 안해주면 어디서 해주죠?

2023-10-03 09:03 UTC, DYGames commented on app/src/main/java/woowacourse/paint/view/PaintView.kt
> +    }
네 트레이드오프입니다 함수형으로 짰어요

2023-10-03 09:04 UTC, DYGames commented on app/src/main/java/woowacourse/paint/view/PaintView.kt
> +                movePaint(event.x + EPSILON, event.y + EPSILON)
Path에 저장된 좌표값들을 가져오기 위해 Path.flatten() 을 호출 했을때,
점만 찍혀있으면 가져와지지 않습니다. 그래서 점만 찍혀있는 상황을 앱실론으로 보정값을 줘서 선으로 인식하게 하고 POJO로 저장 할 수 있도록 했습니다.

2023-10-03 09:04 UTC, DYGames commented on app/src/main/java/woowacourse/paint/view/PaintView.kt
> +                return true
invalidate 안하려구요

2023-10-03 09:04 UTC, DYGames commented on app/src/main/java/woowacourse/paint/view/model/RichPaths.kt
> +data class RichPaths(val data: List<Pair<Path, Paint>> = emptyList())
RichText라는게 있는데 서식 적용된 텍스트라는 뜻입니다.
그걸 Paint있는 Path라고 해서 넣었는데 어렵긴해요 ㅋ

2023-10-03 09:07 UTC, DYGames commented on app/src/main/java/woowacourse/paint/view/model/mapper/PointsMapper.kt
> +            else listOf(Point(pathSegment.end.x, pathSegment.end.y))
flatten()을 해서 Path의 모든 PathSegment을 가져오는데, PathSegment에는 한 직선에 대해 시작과 끝점이 있습니다
그래서 우리는 첫 직선에 대해서만 시작점과 끝점을 저장하고, 남은 모든 직선에 대해서는 끝점을 저장해서 Path의 모든 점을 가져올 수 있습니다

2023-10-03 09:08 UTC, DYGames commented on app/src/main/java/woowacourse/paint/view/palette/PaletteAdapter.kt
> +class PaletteAdapter(private val data: List<Int>, private val onClickPalette: (Int) -> Unit) :
좋긴 한데 전 너무 길어지고 그렇게 할거면 interface 만드는게 좋을 것 같아요.

2023-10-03 09:09 UTC, DYGames commented
> 저도 동의합니다!
근데 커스텀뷰만 캡슐화를 위해 객체분리가 지양되는 것은 저는 반대입니다!
제가 생각하는 커스텀뷰는 xml에서 사용될 그냥 뷰 그 자체이기때문에, 관련 속성을 제외하고는 분리해주는 게 가독성이 더 좋지않나 생각합니다!

그래서 비대해지는 경우 커스텀 뷰 자체를 하나의 모듈 or 라이브러리라고 보고 그 자체에 대한 앱과 분리된 아키텍쳐 패턴을 적용해서 구현하는게 어떨까 싶습니다.

2023-10-03 09:16 UTC, s9hn commented on app/src/main/java/woowacourse/paint/view/PaintView.kt
> +                return true
오 확실히 ㅇㅈ

2023-10-03 09:18 UTC, s9hn commented on app/src/main/java/woowacourse/paint/view/model/mapper/PointsMapper.kt
> +            else listOf(Point(pathSegment.end.x, pathSegment.end.y))
오.. 이해했음다 감사

2023-10-03 09:19 UTC, s9hn commented
오 그것도 괜찮네요 미션하느라 고생했음다! 다음 미션에서 또 뵙겠습니다