[핑구] 뷰 챌린지 미션 1단계 제출합니다.
woowacourse/android-paint pull request #20
Opened 2023-09-30 16:58 UTC by pingu244

안녕하세요 써니!!
리뷰어로 만나서 반가워요😊
그림판 미션 리뷰 잘 부탁드립니다~!

## 실행화면
<image src="https://github.com/woowacourse/android-paint/assets/69796976/f38dc465-2ed8-4a5d-a256-75a291b3b300" width=360>

## 코드 설명
### BoardView
그림을 그릴 수 있는 Custom View 입니다.
이전에 그린 path들을 어떻게 기록할 수 있을까 하다가 bitmap에 저장하는 방식을 사용해보았습니다.
storedCanvas에 bitmap을 지정해주고 storedCanvas에 path를 그려주면서 bitmap에 저장하게 해주었습니다.
더 좋은 방법이 있다면 추천 부탁드립니다!

### ColorPalette
색상들을 정의하는 enum class 입니다.

### PaintBinding
MVVM 구조로 만들며 binding Adapter를 모아놓은 곳 입니다.

2023-10-02 09:57 UTC, inseonyun requested changes
안녕하세요 핑구!! 
제 슬랙이 어느 순간부터 울리질 않아서 6시에 핑구는 왜 미션을 안 내지 하다가 리뷰 요청 온 걸 확인했네요,,,
Bitmap을 이용한 이번 미션 잘 봤습니다! 어려웠을 거 같은데 잘 해내셨네요!
몇몇 궁금한 점과 개선하면 좋을 법한 내용들 코멘트로 남겼습니다!

2023-10-02 09:57 UTC, inseonyun commented on app/src/main/java/woowacourse/paint/BoardView.kt
> +        paint.strokeCap = Paint.Cap.ROUND
Paint의 Cap 뿐만 아니라 Join 값도 ROUND로 주면 좀 더 부드러운 곡선을 그릴 수 있습니다
[Android Docs](https://developer.android.com/reference/android/graphics/Paint.Join)

2023-10-02 09:57 UTC, inseonyun commented on app/src/main/java/woowacourse/paint/BoardView.kt
> +        bitmap.eraseColor(Color.TRANSPARENT)
bitmap의 eraseColor는 해당 Color를 지우는게 아닌 해당 컬러로 채운다는 의미였군요 ㄷㄷ;;
함수명 왜이럼...

2023-10-02 09:57 UTC, inseonyun commented on app/src/main/java/woowacourse/paint/BoardView.kt
> +        bitmap = Bitmap.createBitmap(w, h, Bitmap.Config.ARGB_8888)
Bitmap의 ARGB_8888가 무슨 역할을 하는지 호기심에 docs를 슥 봤는데 투명 값을 사용하기 위함인가용?

2023-10-02 09:57 UTC, inseonyun commented on app/src/main/java/woowacourse/paint/BoardView.kt
> +        storedCanvas = Canvas(bitmap)
Bitmap으로 관리하고 이를 캔버스에 그리는 행위는 정말 좋은 방법 같아요!
근데, onDraw에서 제공되는 canvas와 핑구가 따로 관리하게 되는 storedCanvas 각각 따로 존재해야하나? 라는 생각을 갖게 되네요,,,
> 어떻게든 해결법을 찾고자 고쳐보려했는데 잘 안 되네요 ;(

2023-10-02 09:57 UTC, inseonyun commented on app/src/main/java/woowacourse/paint/PaintBinding.kt
> +    this.valueTo = MAX_WIDTH_VALUE
```suggestion
activity_main.xml
<com.google.android.material.slider.RangeSlider
    ...
    android:valueFrom="0.0"
    android:valueTo="100.0" />
```
요런식으로 xml에서 바로 설정할 수 있습니당

2023-10-02 09:57 UTC, inseonyun commented on app/src/main/java/woowacourse/paint/PaintBinding.kt
> +}
바인딩 어댑터는 전역에서 접근할 수 있는만큼 신중하게 작성해야 한다고 생각합니다.
MainViewModel을 받는 것보다 함수를 받도록 해서 하면 더 좋을 거 같아요!

아 그리고 리스너 등록은 저도 배운건데 아래와 같은 방법으로도 작성 가능합니다!
```suggestion
this.addOnChangeListener { _, value, _ ->
    viewModel.changeWidth(value)
}
```

2023-10-02 18:35 UTC, DYGames commented on app/src/main/java/woowacourse/paint/BoardView.kt
> +        storedCanvas = Canvas(bitmap)
오 제가 Bitmap으로 관리하는거 포기한 포인트

2023-10-03 05:22 UTC, pingu244 commented on app/src/main/java/woowacourse/paint/BoardView.kt
> +        bitmap = Bitmap.createBitmap(w, h, Bitmap.Config.ARGB_8888)
네 맞습니다~!
Bitmap.Config.ARGB_8888 은 비트맵의 픽셀 포맷(색상과 투명도)을 지정하는 매개변수인데요,
Bitmap.Config.ARGB_8888 은 [알파 채널(투명도), 빨강(R), 녹색(G), 파랑(B)]과 같이 총 4개의 채널을 가지고 각 채널은 8비트로 표현되어 0-255의 값을 가지게 됩니다!

2023-10-03 05:42 UTC, pingu244 commented on app/src/main/java/woowacourse/paint/BoardView.kt
> +        storedCanvas = Canvas(bitmap)
저는 Bitmap은 이미지 데이터 자체를 나타내는 것이고, Canvas는 그림을 그리는 작업을 수행하는 도구로 이해해서 Canvas를 사용하여 Bitmap에 그림을 추가하고 조작한다고 봤습니다.
onDraw에서 제공하는 canvas는 화면에 그림 그리는 도구이고, 제가 만든 storedCanvas는 지금 그린 획을 bitmap에 저장하게 해주는 도구이니 따로 존재할 수 밖에 없지 않을까요..?

2023-10-03 08:03 UTC, pingu244 commented on app/src/main/java/woowacourse/paint/PaintBinding.kt
> +}
저도 써니의 의견에 아주아주 동의합니다! 리뷰주신 것처럼 함수를 받도록 수정하려고 하다가 bindingAdapter로 인자가 필요한 함수를 파라미터로 받을 수 없다는 사실을 알게되었습니다. 굉장한 삽질하다가 interface로 해결했습니다👍[참고 링크](https://stackoverflow.com/questions/55578601/typed-parameter-in-a-lambda-not-recognized-by-the-data-binder-when-using-binding)

2023-10-03 12:35 UTC, inseonyun requested changes
피드백 반영 고생 많으셨어요!
어떤 피드백을 드려야할 지 고민을 많이 하다가 궁금한 점과 코드 중간 중간 놓친 거 같은 부분 남겨드렸어요!
제가 잘못 남겨드린 피드백이나 진행이 어려운 점이 있다면 DM 부탁드려요 !

2023-10-03 12:35 UTC, inseonyun commented on app/src/main/java/woowacourse/paint/BoardView.kt
> +        paint.color = ContextCompat.getColor(context, colorPalette.color)
함수가 간단해졌네요 👍

2023-10-03 12:35 UTC, inseonyun commented on app/src/main/java/woowacourse/paint/BoardView.kt
> +    }
함수 분리 굳 👍

2023-10-03 12:35 UTC, inseonyun commented on app/src/main/java/woowacourse/paint/ColorPalette.kt
> +enum class ColorPalette(@ColorRes val color: Int) {
@ColorRes 어노테이션 활용 👍

2023-10-03 12:35 UTC, inseonyun commented on app/src/main/java/woowacourse/paint/PaintBinding.kt
> +}
음,,,핑구가 어떤 방식으로 구현을 시도했었나요? 올려주신 링크의 방법대로 하셨나요?
저는 핑구가 해결한 방법과 똑같? 유사한 방법으로 생각했었습니다!
아래는 제가 주로 사용하는 방법입니다.

```xml
// activity_main.xml
        ...
        <variable
            name="listener"
            type="kotlin.jvm.functions.Function1" />

        <com.google.android.material.slider.Slider
            ...
            app:setupSlider="@{(value) -> listener.invoke(value)}" />
```

```kotlin
// PaintBinding.kt
@BindingAdapter("app:setupSlider")
fun Slider.setupSlider(onSlideListener: (Float) -> Unit) {
    this.addOnChangeListener { _, value, _ ->
        onSlideListener(value)
    }
}
```

```kotlin
// MainActivity.kt
...
binding.listener = mainViewModel::changeWidth
```

결론은 핑구가 구현해 내신 방법과 거의 동일한 방식입니다! 
삽질이 조금 있었다니 죄송하네용,,,
남겨드리는 코멘트가 이해가 안 가거나 이상하다고 생각되면 DM 주세요 ㅋㅋ..제가 말을 잘 몬해서,,

2023-10-03 12:35 UTC, inseonyun commented on app/src/main/res/layout/activity_main.xml
> +            app:layout_constraintTop_toBottomOf="@id/range_slider_width" />
팔레트의 컬러들이 점점 더 늘어난다면 MainActivity의 View가 무한정 늘어날 거 같아요!
Recyclerview로 재활용을 해도 좋을 것 같단 생각이 들지만!!
다음 미션이 공개되면 그 때 생각해보시죠?

2023-10-03 12:35 UTC, inseonyun commented on app/src/main/res/layout/activity_main.xml
> +            android:background="#3F51B5"
colors.xml에 blue의 색상이 있는데 여기선 그대로 쓰고 있어요!

2023-10-03 12:35 UTC, inseonyun commented on app/src/main/java/woowacourse/paint/BoardView.kt
> +        storedCanvas = Canvas(bitmap)
음,,,지금 구조에서는 bitmap에 그림을 그리기 위해선 Canvas를 필요로 하고 이로 인해  따로 존재할 수밖에 없을거 같아요!
그림의 양이 많아지면 bitmap 한 번만 불러와서 그려주면 되기 때문에 정말 편하다고 생각되는데요!
한 가지 궁금한 확장은 그린 그림을 되돌리기 위해서는 어떻게 구현해야 하나요?
> 다음 미션이 공개되면 그 때 생각해봐도 좋을 거 같아요!

2023-10-04 04:52 UTC, pingu244 commented on app/src/main/java/woowacourse/paint/PaintBinding.kt
> +}
아뇨아뇨! 써니는 좋은 리뷰 주셨는데 그냥 제 실력이 부족해서 그랬습니다ㅋㅋㅋ 
바인딩어댑터에 함수를 건네주는 것 자체가 처음이었거든요..ㅎㅎ
써니의 방식도 좋은 것 같아요! 기록해두고 다음에 두고두고 써먹겠습니다 감사합니다😉

2023-10-04 04:53 UTC, pingu244 commented on app/src/main/res/layout/activity_main.xml
> +            android:background="#3F51B5"
오 이걸 발견해주시다니! 정말 꼼꼼하게 봐주셨군요 감사합니다!

2023-10-04 04:58 UTC, pingu244 commented on app/src/main/java/woowacourse/paint/BoardView.kt
> +        storedCanvas = Canvas(bitmap)
이 부분에 대해서 계속 고민해봤는데 지금 당장 떠오르는 방법은 없네요..ㅜ 더 생각해보고 다음 미션 구현해보도록 하겠습니다

2023-10-04 08:02 UTC, pingu244 commented
이번에 2단계 미션 확인하고 전체적으로 좀 많이 바꾸게 되었습니다..! (죄송해요 써니😂)
일단 색상 선택 커스텀 뷰와 굵기 선택 커스텀 뷰를 만들었습니다. 
메인 화면 하단에 색상선택 버튼과 굵기 선택 버튼을 두고 각각의 버튼을 눌렀을 때, 버튼 위쪽에 만들어 둔 LinearLayout에 커스텀 뷰를 동적 생성하여 add하게 했습니다.
이해 안되시는 부분이나 궁금한 부분이 있으면 언제든 DM주세요!

2023-10-04 09:07 UTC, inseonyun approved these changes
피드백 반영 및 1단계 미션 고생 많으셨어요!
마지막 반영에서 변경점이 좀 있긴 했지만 핑구가 코드를 잘 작성해준 덕에 딱히 피드백을 드릴만한 내용이 존재하지 않았던 거 같아요!
추가로 구현하신 ImageButton과 관련된 뷰 제거 및 생성 기능이 조금 비효율적이라고 생각되어 코멘트 남겼습니다!
고민 해보시고 다음 단계에서 반영 혹은 의견 공유 부탁드릴게요 !

2023-10-04 09:07 UTC, inseonyun commented on app/src/main/java/woowacourse/paint/MainActivity.kt
> +    }
뷰를 감췄다가 보여줬다가 하기 위해 LiveData로 event를 두고 이 이벤트가 불렸을 때 view를 그리도록 하는 구조 인 거 같아요!
아마 그림을 그리는 영역에 불필요하게 계속 차지하는 팔레트, 굵기 창 때문에 가렸다가 보여지게 하고 싶었을 거 같아요? 맞나요? 하하...
지금 구조에서 isClicked는 한 번 클릭을 하고 나면 항상 true가 되어있기 때문에 초기 클릭이 아닌 이후에는 계속 isClicked 조건문 내부 로직을 수행해서 불필요한 뷰 제거, 생성을 계속 할 거 같아요!
값이 변동 되었을 때만 Observer에게 event가 가게 하는 방법, 혹은 똑같은 뷰가 이미 존재한다면 그 뷰의 visible을 gone / visible 하게 하는게 좀 더 나을 거 같단 생각이 듭니다!

2023-10-04 09:07 UTC, merged