[아크] 뷰 챌린지 미션 1단계 제출합니다.
woowacourse/android-paint pull request #21
Opened 2023-09-30 18:53 UTC by re4rk

안녕하세요 수달! 뷰 챌린지 미션동안 잘부탁드립니다!

customView에 public으로 변수를 놔둬서 setter를 통해서  색상과 굵기가 변경 시 화면 또한 자동으로 바뀌도록 수정을 하였습니다!
추가로 색상 선택시 더욱 다양한 색상을 선택할 수 있게 Recycler로 구현을 하였습니다!

미션 수행에 추가한 기능은 다음과 같습니다! (추가한 기능은 사진과 번호를 맞춰서 설명했습니다!)
1. 현재 브러쉬의 크기와 색상을 확인할 수 있습니다.
2. 되돌리기(Undo) 기능을 추가했습니다.
3. 취소(Redo) 기능을 추가했습니다.
4. 초기화(Clear) 기능을 추가했습니다.

<img width="314" alt="스크린샷 2023-10-01 오전 2 34 56" src="https://github.com/woowacourse/android-paint/assets/37167652/d7c54654-b11a-4281-8efd-6ef3c45110f3">

2023-10-01 11:30 UTC, otter66 requested changes
현재 색상 및 굵기 확인 기능 재치있는 것 같아요!!! :)
코멘트 남겼습니다!! 화이팅!!!

2023-10-01 11:30 UTC, otter66 commented on app/build.gradle.kts
필요한 설정까지 하나하나 커밋을 상세하게 나눠주신 것 같아요! 
커밋이 잘게 잘 나누어져 있어서 아크의 흐름을 따라가며 이해가 조금 더 수월했던 것 같습니다!
이렇게 하면서 생산력도 누구보다 잘 챙기는 아크 멋있습니다!!

2023-10-01 11:30 UTC, otter66 commented on app/src/test/java/woowacourse/paint/customVeiw/PaintingPaperTest.kt
추가될 예정인가요? 🤔

2023-10-01 11:30 UTC, otter66 commented on app/src/main/res/layout/activity_main.xml
> +                    android:layout_weight="1" />
"취소"가 가 무엇인지 이해하기 어려울 수 있을 것 같아요!
네이밍을 수정해보거나 되돌리기를 누른 후에 취소가 활성화되도록 해보는건 어떨까요?
(참고 : 갤럭시 노트 앱, 각각 undo, redo 입니다!)
![KakaoTalk_Photo_2023-10-01-18-24-06](https://github.com/woowacourse/android-paint/assets/69189793/2b3bc0af-3dce-4125-a3b4-035754d95e90)
안그래도 많이 하는 아크에게 미션을 더 주는 악덕...???
이미 미션 요구사항은 모두 만족했으니 반영 여부는 아크의 자유!!

2023-10-01 11:30 UTC, otter66 commented on app/src/main/java/woowacourse/paint/customVeiw/PaintingPaper.kt
> +        }
클릭했을 때 점이 찍히지 않도록 한 것은 의도한걸까요?

2023-10-01 11:30 UTC, otter66 commented on app/src/main/java/woowacourse/paint/customVeiw/PaintingPaper.kt
> +        isFocusableInTouchMode = true
어떤 역할을 하는 코드인가요?? 궁금합니다!

2023-10-01 11:30 UTC, otter66 commented on app/src/main/java/woowacourse/paint/model/Brush.kt
> +    }
calculateDistance라고 하면, 어떤 것과의 거리를 계산하는지 명확하지 않은 것 같아요!

그리고 제가 잘 이해가 안되어서 조금만 추가로 설명해주실 수 있을까요? 
움직일 수 있는 위치인지 판단하는데 마지막 점과의 거리가 필요한 이유를 잘 모르겠습니다.

2023-10-01 11:30 UTC, otter66 commented on app/src/main/java/woowacourse/paint/ui/MainActivity.kt
> +            binding.paintingPaper.brushSize = value * 100
소수로 표시하고, 사용할 때 100을 곱하는 것보다는 표시할 때 사용할 때 모두 정수로 표현되는게 더 좋지 않을까요!??

2023-10-01 11:30 UTC, otter66 commented on app/src/main/java/woowacourse/paint/customVeiw/PaintingPaper.kt
현재 선을 왔다갔다 그리면 삐죽삐죽 튀어나옵니다! (브러쉬를 굵게 하고, 빠르게 움직일 때 확인이 편합니다!)
아마 이 부분은 많이들 지나쳤을 것 같은데, 해결해보면 좋을 것 같아요!

2023-10-01 11:44 UTC, otter66 commented on app/src/main/java/woowacourse/paint/ui/ColorAdapter.kt
> +        )
추가로 하나 더 남길게요! 미션 요구사항에는 주황색도 있었는데요! 
`android.graphics.Color`에 기본적으로 지정되지 않은 주황색으로 표현하기 위해 다른 방법이 필요할겁니다!

2023-10-04 07:43 UTC, re4rk commented on app/src/main/res/layout/activity_main.xml
> +                    android:layout_weight="1" />
적용해봤는데 이쁘네요!

2023-10-04 07:43 UTC, re4rk commented on app/src/main/java/woowacourse/paint/customVeiw/PaintingPaper.kt
> +        }
변경했습니다!

2023-10-04 07:45 UTC, re4rk commented on app/src/main/java/woowacourse/paint/model/Brush.kt
> +    }
마지막 점과 거리가 가까우면 성능 최적화를 위해서 점이 찍히지 않도록 변경하였습니다. 
해당 코드는 x,y좌표를 Point로 묶으면서 구조 변경하였습니다!

2023-10-04 07:45 UTC, re4rk commented on app/src/main/java/woowacourse/paint/ui/MainActivity.kt
> +            binding.paintingPaper.brushSize = value * 100
xml을 통해서 해당 방법대로 동작하도록 변경하였습니다!

2023-10-04 07:46 UTC, re4rk commented on app/src/main/java/woowacourse/paint/customVeiw/PaintingPaper.kt
Paint가 생각보다 많은 기능을 하고 있군요 실사용 리뷰 감사합니다!

2023-10-04 08:01 UTC, re4rk commented on app/src/main/java/woowacourse/paint/customVeiw/PaintingPaper.kt
> +        isFocusableInTouchMode = true
관용적으로 사용하다가 코멘트를 보고 찾아보니 저한태는 필요하지 않는 기능같아서 제거하였습니다!
focus는 사용자와 상호작용할수 있는 상태를 말하고 isFocusable, isFocusableInTouchMode는 focus 상태가 될 수 있음을 나타냅니다.
isFocusable과 isFocusableInTouchMode의 차이점은 isFocusble은 keyBoardMode까지 가능하다는 것입니다.

2023-10-04 08:01 UTC, re4rk commented
리뷰 반영하면서 지우게 모드도 추가하였습니다. 이 점도 확인부탁드립니다! [cf7c115](https://github.com/woowacourse/android-paint/pull/21/commits/cf7c11572c29793fef8e55f37f48023bbe7eed16)

2023-10-04 11:32 UTC, otter66 commented on app/src/main/java/woowacourse/paint/customVeiw/PaintingPaper.kt
> +            pathEffect = CornerPathEffect(100F)
상수화 ! 
다른 곳들도 !

2023-10-04 15:41 UTC, otter66 approved these changes
아크 수고 많으셨습니다!!
지우개 모드도 추가해 주셨는데, 제가 아직 이 부분을 구현하지 않아서 지금은 리뷰를 잘 남기지 못할 것 같아요. 다음 step에서 다루겠습니다!
아마 강의자료를 보며 달라지는 부분도 많을거라 생각해요!
코멘트를 조금 더 남겼으니 확인해 보시고, 다음 미션 제출 때 다시 뵙겠습니다!🫡

2023-10-04 15:41 UTC, otter66 commented on app/src/main/java/woowacourse/paint/customVeiw/PaintingPaper.kt
> +            pathEffect = CornerPathEffect(100F)
상수화!
다른 곳들도!!!
저의 경우에는 관련 객체의 companion object에서 defaultXXX를 만들어 사용합니다!
brushSize라면 Brush의 companion object에서 default size 등으로요!

2023-10-04 15:41 UTC, otter66 commented on app/src/main/java/woowacourse/paint/customVeiw/PaintingPaper.kt
> +    }
이 부분은 취향차이일 것 같기는 하네요.

저는 `brushes.redo { updatePaper() }`처럼 사용하는 것을 선호합니다.
리플렉션을 사용하게 되면 최적화가 되지 않는 등의 문제가 있기도 하고, 인자로 어떤 것이 있는지 확인도 어렵습니다. 또한, 안드로이드에서는 이 방식이 더 익숙하다고 생각해요. list.map, setOnClickListener와 같은 것도 주로 해당 방식을 사용하기 때문이죠.

선택은 아크의 자유! 이지만, 아크는 리플렉션을 사용하는 이유가 있을까요?? 궁금합니다!

2023-10-04 15:41 UTC, otter66 commented on app/src/main/res/drawable/ic_baseline_redo_32.xml
아이콘들 반영해주셨군요 😆
전보다 더 직관적인 뷰가 된 것 같아요!
isEnabled까지 꼼꼼한 처리! 한 수 배워갑니다!

2023-10-04 15:41 UTC, otter66 commented on app/src/main/res/layout/activity_main.xml
그러고보니 View의 depth가 조금 깊은 것 같아요.
개선해볼 수는 없을까요🤔?

2023-10-04 15:42 UTC, merged

2023-10-10 11:25 UTC, re4rk commented on app/src/main/res/layout/activity_main.xml
View의 depth가 깊다는 것에 잘 공감이 가지 않습니다! 
구조상 constroller를 맡은 객체가 최소한으로 vertical과 horizontal 각각 한번씩 사용하고 있습니다!
depth가 낮을 때에 성능 차이는 [Constraint vs Linear 블로그](https://medium.com/android-news/constraint-layout-performance-870e5f238100) 에서 보다시피 오히려 Linear가 좋은 것을 볼 수 있습니다!
그래서 당장 RecyclerView와 같이 depth가 깊어진다면 Constraint가 도움이 된다고 생각하지만 단순한 뷰에서는 Linear를 적용하는 것이 낫지 않을까 생각하고 있습니다!
수달은 이에 대해서 어떻게 생각하시나요??

2023-10-10 11:25 UTC, re4rk commented on app/src/main/java/woowacourse/paint/customVeiw/PaintingPaper.kt
> +    }
성능상 더 좋을 것 같다는 것과 인자 확인 또한 공감갑니다! 반영하겠습니다!

2023-10-10 11:42 UTC, re4rk commented on app/src/main/java/woowacourse/paint/customVeiw/PaintingPaper.kt
> +            pathEffect = CornerPathEffect(100F)
해당 코멘트가 잘 와닿지 않습니다!
코드 상에서 상수만 바라보았을 때에 역할을 알지 못했을 때 `THRESHOLD`와 `ADJSTMENT`와 같이 무슨 역할을 하는지 알면 좋을 것같다고 생각합니다!
하지만 해당 상수들은 객체를 초기화 하고 코드 상으로 바라보았을 때에 이해하는 것에 어려움이 없다고 생각합니다!
오히려 defaultXXX와 같이 작성하면 코드도 길어지고 무슨 값이 들어오는지 코드 리딩때에 위아래로 이동하면서 봐야하는 불편함이 있습니다!
만약에 defaultXXX로 지정이 필요한 상황이 있다면 Configuration을 정의하고 중앙 관리를 한다면 필요하다고 생각합니다!

수달이 같은 클래스 내에서 defaultXXX으로 작성하신 이유는 무엇인가요???

2023-10-11 02:12 UTC, otter66 commented on app/src/main/java/woowacourse/paint/customVeiw/PaintingPaper.kt
> +            pathEffect = CornerPathEffect(100F)
첫째로는 가독성에 좋다고 생각합니다. 100F라고 할 경우 어떤 이유로 100을 썼는지, 100이 왜 쓰인 것인지 모호할 수 있다고 생각합니다.
두번째로는 값이 변경되었을 때 해당 값을 모두 적용시키기 위해 일일이 파일을 찾아봐야하는 단점을 보완할 수 있다고 생각합니다.

저는 코드가 조금 더 길어지더라도 명확하게 이해할 수 있도록 변수로 묶거나 축약형을 쓰지 않는 방식을 조금 더 선호하기 때문에 아크와 의견이 다를 수도 있을 것 같네요!

2023-10-11 02:25 UTC, otter66 commented on app/src/main/res/layout/activity_main.xml
습관적으로 depth를 줄여야한다고 생각해서 얘기했던 것이었습니다!
다시 보니 당시의 요구사항과 구현에서는 해당 depth가 최선이라는 생각이 드네요🤔.
저도 덕분에 다시한번 더 xml에 대해 생각해볼 수 있는 기회가 되었습니다! 감사합니다!

추가로, step3 요구사항을 위해 Constraint로 변경이 필요할 수는 있겠네요!