[수달] 1단계 자유 곡선 미션 제출합니다.
woowacourse/android-paint pull request #24
Opened 2023-10-02 05:31 UTC by otter66

안녕하세요! 코건! 리뷰 잘 부탁드립니다!!!
코건의 리뷰 무더기 기다리고 있겠습니다! 🤗🤗🤗   

또, 제가 신나서 앱 로고를 변경하였는데요! 이 때문에 파일이 조금 많습니다! 
해당 부분을 제거한 커밋들입니다!

<image src="https://github.com/woowacourse/android-paint/assets/69189793/604d155f-fb8e-4e4f-9994-7dfc61e05788" width=360>

2023-10-02 05:36 UTC, otter66 commented on app/src/main/java/woowacourse/paint/MainActivity.kt
> +        binding.paintView.pen = selectedPen
penToolView의 pen과 paintView의 pen이 같은 주소를 바라보게 하는게 과연 좋은 방법일지 의문입니다 리뷰어 코건님...
마음같아서는 OtterPaintView를 만들어 Controller의 역할을 하게 하고 싶으나 이렇게 할 경우에도 고민이 있습니다.
가장 좋은 방법은 터치 이벤트가 발생할 때마다 외부에서 펜을 받아오게 하여 사용하는 방법이라고 생각하나 이것을 구현할 수 있을지 모르겠습니다.

2023-10-02 06:07 UTC, DYGames requested changes
수달 꼼꼼하게 고민 많이 하신 흔적이 돋보여서 좋았습니다 👍 

코멘트 남겼으니 확인하고 선택해서 반영해주세요~

화이팅 💯

2023-10-02 06:07 UTC, DYGames commented on app/build.gradle.kts
> +    id("kotlin-kapt")
kapt는 왜 추가된걸까요 ?

2023-10-02 06:07 UTC, DYGames commented on app/build.gradle.kts
> +                "proguard-rules.pro",
트레일링 콤마..

2023-10-02 06:07 UTC, DYGames commented on app/src/main/AndroidManifest.xml
> +        android:icon="@mipmap/ic_app_logo"
로고 추가 신선합니다~

2023-10-02 06:07 UTC, DYGames commented on app/src/main/java/woowacourse/paint/BindingAdapters.kt
> +fun PenToolView.setVisibility(value: Boolean) {
확장 함수로 BindingAdpater 좋습니다~

다만 파일명을 좀 더 세부적으로 명시하는건 어떨까요?

2023-10-02 06:07 UTC, DYGames commented on app/src/main/java/woowacourse/paint/BindingAdapters.kt
> +fun PenToolView.setVisibility(value: Boolean) {
파라미터도 value가 아닌 isVisible 정도로 바꾸면 좋겠네요.

2023-10-02 06:07 UTC, DYGames commented on app/src/main/java/woowacourse/paint/MainActivity.kt
> +        binding.paintView.pen = selectedPen
xml에서 양방향 데이터 바인딩으로 대체할 수 있지 않을까요?

2023-10-02 06:07 UTC, DYGames commented on app/src/main/java/woowacourse/paint/MainViewModel.kt
> +        _penToolVisibility.value = _penToolVisibility.value!!.not()
null assert 대신 다른 방법을 생각 해 봅시다!

2023-10-02 06:07 UTC, DYGames commented on app/src/main/java/woowacourse/paint/MainViewModel.kt
> +    val penToolVisibility: LiveData<Boolean> = _penToolVisibility
고민 해볼 문제인데, 펜 툴의 표시 여부가 ViewModel의 관심사일까요? View 내에서 해결 할 수 있지 않을까요? (정답은 없습니다)

2023-10-02 06:07 UTC, DYGames commented on app/src/main/java/woowacourse/paint/PaintView.kt
> +        return true
ACTION_DOWN과 ACTION_MOVE가 아닌 상황에서도 invalidate를 하지 않나요?

2023-10-02 06:07 UTC, DYGames commented on app/src/main/java/woowacourse/paint/PaintView.kt
> +        lines.last().path.moveTo(event.x, event.y)
last()를 하는 비용이 있을텐데 addLine()에서 더해준 Line을 return해주고 그 참조로 moveTo하는건 어떤가요?

2023-10-02 06:07 UTC, DYGames commented on app/src/main/java/woowacourse/paint/PenToolView.kt
> +        ViewPenToolBinding.inflate(LayoutInflater.from(context), this, true)
커스텀뷰 인스턴스가 생성된 시점에서 inflate 또해주면 뷰 인스턴스가 두개 생기는건가요?

2023-10-02 06:07 UTC, DYGames commented on app/src/main/java/woowacourse/paint/PenToolView.kt
> +            container.addView(view)
indent depth가 깊어용

2023-10-02 06:07 UTC, DYGames commented on app/src/main/java/woowacourse/paint/PenToolView.kt
> +class PenToolView(
이건 제 개인적인 생각인데, PenToolView라는 뷰가 커스텀 뷰로 만들기 적합할까요? 안드로이드 기본 뷰로도 충분히 표현 할 수 있는 뷰를 커스텀뷰로 만들지 않았나 생각해봅니다.

2023-10-02 06:07 UTC, DYGames commented on app/src/main/java/woowacourse/paint/model/pen/Pen.kt
> +abstract class Pen(
수달의 클래스들... 깊은 고민의 흔적과 객체지향에 대한 이해가 돋보이네요 👍

2023-10-02 06:07 UTC, DYGames commented on app/src/main/res/layout/activity_main.xml
> +            android:contentDescription="펜 선택 버튼"
contentDescription 👍

2023-10-02 06:07 UTC, DYGames commented on app/src/main/res/layout/activity_main.xml
> +            android:visibility="gone"
penToolVisibility와 android:visibility가 같이있어서 혼동이 와요.

2023-10-02 06:07 UTC, DYGames commented on app/src/main/res/values/strings.xml
> +    <string name="app_name">🦦 수달 그림판 🦦</string>
앱 이름에 이모지가 와도 괜찮을까요? (진짜 모름)

2023-10-03 06:48 UTC, otter66 commented on app/build.gradle.kts
> +                "proguard-rules.pro",
무려 공식문서 컨벤션! 포기하시죠!
https://kotlinlang.org/docs/coding-conventions.html#trailing-commas !

2023-10-03 07:27 UTC, otter66 commented on app/build.gradle.kts
> +    id("kotlin-kapt")
binding adapter 어노테이션을 사용하기 위해 추가되었습니다!
https://kotlinlang.org/docs/kapt.html#using-in-gradle

2023-10-03 07:41 UTC, otter66 commented on app/build.gradle.kts
> +    id("kotlin-kapt")
binding adapter 어노테이션을 사용하기 위해 추가되었습니다!
kapt는 이후에 기능 업데이트가 없을 예정이고([코틀린 공식 문서](https://kotlinlang.org/docs/kapt.html#using-in-gradle)), ksp가 조금 더 성능이 좋기 때문에([안드로이드 공식 문서](https://developer.android.com/studio/build/migrate-to-ksp?hl=ko)) kapt보다 ksp를 권장하기도 합니다.
하지만 데이터 바인딩 관련 기능은 ksp에서 지원하지 않기 때문에 kapt를 사용하였습니다! ([안드로이드 공식 문서](https://developer.android.com/studio/build/migrate-to-ksp?hl=ko))

2023-10-03 07:57 UTC, otter66 commented on app/src/main/res/values/strings.xml
> +    <string name="app_name">🦦 수달 그림판 🦦</string>
어... 이 부분은 생각해본 적이 없네요. 단지 수달임을 표시하고 싶었습니다. 
하지만 변수명으로도 이모지는 가능하니 괜찮지 않을까요...?
팀 프로젝트에서 이런식으로 할 생각은 정말 먼지만큼도 없지만요...

2023-10-03 08:42 UTC, otter66 commented on app/src/main/java/woowacourse/paint/PenToolView.kt
> +class PenToolView(
저 또한, 하나의 레이아웃 안에서 Constraint Layout을 이용해 레이아웃 뎁스를 만들지 않고 충분히 표현 가능하다고 생각합니다!
그러나 색깔 종류가 변경될 경우, 굵기가 변경될 경우, 그 외에 추가적인 기능이 생길 때 등을 가정해보았습니다. 이 경우 변경점을 외부에 미치치 않도록, 분리될 수 있도록 설계해 보았습니다!

2023-10-03 09:19 UTC, otter66 commented on app/src/main/java/woowacourse/paint/PenToolView.kt
> +            container.addView(view)
시간 부족 관계로 눈을 돌릴 수밖에 없던 아이를 캐치하셨군요... 🥲 
덕분에 잊지 않고 메서드 분리하였습니다!

2023-10-03 10:27 UTC, DYGames commented on app/src/main/java/woowacourse/paint/PenToolView.kt
> +class PenToolView(
색의 종류, 굵기의 변화, 추가 기능은 PaintAcitivity (현재는 MainAcitivty)의 역할이 아닐까요? 이를 재사용할 경우가 있을지 궁금합니다. 없다면 오버엔지니어링이라고 생각되네요.

2023-10-03 11:14 UTC, otter66 commented on app/src/main/java/woowacourse/paint/PenToolView.kt
> +class PenToolView(
커스텀 뷰는 재사용 목적 외에는 사용하지 않나요? 
재사용 될 일이 없고, 하나의 Activity에서 관리할 수도 있다고 생각합니다. 
하지만 pen이라는 객체를 관리하고, 추가로 현재 제 기능상 Visibility를 한 번에 관리하는 등 공통된 목적이 있습니다.
PenToolView는 관련 기능을 묶어 외부에서 사용이 편리하도록 하는 것이 목적입니다!

2023-10-03 11:23 UTC, otter66 commented on app/src/main/java/woowacourse/paint/PenToolView.kt
> +class PenToolView(
커스텀 뷰는 재사용 목적 외에는 사용하지 않나요? (커스텀 뷰를 이번에 처음 접해봐서 잘 모릅니다...🤔)
PenToolView는 아직까지 재사용 될 일이 없으며 하나의 Activity에서 관리할 수도 있다고 생각합니다.
하지만 pen이라는 객체를 관리하고, 추가로 현재 제 기능상 관련 뷰의 Visibility를 한 번에 관리하는 등 pen과 관련된 뷰 로직들이 있습니다.
PenToolView는 관련 기능을 묶어 외부에서 사용이 편리하도록 하는 것이 목적입니다!

2023-10-03 11:27 UTC, DYGames commented on app/src/main/java/woowacourse/paint/PenToolView.kt
> +class PenToolView(
음 물론 해당 목적이라면 충분히 커스텀 뷰 (사실 컴파운드 뷰이지만)을 써도 무방하겠네요

하지만 이런 객체를 커스텀 뷰로 만들다보면 기준이 모호해져 프로젝트가 커지면 어떤 뷰는 그냥 xml에 작성할지, 어떤 뷰는 커스텀 뷰로 만들지 결정하기 어려워 질 수도 있다고 생각합니다.

그 이유는 여전히 안드로이드 기본 뷰로도 표현 가능한 뷰이기 때문이죠.

사실 커스텀 뷰 만든다고 문제 될 일은 없죠! 쓰고싶으면 쓰는 거지만 왜 쓰는지에 대한 뚜렷한 목적과 이해가 필요하다 생각합니다.

2023-10-03 11:48 UTC, otter66 commented on app/src/main/java/woowacourse/paint/BindingAdapters.kt
> +fun PenToolView.setVisibility(value: Boolean) {
확장함수가 사실 눈엣가시였는데요...! 코드를 계속 보다보니 보내버릴 구현이 떠올라서 보내줬습니다!
PenToolView라는 것을 커스텀뷰로 만들었는데, 굳이 확장함수로 만들 필요 없이 PenToolView에서 관리하도록 하였습니다!!!
마찬가지로 ViewModel도 함께 사라졌습니다!

2023-10-03 13:35 UTC, otter66 commented on app/src/main/java/woowacourse/paint/PenToolView.kt
> +        ViewPenToolBinding.inflate(LayoutInflater.from(context), this, true)
엇...! 생각해보지 않은 부분 집어주셔서 감사합니다!!! 
열심히 찾아보았으나 관련 자료를 찾기 어려운 것 같습니다🥲

inflate할 때 attachToRoot를 true로 주었기 때문에 같은 인스턴스를 공유하는 것이라 생각했습니다. 하지만 직접 두 주소를 확인해보니 각각 다른 주소였습니다. attachToRoot와는 무관했던 것 같습니다.
해당 블로그(https://gun0912.tistory.com/38)를 참고하여 수정하였습니다!

attachToRoot는 무엇일까요...? 🥲 도와주세요 코건님!

2023-10-03 13:37 UTC, otter66 commented on app/src/main/java/woowacourse/paint/PaintView.kt
> +        lines.last().path.moveTo(event.x, event.y)
😱그렇게 좋은 방법이😱 !!!

2023-10-03 14:19 UTC, DYGames commented on app/src/main/java/woowacourse/paint/PenToolView.kt
> +        ViewPenToolBinding.inflate(LayoutInflater.from(context), this, true)
attachToRoot는 말그대로 parent ViewGroup에 inflate 한 View를 즉시 addView() 해준다는 거죠~

2023-10-03 14:36 UTC, otter66 commented on app/src/main/java/woowacourse/paint/PenToolView.kt
> +        ViewPenToolBinding.inflate(LayoutInflater.from(context), this, true)
아 하 !

2023-10-03 14:43 UTC, otter66 commented on app/src/main/java/woowacourse/paint/PenToolView.kt
> +class PenToolView(
확실히 코드 양이 많아지다 보면 기준이 모호해지는 시점이 오겠네요...🤔 
아직은 규모가 작은 미션이기도 하고, 학습의 목적도 있었기 때문에 우선 그대로 두겠습니다!

2023-10-03 15:03 UTC, otter66 commented on app/src/main/java/woowacourse/paint/MainActivity.kt
> +        binding.paintView.pen = selectedPen
Pen은 현재 너무나도 Android 의존성이 강한 객체라 뷰모델에 두어도 좋을지 고민입니다🤔🤔🤔

2023-10-03 15:07 UTC, otter66 commented
코건 리뷰 반영 완료입니다!
[리뷰 반영 커밋입니다!](https://github.com/woowacourse/android-paint/pull/24/files/a842c97aa917d60bfec238cf51c37066baff26eb..65eab24c82c681ab9fb44d1b4b8eabaee8c7cc37)

코멘트 답글까지 빠른 코건... 정말 대단하시군요... 
덕분에 리뷰 반영하면서 바로바로 의문이 해결되어서 너무 좋았습니다!!!

2023-10-03 15:08 UTC, DYGames commented on app/build.gradle.kts
> +                "proguard-rules.pro",
포기하긴 싫지만 개인의 성향따라 가는건 인정입니다..

물론 트레일링 콤마를 쓰면 편해지지만... 보기 너무 안좋아!!

2023-10-03 15:09 UTC, DYGames commented on app/src/main/java/woowacourse/paint/MainActivity.kt
> +        binding.paintView.pen = selectedPen
뷰모델이 아닌 xml 내에서 양방향 바인딩을 의미한 것이었어요.

2023-10-03 15:10 UTC, otter66 commented on app/build.gradle.kts
> +                "proguard-rules.pro",
여전히 보기 안좋다는건 공감하지만... 
🤗 세뇌 전파 🤗

2023-10-03 15:10 UTC, DYGames commented on app/src/main/res/values/strings.xml
> +    <string name="app_name">🦦 수달 그림판 🦦</string>
유니코드 외의 인코딩으로 앱 이름을 표현할 경우가 있을까요? 없다면 내버려둬도 되겠네요~!

2023-10-03 15:16 UTC, DYGames approved these changes
수달 고생하셨습니다~! 많은 점이 바뀌었네요.

리뷰 반영은 다음 단계에서 확인할게요~!

화이팅 💯

2023-10-03 15:16 UTC, DYGames commented on app/src/main/java/woowacourse/paint/PaintView.kt
> +        invalidate()
last()가 남아있네요..?

2023-10-03 15:16 UTC, DYGames commented on app/src/main/java/woowacourse/paint/PenToolView.kt
> +    private lateinit var colorContainer: LinearLayout
이 프로퍼티들은 lateinit을 쓰지 않고 PenToolView 생성 시점에서 초기화 해 줄 수 있을 것 같아요.

2023-10-03 15:16 UTC, DYGames commented on app/src/main/java/woowacourse/paint/PenToolView.kt
> +    fun changeVisibility() {
뭘로 change하는지 알 수 없는 네이밍이네요.
toggle 정도가 어떨까요?

2023-10-03 15:16 UTC, DYGames commented on app/src/main/java/woowacourse/paint/PenToolView.kt
> +        val layoutInflater = context.getSystemService(inflateService) as LayoutInflater
`LayoutInflater.from(context)`으로 쓰는게 더 간편하지 않을까요?

2023-10-03 15:16 UTC, DYGames commented on app/src/main/java/woowacourse/paint/PenToolView.kt
> +        val v: View = layoutInflater.inflate(R.layout.view_pen_tool, this, false)
이것도 동일한데 이미 커스텀 뷰의 인스턴스가 생성된 시점에서 또 inflate 해주는것 아닐까요?

2023-10-03 15:17 UTC, merged