[써니] 뷰 챌린지 미션 1단계 제출합니다.
woowacourse/android-paint pull request #3
Opened 2023-09-26 11:59 UTC by inseonyun

안녕하세요 로이킴 팬입니다.

UI 상태 저장을 위해 ViewModel을 굳이? 추가해줘서 구현했습니다.
PathPaint List도 같이 저장할까 했는데 현재 뷰에서 화면 회전을 하면 팔레트와 버튼이 가려서 그림판이 안 보이더라구요.. 그래서 구현을 했다가 굳이? 싶어서 롤백 했습니다. 
그래서 현재 PaintColor와 StrokeSize만 저장하여 구성 변경 후 돌아와도 유지되도록 했습니다.

팔레트에 여러 색깔이 추가 될 수 있고 이를 반복적으로 xml에 추가해주는건 멍청하다고 생각돼서 Recyclerview로 구현했습니다

크롱의 멋진 리뷰 기다리고 있겠습니다.
감사합니다

2023-09-27 14:44 UTC, krrong requested changes
안녕하세요 써니!☀️ 
팬이라고 하시기에 싸인 해드렸습니다🦖~  
<img src=https://github.com/woowacourse/android-paint/assets/84285337/96aa1a33-cc03-4738-8a9e-ea5950bfbdfb, width=180>

레벨 2 마지막 미션을 써니와 함께 하면서 많은 도움을 받은 게 엊그제 같은데 벌써 레벨 4 마지막 미션을 함께하고 있네요. 시간이 정말 빠른 것 같아요!  
굉장히 빨리 미션을 제출해주셔서 제 행복할 추석이 약간 슬플뻔 했지만 다행히도 추석전에 리뷰가 끝나 다시 추석이 행복해질 것 같네요 :)  
너무 잘 구현해주셔서 리뷰할 게 없었고 궁금한 점만 잔뜩 있는 것 같네요ㅎㅎ!

ps. 저격글 잘보았습니다..!-0-

2023-09-27 14:44 UTC, krrong commented on app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintBottom_toBottomOf="parent" />
오 이렇게 속성 값을 지정해줄 수도 있네요! 👍 배워갑니다!

2023-09-27 14:44 UTC, krrong commented on README.md
> +    - [x] 브러시 굵기를 변경할 수 있다.
다음엔 readme도 챱챱 해보죠!!

2023-09-27 14:44 UTC, krrong commented on app/src/main/res/values/colors.xml
> +    <color name="orange">#FF9800</color>
기존에 있는 값을 사용하고 주황색만 추가해주셨네요!  
좋은 것 같습니다!

2023-09-27 14:44 UTC, krrong commented on app/src/main/java/woowacourse/paint/MainViewModel.kt
> +
아래에 있는 setPaintColor 메서드를 통해 PaintColor를 변경하고 있는데, 제공되는 setter 메서드 대신 setPaintColor 메서드를 정의해준 이유가 있을까요?🙃

2023-09-27 14:44 UTC, krrong commented on app/src/main/java/woowacourse/paint/Paint.kt
> +class Paint(
리사이클러 뷰에 들어가는 아이템도 뷰를 따로 만들어주셨군요! 좋은 것 같아요 🤠

2023-09-27 14:44 UTC, krrong commented on app/src/main/java/woowacourse/paint/PaletteAdapter.kt
> +    override fun getItemCount(): Int = items.size
값을 반환하는 함수에서 return을 쓰는 경우와 쓰지 않는 경우를 구분하는 기준이 있나요?🤔(단순 궁금)

2023-09-27 14:44 UTC, krrong commented on app/src/main/java/woowacourse/paint/PaletteAdapter.kt
> +        return PaletteViewHolder(parent, onPaletteClick)
PaletteViewHolder에서 받고 있는 파라미터의 이름은 paletteClick입니다! 일치 시켜 보는 것은 어떨까요?

2023-09-27 14:44 UTC, krrong commented on app/src/main/java/woowacourse/paint/model/PathPaint.kt
> +    fun resetPaint(): PathPaint = PathPaint(paint = Paint(paint))
써니가 이미 Paint라는 View를 구현하는 클래스를 만들어줘서 여기서 넘겨주는 Paint가 android.graphics.Paint 객체인지 만든 커스텀 뷰 객체인지 잠시 헷갈렸어요!  
Paint라는 이름의 커스텀 뷰 클래스의 이름을 변경해보는 것은 어떨까요?🤔

2023-09-27 14:44 UTC, krrong commented on app/src/main/java/woowacourse/paint/Canvas.kt
> +    private var currentPathPaint: PathPaint = PathPaint()
Pair에서 하나의 클래스로! 👍

2023-09-27 14:44 UTC, krrong commented on app/src/main/java/woowacourse/paint/Canvas.kt
> +                initPaint()
ACTION_UP 이벤트가 발생할 때마다 initPaint 메서드를 호출하여 paint를 초기화하고 있네요!  
색상이나 굵기가 변경될 때를 대비하여 있는 작업으로 보이는데 색상이 변경되지 않을때 혹은 굵기가 변경되지 않았을 때는 어떻게 될까요?!  
굵기 조절보다는 단순히 선분을 그리기 위해 펜을 터치하고 떼는 빈도가 훨씬 많은 것 같아 질문드립니다. 🙃

2023-09-27 14:44 UTC, krrong commented on app/src/main/java/woowacourse/paint/MainActivity.kt
> +        super.onRestoreInstanceState(savedInstanceState)
꼼꼼한 처리 좋은 것 같네요ㅎㅎ

2023-09-27 14:44 UTC, krrong commented on app/src/main/java/woowacourse/paint/MainViewModel.kt
> +        _colors = colors.toMutableList()
이렇게 처리한 이유는 구성 변경이 일어난 이후에도 같은 색들이 추가되어서인 것 같아요!  
MutableList가 variable로 선언되어 있으니 굉장히 어색한데요.   
다음과 같은 방법은 어떤가요?  
```kotlin
private val _colors: MutableList<Int> = mutableListOf()
    ...
fun setColors(colors: List<Int>) {
    _colors.clear()
    _color.addAll(colors)
}
```

2023-09-27 14:44 UTC, krrong commented on app/src/main/java/woowacourse/paint/MainViewModel.kt
> +        _colors = colors.toMutableList()
아니면 뷰모델의 생성자의 인자로 컬러 리스트를 넘겨주어 생성자에서 주입으..ㄹ.. 여기까지 하겠습니다.🦖

2023-09-28 14:10 UTC, inseonyun commented on app/src/main/java/woowacourse/paint/MainViewModel.kt
> +
앗 그러게요 특별한 처리를 따로 해주지 않아 의미 없는 코드였네요
감사합니당 👍🏻

2023-09-28 14:12 UTC, inseonyun commented on app/src/main/java/woowacourse/paint/Paint.kt
> +class Paint(
앗 사실 만들 때는 몰ㄹ랐는데 코드 제출하고 View가 아닌 Paint(커스텀 뷰)로 했을 때의 장점이 뭔지 생각을 해내지 못해 '다시 바꿔야지' 하고 있었는데 크롱이 보기엔 어떤 점이 좋은 것 같았나용? (크롱의 생각을 들어보고 한 번 더 생각해보고 수정해볼게요!)

2023-09-28 14:18 UTC, inseonyun commented on app/src/main/java/woowacourse/paint/PaletteAdapter.kt
> +    override fun getItemCount(): Int = items.size
다른 사람들의 기준이 어떤지, 이와 관련해서 컨벤션이 있는지 잘 모르겠지만 제 경우 값을 반환하는 코드가 명확하다면 이와 같이 return을 쓰지 않고 한 줄에 표기를 많이 하는 것 같아요!

2023-09-28 14:19 UTC, inseonyun commented on app/src/main/java/woowacourse/paint/PaletteAdapter.kt
> +    override fun getItemCount(): Int = items.size
근데 코드 통일성이 좀 부족한 거 같아 보이긴 하네요 허허 통일하도록 수정해보겠습니다 :(

2023-09-28 14:26 UTC, inseonyun commented on app/src/main/java/woowacourse/paint/PaletteAdapter.kt
> +    override fun getItemCount(): Int = items.size
이와 관련해서 컨밴션이 있나 찾아봤는데 Kotlin Docs에서도 명확한 경우 이와 같이 단일 표현식으로 해주는 것 같아요 : )
[Kotlin Docs](https://kotlinlang.org/docs/coding-conventions.html#functions)

2023-09-28 14:54 UTC, inseonyun commented on app/src/main/java/woowacourse/paint/Canvas.kt
> +                initPaint()
같은 페인트 객체를 썼을 때, 다음 선분을 그릴 경우 이전 페인트 객체를 사용하다보니 크롱이 말씀하신 거처럼 색상이나 굵기 변경 시 같은 페인트 객체를 사용하던 모든 선분의 굵기, 색상이 변동됩니다!
이러한 문제점을 해결하기 위해 선분을 그리는 행위가 끝나면 새롭게 객체를 생성해주도록 하였습니다.

삼성 노트나, 굿노트와 같은 그림판 앱들을 보면 추후 특정 선분에 대해서만 선택해서 색상, 굵기, 스타일 등을 조절할 수 있는데요!
만약 색깔, 굵기가 변동된 경우에만 페인트 객체를 새로 초기화 해주는 경우에는 특정 선분만 속성을 새로 정의하지 못 할 수도 있다고 생각합니당
하지만 크롱의 얘기를 들어보니 모든 선분을 하나의 굵기, 색깔로 그리는 경우에는 이러한 작업이 불필요한 작업일 수 있단 생각도 드네요.
이와 관련해서는 한 번 더 고민해볼게요!

2023-09-28 15:06 UTC, inseonyun commented on app/src/main/java/woowacourse/paint/MainViewModel.kt
> +        _colors = colors.toMutableList()
위 방법을 고려 했었는데 Clear를 하고, 다시 그 리스트에 addAll 하는 것이 과연 효율적인 행위일까를 먼저 생각했었습니다.
이와 관련해서는 [레퍼런스](https://stackoverflow.com/questions/6961356/list-clear-vs-list-new-arraylistinteger)가 몇 몇 보여 첨부합니당

> 행복한 추석 연휴를 위한 요약 
> 너 리스트에 아이템 많아?(만 개 이상 돼?)아이템 사이즈 명확히 몰라?
> 그럼 새 객체 대입
> 너 리스트 사이즈 명확히 알고 데이터 적어? 
> 그럼 clear 써 (새 객체 대입 해도 시간, 메모리 큰 차이 없음)

결론, 크롱이 제시한 방법으로 수정하겠읍니당 : )

2023-09-28 15:19 UTC, inseonyun commented
싸인 너무 감사합니다. 덕분에 풍족한 한가위 보낼 수 있을 거 같습니다.
답례로 제 추석 감사인사 보내드렸습니다. 리뷰 요청은 덤입니다.

<img width="400" alt="image" src="https://github.com/woowacourse/android-paint/assets/84364741/9ebec237-69a2-47a5-91f6-2e1e7fbdf02d">

이번 리뷰 요청에 변경점은 많지 않습니다!
+ Paint 커스텀뷰 네이밍 수정
+ Hue(구 Paint) 커스텀뷰 set 함수 DataBinding set으로 수정
+ MainViewModel Set 함수 제거 후 setter로 대체
+ MainViewModel 리스트 새 리스트 대입이 아닌 기존 리스트 객체 재사용
+ 기타 컨벤션 통일

리뷰 감사합니다 크롱!
연휴 잘보내세요 : )

2023-09-30 19:05 UTC, krrong requested changes
정말 괜찮았는데.. 주신 명절선물 잘 받았습니다..!☀️  
전반적으로 코드가 깔끔해서 제 눈에는 고칠 점들을 찾기 어렵고 오히려 제가 많이 배워가는 것 같아요 🥸  
제가 남긴 코멘트의 써니의 생각을 일목요연하게 정리해주신 덕분에 생각을 잘 나눈 것 같아 기분이 좋습니다! 남은 기간동안도 핑퐁을 잘 주고 받았으면 좋겠네요🏓  
고민해볼만한 점들을 코멘트로 남겨두었고, 다음 단계 요구사항이 어떻게 나오느냐에 따라 구조가 바뀔 수도 있을 것 같아 반영은 써니의 선택으로 남겨둘게요!  
코멘트 확인을 위해 Request Changes 하겠습니다 :)

2023-09-30 19:05 UTC, krrong commented on app/src/main/res/layout/activity_main.xml
> +            android:layout_width="match_parent"
ConstraintLayout의 자식뷰는 match_parent 대신 0dp 사용을 권장합니다!  
https://developer.android.com/develop/ui/views/layout/constraint-layout#adjust-the-view-size

2023-09-30 19:05 UTC, krrong commented on app/src/main/java/woowacourse/paint/Paint.kt
> +class Paint(
RecyclerView 안에 들어가는 뷰를 직접 커스텀 해줌으로써 해당 뷰에서의 처리를 조금 더 간단하게 처리할 수 있고 관심사 분리도 가능하다고 생각이 들었어요! 써니 코드에서는 리사이클러뷰 아이템의 background의 색상의 변경을 Hue라는 커스텀 뷰 안에서 진행하고 xml에서 처리하고 있기 때문에 뷰적인 부분의 관심사가 분리가 잘 되었다고 느꼈어요! 🦖  

하지만 현재는 프로젝트의 규모가 작아서 한눈에 알아볼 수 있지만 만약 규모가 커진다면 또 다른 이야기가 될 수도 있을 것 같고, MainActivity의 xml 파일을 살펴보니 RecyclerView 안에 들어가는 아이템을 지정해주었지만 Design탭에서 보이지 않더라구요. 이런 부분들은 확실히 단점으로 작용할 수 있을 것 같아요!  

써니가 잘 판단해서 적용하면 좋을 것 같습니다 🙃

2023-09-30 19:05 UTC, krrong commented on app/src/main/java/woowacourse/paint/Canvas.kt
> +                initPaint()
> 특정 선분에 대해서만 선택해서 색상, 굵기, 스타일 등을 조절할 수 있는데요!

라는 말은 아마도 그려져 있는 선분들 중에서 선택하여 색상, 굵기, 스타일을 변경할 수 있다는 것이겠죠?  
저는 이 부분까지 고려하지는 못했었는데, 써니의 의견에 충분히 공감합니다! 다음 단계에서 어떤 요구사항이 나올지 모르니 요구사항을 확인한 뒤에 고민해봐도 늦지 않겠네요!

리뷰를 달다가 한 가지 좋은 방법이 떠올랐어요!  
현재 써니는 Path와 Paint를 갖는 PathPaint 객체로 선분들을 관리하는데, 색상, 굵기, 스타일을 변경하고 싶은 특정 선분을 찾을 수 있다고 가정하면 알맞는 PathPaint를 찾을 수 있을 것이고, 찾은 PathPaint의 paint를 바꿔주면 되는 것이 아닐까? 하는 생각이 들었답니다! (그냥 이야기 해보고 싶어서 남긴 코멘트에요🤠)

2023-09-30 19:05 UTC, krrong commented on app/src/main/java/woowacourse/paint/MainActivity.kt
> +            ),
색상을 관리하는 더 좋은 방법이 있지 않을까요?

2023-09-30 19:05 UTC, krrong commented on app/src/main/java/woowacourse/paint/MainActivity.kt
> +        )
```kotlin
binding.rsMain.addOnChangeListener { _, value, _ ->
    mainViewModel.strokeSize = value
}
```
이렇게도 작성할 수 있답니다!

2023-09-30 19:05 UTC, krrong commented on app/src/main/java/woowacourse/paint/MainViewModel.kt
> +    val colors: List<Int> get() = _colors.toList()
색상을 관리하는 일급컬렉션을 만들어도 좋을 것 같아요🙃  
이 부분은 변경점이 많아질 수도 있고, 다음 단계의 요구사항이 어떻게 나오느냐에 따라 충분히 바뀔 수 있는 영역이기 때문에 반영은 써니에게 맡길게요!

2023-09-30 19:05 UTC, krrong commented on app/src/main/java/woowacourse/paint/PaletteViewHolder.kt
> +    fun bind(hue: Int) {
`@ColorInt` 애노테이션을 사용해볼까요?

- `@ColorInt` 애노테이션을 활용하면 어떤 이점이 있을까요?
- `@ColorInt`와 `@ColorRes`은 어떤 점이 다를까요? 

만약 반영한다면 프로젝트 전반적으로 사용하면 더 효과적일 것 같아요!

2023-09-30 19:05 UTC, krrong commented on app/src/main/java/woowacourse/paint/Canvas.kt
> +        initPaint()
이 두가지 속성은 어떤 것을 해주나요? (진짜 모름)

2023-09-30 19:05 UTC, krrong commented on app/src/main/java/woowacourse/paint/Canvas.kt
> +            }
이 코드가 없어도 정상적으로 동작되는 것 같아요! 혹시 제가 파악하지 못한 필요한 이유가 있을까요?🙃

2023-10-02 10:49 UTC, inseonyun commented on app/src/main/java/woowacourse/paint/Canvas.kt
> +        initPaint()
setFocusable은 주로 터치 모드와 키패드 모드(위/아래/다음 키 사용) 모두에서 뷰의 포커스 이벤트를 활성화/비활성화하는 데 사용됩니다.
setFocusableInTouchMode는 주로 터치 모드에서만 뷰의 포커스 이벤트를 활성화/비활성화하는 데 사용됩니다.
setFocusable을 비활성화하면 터치 모드에서 뷰의 포커스 이벤트도 비활성화됩니다.

라고 하네요

저도 몰랐.. ㅎ;
예제코드에 있길래 무지성 복붙 했읍니다,,,

2023-10-02 10:50 UTC, inseonyun commented on app/src/main/java/woowacourse/paint/Canvas.kt
> +            }
MOVE 하지 않았을 때 그저 DOWN만 했을 때 그 점을 그려주기 위함입니다

2023-10-03 15:41 UTC, krrong commented on app/src/main/java/woowacourse/paint/Canvas.kt
> +            }
아하 점을 찍기 위함이군요! 👍

2023-10-03 15:46 UTC, krrong approved these changes
절거운 추석보내셨나요? 피드백 반영하느라 고생많았습니다!  
더 이상 코멘트 드릴 것 없이 잘 구현해주셔서 머지하도록 하겠습니다 🦖  
써니와 의견 주고 받으면서 미션하니 재밌었어요🙃  
다음 단계에서 뵐게요!

2023-10-03 15:46 UTC, merged