[반달] 뷰 챌린지 미션 2단계 제출합니다.
woowacourse/android-paint pull request #37
Opened 2023-10-09 13:11 UTC by no1msh

<img src="https://github.com/woowacourse/android-paint/assets/22425650/ed2f42d4-e066-4e58-8ac2-62b8205bb165" width="30%">

멘데에에엘~ 안녕하세용~
미션하랴 프로젝트하랴 여러므로 바쁘군요 ㅎㅎ

선택 요구사항 까지 충족 시키고 미션 제출합니다!

리뷰부탁드리겠습니다~

2023-10-10 08:25 UTC, rhthrhrl0 requested changes
안녕하세요 반달! 전반적으로 잘 짜여진 것 같아요 👍 사소한 리뷰 몇 개 달았는데 확인 부탁드립니다!

2023-10-10 08:25 UTC, rhthrhrl0 commented on app/src/main/java/woowacourse/paint/customview/paint/BrushColor.kt
getColorBoxes 함수의 위치를 BrushColorBox 클래스 안에 놓는게 더 좋을 것 같아요! 왜냐하면, 이 함수가 안에 있게 됨으로써, BrushColor 파일에서 BrushColorBox에 대한 의존성이 생겼어요! 반대로, BrushColorBox는 어차피 BrushColor를 알고 있어서, 이 함수가 BrushColorBox로 가는게 더 좋아보여요

2023-10-10 08:25 UTC, rhthrhrl0 commented on app/src/main/java/woowacourse/paint/customview/paint/PaintingView.kt
> +        _paintings.removeLast()
removeLast는 제거함과 동시에 제거한 요소를 반환해줍니다. removeLastOrNull을 사용하면 한 줄로 줄일 수 있을 것 같네요!

2023-10-10 08:25 UTC, rhthrhrl0 commented on app/src/main/java/woowacourse/paint/customview/paint/PaintingView.kt
> +        _paintingHistory.removeLast()
동일하게 한 줄로 줄일 수 있을 것 같아요

2023-10-10 08:25 UTC, rhthrhrl0 commented on app/src/main/java/woowacourse/paint/customview/paint/tool/PaintTool.kt
> +sealed interface PaintTool {
실드 인터페이스를 사용한 추상화 좋네요~

2023-10-10 08:25 UTC, rhthrhrl0 commented on app/src/main/java/woowacourse/paint/customview/paint/PaintingView.kt
> +        get() = _paintings.map { stroke ->
Painting으로 바꿀때, 같이 수정이 안되고 stroke로 남은 것 같아요!

2023-10-10 08:25 UTC, rhthrhrl0 commented on app/src/main/java/woowacourse/paint/customview/paint/tool/Oval.kt
> +        painting.path.addOval(
Path에 그리는 거는 생각을 못했네요. 모든 내용들을 Path로 관리할 수 있을 것 같네요! 👍 👍

2023-10-10 08:25 UTC, rhthrhrl0 commented on app/src/main/java/woowacourse/paint/main/MainViewModel.kt
>      private val _brushThickness: MutableLiveData<Float> = MutableLiveData(DEFAULT_BRUSH_THICKNESS)
이 줄 리뷰는 아니고요 ㅋㅋㅋㅋ 
사실 위에 13,14 번째 줄에 대한 리뷰입니다. 그런데, 과거 코드라서 리뷰다는 법을 모르겠네요...
<img width="783" alt="스크린샷 2023-10-10 오후 5 15 24" src="https://github.com/woowacourse/android-paint/assets/67176829/9424171a-a981-4b45-808d-a87c7705e44b">
지금 구조에서 항상 _brushColor는 _brushColorBoxes에서 선택된 요소의 값을 따라가는 것 같아요.
만약 이렇게 특정 라이브데이터에 종속된 구조라고 한다면, LiveData의 map 함수나 switchMap을 사용해볼 수 있을 것 같아요. 
Transformation.map에 대해 공부해보시면 좋을 것 같습니다!

2023-10-12 10:57 UTC, no1msh commented on app/src/main/java/woowacourse/paint/customview/paint/BrushColor.kt
어우 나이스한 생각입니다. 수정했어요!

2023-10-12 10:57 UTC, no1msh commented on app/src/main/java/woowacourse/paint/customview/paint/PaintingView.kt
> +        _paintings.removeLast()
오 반환값을 준다는 사실을 망각하고 있었군요 감사합니다!

2023-10-12 10:57 UTC, no1msh commented on app/src/main/java/woowacourse/paint/customview/paint/PaintingView.kt
> +        get() = _paintings.map { stroke ->
오우 다시한번 프로젝트 검사해서 수정하였습니다!

2023-10-12 10:57 UTC, no1msh commented on app/src/main/java/woowacourse/paint/main/MainViewModel.kt
>      private val _brushThickness: MutableLiveData<Float> = MutableLiveData(DEFAULT_BRUSH_THICKNESS)
이런게 있었군요 멘델 ㅠㅠ 덕분에 공부했습니다.

2023-10-12 11:56 UTC, rhthrhrl0 approved these changes
반달 고생많으셨습니다! 리뷰 반영도 너무 잘해주셨네요~ 다음 단계 진행해주시면 될 것 같아요!!

2023-10-12 11:57 UTC, merged