[우기] 뷰 챌린지 미션 1단계 제출합니다.
woowacourse/android-paint pull request #4
Opened 2023-09-26 13:43 UTC by boogi-woogi

안녕하세요 뽀또! 이번 뷰 챌린지 미션 잘 부탁드립니다~

1단계 미션을 진행하면서 구현한 주요 클래스들에 대한 설명입니다~

### PaintingRecord
터치가 시작되고(`ACTION_DOWN`) 터치가 끝날때까지(`ACTION_UP`)의 path 기록을 저장하고 있는 데이터 클래스입니다.

### Painting
PaintingRecord를 보관하고 `onDraw()` 단계가 시작될 때 이전의 그림들을 복구하기 위한 작업을 수행합니다.

이해가 되지 않는 코드에 대해서는 꼭 물어봐주시면 감사하겠습니다~~ 추석 잘 보내세요:smiley:

2023-09-30 14:55 UTC, hyunji1203 requested changes
우기~ 레벨3-4 때 많이 만나지 못해 아쉬웠는데 이번 미션에서 리뷰어로 만나게 되어 너무 반갑습니다!
그리고 리뷰가 좀 늦어졌는데 양해해주셔서 너무 감사합니다🥹 
전반적으로 깔끔하게 잘 구현해주셨네요! 
덕분에 코드 리뷰 수월하게 했습니다😎 
리뷰 확인해주시면 되고, 즐거운 추석 보내시길 바랍니다~!!

<img width="315" alt="image" src="https://github.com/woowacourse/android-paint/assets/83613106/465c8001-b9be-4a9a-9961-633a9490d6ce">

2023-09-30 14:55 UTC, hyunji1203 commented on app/src/main/java/woowacourse/paint/MainActivity.kt
> +            rs.valueTo = MAXIMUM_WIDTH
해당 부분은 xml에서도 `"valueForm / valueTo"`를 사용해 설정 가능하답니다! 
xml에서 설정해주면 코드가 줄어들 것 같아요!

2023-09-30 14:55 UTC, hyunji1203 commented on app/src/main/java/woowacourse/paint/MainActivity.kt
> +    private fun setupView() {
해당 함수 네이밍이 `view`라고 되어있는데, 뷰들 중 어떤 뷰를 세팅해주는지 명시적으로 알 수 있으면 좋을 것 같아요! 예를 들어 `setupPalette`나 `setupRecyclerView` 처럼요! 물론 이건 저의 개인적인 생각이라 우기의 의견도 궁금합니다!

2023-09-30 14:55 UTC, hyunji1203 commented on app/src/main/java/woowacourse/paint/PaintingView.kt
> +        isFocusableInTouchMode = true
이 친구들은 어떤 역할을 하는 코드인가요? 궁급합니다!ㅎㅎㅎ

2023-09-30 14:55 UTC, hyunji1203 commented on app/src/main/java/woowacourse/paint/Painting.kt
> +class Painting(private val records: MutableList<PaintingRecord> = mutableListOf()) {
일급컬렉션 👍

2023-09-30 14:55 UTC, hyunji1203 commented on app/src/main/java/woowacourse/paint/MainActivity.kt
> +        binding.rvColors.adapter = ColorsAdapter(
해당 리사이클러뷰 아이템의 크기가 고정되어있는 상황이네요! 이런 상황에서는 `setHasFixedSize`를 사용해 리사이클러뷰의 효율을 높일 수 있을 것 같은데 어떻게 생각하나요?!

2023-09-30 14:55 UTC, hyunji1203 commented on app/src/main/java/woowacourse/paint/PaintingView.kt
> +                MotionEvent.ACTION_UP -> {
현재는 드래그를 하며 그림을 그릴 때 선이 그려지지만, 클릭만 했을 때는 아무것도 그려지지 않는 상황이네요😎
드래그를 안하고 클릭만 했을 상황에도 붓이 닿아 점이 찍히는 것 처럼 바꿀 수도 있을 것 같은데 어떠신가요?!

2023-09-30 14:55 UTC, hyunji1203 commented on app/src/main/res/values/colors.xml
> +    <color name="red">#FF0000</color>
resource로 관리👍

2023-10-02 08:07 UTC, boogi-woogi commented on app/src/main/java/woowacourse/paint/PaintingView.kt
> +                MotionEvent.ACTION_UP -> {
사실 이 부분에 대해서 인지는 하고 있었는데 뽀또에게 딱 걸렸네요 ㅋㅋㅋㅋㅋㅋ 개선해보겠습니다!!

2023-10-02 08:08 UTC, boogi-woogi commented on app/src/main/java/woowacourse/paint/MainActivity.kt
> +        binding.rvColors.adapter = ColorsAdapter(
setHasFixedSize라는 것을 얼마 전에 알게되어 사용해 본적이 없었고 이론적으로만 인지하고 있었는데 감사합니다~

2023-10-02 08:14 UTC, boogi-woogi commented on app/src/main/java/woowacourse/paint/PaintingView.kt
> +        isFocusableInTouchMode = true
`Focusable`은 순수하게 해당 뷰가 포커스를 가질 수 있는지 없는지를 의미하고 `inFocusableInTouchMode`는 터치모드에서 해당 뷰가 포커스를 받을 수 있는지를 설정하는 값입니다! (사실 강의자료에 있는 코드를 복사 붙여넣기를 하다보니 이런 코드가 생겼었는데 말씀해주신 덕분에 찾아볼 수 있었습니다!)

참고 자료: https://android-developers.googleblog.com/2008/12/touch-mode.html

2023-10-02 09:14 UTC, boogi-woogi commented on app/src/main/java/woowacourse/paint/MainActivity.kt
> +    private fun setupView() {
뽀또의 의견에 전적으로 동의합니다~~

2023-10-02 09:30 UTC, boogi-woogi commented
날카로운 리뷰 남겨주셔서 감사합니다! 말씀해주신 사항들 반영해보았습니다:slightly_smiling_face:

남은 연휴 잘 보내세요~~
![image](https://github.com/woowacourse/android-paint/assets/88770426/01ea0996-8ac9-4a18-8774-8294ddd8a86d)

2023-10-02 16:02 UTC, hyunji1203 commented on app/src/main/java/woowacourse/paint/PaintingView.kt
> +        isFocusableInTouchMode = true
오 저런 역할을 하는 코드였군요?!
저도 우기 덕분에 해당 코드에 대해 더 알아가볼 수 있었네요!
참고 자료까지 첨부해주시다니 잘 받아먹겠습니다ㅎㅎㅎ👍

2023-10-03 08:19 UTC, hyunji1203 requested changes
우기 리뷰 반영한거 잘 봤습니다!
점이 찍힐 수 있도록 Line이라는 객체를 만들어 진행하신게 인상 깊었어요👍
이번엔 큰 수정 요구 사항은 없고 궁금한 부분이나 간단한 코멘트 위주로 달았습니다! 
확인해주시고 리뷰요청 해주시면 담번엔 바로 merge 하도록 하겠습니다!

2023-10-03 08:19 UTC, hyunji1203 commented on app/src/main/java/woowacourse/paint/MainActivity.kt
> +                getColor(R.color.blue),
해당 color들을 enum으로 관리해도 좋을 것 같아요! 물론 이건 제 생각이니 우기 취향대로 반영 안하셔도 됩니다!ㅎㅎㅎ

2023-10-03 08:19 UTC, hyunji1203 commented on app/src/main/java/woowacourse/paint/Line.kt
> +        get() = PathMeasure(path, false).length
```suggestion
val length: Float = PathMeasure(path, false).length
```
위와 같이 수정해도 똑같이 동작이 되던데, get을 쓰신 이유가 무엇인가요? 정말 순수 100% 궁금해서 물어봅니다!😄

2023-10-03 08:19 UTC, hyunji1203 commented on app/src/main/java/woowacourse/paint/PaintingView.kt
> +                        Line.dot(x, y, brush)
점을 찍는 방법이 이런 방법도 있네요👍 많이 배워갑니다👍

2023-10-03 08:19 UTC, hyunji1203 commented on app/src/main/res/layout/activity_main.xml
> +        <com.google.android.material.slider.RangeSlider
이건 저도 다른 분들 리뷰를 보고 알게 된 아이 인데 `stepSize="2"` 라는 속성을 xml에서 써주면 rangeSlider의 크고 작아지는 단위(?)를 조절할 수 있다 그러더라고요! 언젠간 쓸날이 오면 써보는걸로ㅎㅎ

2023-10-05 07:30 UTC, boogi-woogi commented on app/src/main/java/woowacourse/paint/MainActivity.kt
> +                getColor(R.color.blue),
이 부분에 대해선 신경을 쓰지 않고 있었는데 감사합니다~

2023-10-05 07:30 UTC, boogi-woogi commented on app/src/main/java/woowacourse/paint/Line.kt
> +        get() = PathMeasure(path, false).length
뽀또가 제시해주신 방법으로 생성하는게 적합합니다!! 
생성된 Line 객체의 length가 가변적이라고 생각했는데 온전히 제 실수입니다ㅎㅎ

2023-10-05 07:31 UTC, boogi-woogi commented on app/src/main/res/layout/activity_main.xml
> +        <com.google.android.material.slider.RangeSlider
감사합니다~~ 미션 진행하면서 쓸 기회가 있다면 적용해보겠습니다!

2023-10-05 07:38 UTC, boogi-woogi commented
항상 좋은 리뷰 남겨주셔서 감사합니다:thumbsup:

머지해주시면 다음 단계 빠르게 진행해보도록 하겠습니다ㅎㅎ

내일이면 캠퍼스로 다시 등교를 시작하는데 오늘 하루 마무리 잘하시구 다음 단계도 화이팅입니다:smile:

2023-10-05 07:43 UTC, boogi-woogi commented
뽀또 항상 좋은 리뷰 남겨주셔서 감사합니다:+1:

내일이면 캠퍼스로 다시 등교를 시작하는데 오늘 하루 마무리 잘하시구 다음 단계도 화이팅니다:+1:

2023-10-05 15:42 UTC, hyunji1203 approved these changes
우기!!! 이번 1단계 미션 너무 고생많았어요!
우기도 낼부터 다시 시작되는 캠퍼스 등교 화이팅하시고💪, 그럼 이만 이번 단계 merge 하겠습니다!
앞으로 남은 미션도 화이팅!!👍

2023-10-05 15:42 UTC, merged