[뽀또] 뷰 챌린지 미션 2단계 제출합니다.
woowacourse/android-paint pull request #41
Opened 2023-10-09 22:49 UTC by hyunji1203

베뤼이이이🍓 안녕하세요!
이번 2단계 미션에서 다시 찾아뵙게 되었네요😎
저번 1단계 때 베리의 리뷰 덕에 야무지고 보람찬 햅삐햅삐햅삐 미션이였습니다 후후..
2단계 미션도 잘 부탁드리고! 베리 리뷰 야무지게 받아먹을 준비가 되어있으니 부담없이 리뷰 막막 해주세요!

요구사항은 아래와 같이 취소, 재실행 기능을 제외하고 구현하였습니다!

## 요구 사항
### 기능 요구 사항
- [x] 화면에 사각형, 원 모양을 그릴 수 있도록 구현한다.
    - [x] 사용자가 자유롭게 크기나 위치를 조정할 수 있다.
- [x] 특정 영역의 요소를 지울 수 있는 지우개를 구현한다.
- [x] 브러쉬(펜, 사각형, 원, 지우개) 종류를 자유롭게 선택해서 그릴 수 있다.

### 선택 요구 사항
- [x] 전체 그림을 지우는 기능을 추가한다.
- [ ] 취소(undo), 재실행(redo)을 구현한다.

## 구현 설명
- brush의 type 별로 class를 나누어 구현하였습니다. (Circle, Rectangle, Line, Eraser) 
- 지우개는 `xfermode`를 활용해 구현하였습니다.
- 전체 그림 초기화는 paintings 객체를 활용해, 해당 클래스가 포함하고 있는 컬렉션이 clear되도록 구현하였습니다.

## 시연영상
영상도 첨부합니다~🍓

<img width="315" src="https://github.com/woowacourse/android-paint/assets/83613106/cb28089f-e1b9-45ca-aa61-a187554c3f44"/>

2023-10-10 06:41 UTC, woowahan-leah commented on app/src/main/java/woowacourse/paint/ui/CustomView.kt
> +    private var brushType = LINE
각각 따로 관리될 필요가 있을까요?

2023-10-10 19:02 UTC, whk06061 requested changes
안녕하세요 뽀또 😊🍪
2단계 미션 잘 구현해주셨습니다! 
BrushType 에 대한 추상화가 잘 이루어져서 코드의 가독성이 좋았어용 ㅎㅎ 👍
궁금한 점과 수정하면 좋을 점 코멘트 남겼으니 확인하시고 다시 리뷰요청 주세요 🍪🍪

2023-10-10 19:02 UTC, whk06061 commented on app/src/main/java/woowacourse/paint/ui/CustomView.kt
>  class CustomView(context: Context, attrs: AttributeSet) : View(context, attrs) {
CustomView 보다 더 명시적인 이름을 사용해볼까요~?

2023-10-10 19:02 UTC, whk06061 commented on app/src/main/java/woowacourse/paint/ui/CustomView.kt
> +                doActionUp(pointX, pointY)
추상화를 잘해주셔서 코드가 간편하고 좋네요오

2023-10-10 19:02 UTC, whk06061 commented on app/src/main/java/woowacourse/paint/ui/CustomView.kt
> +        brushType = ERASER
브러쉬 종류가 늘어나면 코드가 계속 늘어날 것 같네요! 중복 로직이 보이는데 추상화할 수 있을 것 같아요!

2023-10-10 19:02 UTC, whk06061 commented on app/src/main/java/woowacourse/paint/ui/CustomView.kt
> +        setLayerType(LAYER_TYPE_HARDWARE, null)
이 코드는 어떤 역할을 하는건가요?! 궁금..ㅎㅎ

2023-10-10 19:02 UTC, whk06061 commented on app/src/main/java/woowacourse/paint/ui/brushtype/Circle.kt
> +    }
모든 brushType 에서 페인트를 설정해주는 함수를 따로 가지고있게 하셨네요!
커스텀뷰에서 패쓰, 페인트를 공유하면 아래 코드가 불필요하여 코드량이 줄어들 것 같은데 뽀또의 의견은 어떤가요? 제가 놓쳤던 뽀또의 의도가 있었다면 알려주세요 ㅎㅎ
```kotlin
override fun setStrokeWidth(width: Float) {
        paint.strokeWidth = width
    }

  override fun setStrokeColor(color: Int) {
      paint.color = color
  }
```

2023-10-10 19:02 UTC, whk06061 commented on app/src/main/java/woowacourse/paint/ui/CustomView.kt
> +                setupCircle()
터치를 뗐을 때 마다 brush 를 해당 brushType 으로 다시 설정해주는 이유가 뭔가용?!

2023-10-10 19:02 UTC, whk06061 commented on app/src/main/java/woowacourse/paint/ui/brushtype/Circle.kt
> +    }
오,,,해당 로직을 BrushType 이 가지고 있도록 캡슐한거 좋네요!! 👍

2023-10-10 19:02 UTC, whk06061 commented on app/src/main/java/woowacourse/paint/ui/MainActivity.kt
>                  listOf(
저두 반달한테 배웠는데 리소스를 [TypedArray](https://developer.android.com/guide/topics/resources/more-resources?hl=ko#TypedArray) 을 사용하여 관리하는 방법도 있다고 합니다 !! 참고만 해주세용 ㅎㅎ

2023-10-11 08:56 UTC, hyunji1203 commented on app/src/main/java/woowacourse/paint/ui/CustomView.kt
> +                setupCircle()
하핫 구현 도중에 잘 못 생각한 부분이 있었습니다.
현재는 아예 brushtype을 각각의 brush 객체에서 갖고 있도록 수정하였기 때문에 해당 코드들은 싹 사라졌습니다!

2023-10-11 08:57 UTC, hyunji1203 commented on app/src/main/java/woowacourse/paint/ui/CustomView.kt
> +    private var brushType = LINE
레아가 남겨주신 리뷰를 보고 따로 관리될 필요가 없다는 것을 깨달았습니다!
따라서 현재는 타입을 각각의 brush안에서 갖고 있어 한번에 관리될 수 있도록 수정하였습니다!

2023-10-12 11:32 UTC, hyunji1203 commented on app/src/main/java/woowacourse/paint/ui/CustomView.kt
> +        brushType = ERASER
넵! 중복 코드 제거 하였습니다!

2023-10-12 11:34 UTC, hyunji1203 commented on app/src/main/java/woowacourse/paint/ui/CustomView.kt
>  class CustomView(context: Context, attrs: AttributeSet) : View(context, attrs) {
`PaintingPaper` 로 이름 변경하였습니다!

2023-10-12 11:58 UTC, hyunji1203 commented on app/src/main/java/woowacourse/paint/ui/CustomView.kt
> +        setLayerType(LAYER_TYPE_HARDWARE, null)
지우개 브러쉬가 검은색으로 보이길래 해당 코드를 추가해 지우개가 잘 작동되도록 설정해준 것 입니다!

2023-10-12 11:59 UTC, hyunji1203 commented on app/src/main/java/woowacourse/paint/ui/MainActivity.kt
>                  listOf(
오! 이런 방법이 있었군요! 바로 적용해줬습니다! 알려주셔서 감사합니당 붸리🍓

2023-10-12 20:11 UTC, hyunji1203 commented on app/src/main/java/woowacourse/paint/ui/brushtype/Circle.kt
> +    }
오 너무 좋은 생각인데요??!!!👍🍓
베리의 리뷰처럼 커스텀뷰에서 패스와 페인트를 공유하면 불필요한 코드를 줄일 수 있어 좋다고 생각합니다!

여기서 추가적으로 제가 생각했던 부분이 있는데,
각각의 브러쉬 클래스들을 각각 패스와 페인트를 갖고 있는 하나의 완벽한 객체(캡슐화 시키기 위해!)로 만들고 싶다는 생각이 들었습니다!
따라서 패스와 페인트는 각각의 클래스에 존재한채로 해당 불필요한 코드들이 제거될 수 있는 방향으로 코드를 수정하였습니다!
베리의 리뷰에 추가적으로 제 생각을 더해 수정한 코드이기 때문에, 이런 식으로 반영한 부분에 대해 베리의 의견이 궁금합니다ㅎㅎㅎ🤩

2023-10-12 20:29 UTC, hyunji1203 commented
베리ㅣ리리릴~~~~🍓
베리 리뷰 반영하면서 새롭게 배울 수 있었던 것도 있었고 어떻게 하면 더 나은 구조가 될 수 있는지 생각해볼 수 있어서 너무 좋았어요!
이번 리뷰 반영하면서 중점적으로 다뤘던 부분은, 중복되는 코드를 줄이는 것에 집중해 리팩토링을 진행했습니당
항상 리뷰 너무 감솨합니당😘

2023-10-13 06:15 UTC, whk06061 commented on app/src/main/java/woowacourse/paint/ui/brushtype/Circle.kt
> +    }
오 좋습니당 ㅎㅎ 뽀또가 구현한 것 처럼 각 클래스들의 자신만의 패쓰와 페인트를 가지고 있으면 유지보수가 더 수월해질 것 같네요 👍

2023-10-13 06:24 UTC, whk06061 approved these changes
뽀또 리뷰 반영하느라 고생하셨습니다! ㅎㅎ
코드가 엄청 깔끔해졌네요! 👍
고민해볼만한 부분 한가지를 남겨두었는데 다음 단계에서 같이 반영해주세요!
이번 단계는 이만 머지할게요~🍪

2023-10-13 06:24 UTC, whk06061 commented on app/src/main/java/woowacourse/paint/ui/brushtype/BrushType.kt
> +    var type: BrushType
BrushType 이 type 정보를 또 따로 가지고 있어야될까요? BrushType 그 자체로 타입이 구분되도록 할 수 있을 것 같아요!

2023-10-13 06:24 UTC, merged

2023-10-13 08:53 UTC, hyunji1203 commented on app/src/main/java/woowacourse/paint/ui/brushtype/BrushType.kt
> +    var type: BrushType
step3 진행하면서 해당 부분도 같이 수정하겠습니당 베리 쵝오 뽀뽀쪽😘

2023-10-13 09:18 UTC, whk06061 commented on app/src/main/java/woowacourse/paint/ui/brushtype/BrushType.kt
> +    var type: BrushType
오늘따라 사랑이 넘치는ㅌㅋㅋㅋㅋㅋㅋㅋㅋㅋ뽀또 코드 보면서 저두 많이 배웠써용❤️❤️❤️ 3단계두 화이팅 뽀뽀😘😘