[멧돼지] 뷰 챌린지 미션 2단계 제출합니다.
woowacourse/android-paint pull request #46
Opened 2023-10-10 13:17 UTC by 2chang5

핀치줌을 계속 시도해보았지만 멀티터치 + 드래그 + 핀치줌은 보정해줘야하는 값이 너무 많아서 시간이 무한정 들것 같아 일단 보류시켰습니다.
가장 기본적인 방법을 통해서 빠르게 구현해보았는데 글로의 소중한 리뷰가 필요합니다.

2023-10-11 13:33 UTC, ippnsj requested changes
수고했어요 멧돼지! 🐗
멧돼지 덕분에 action과 actionMasked의 차이도 알아보고 새로운 지연초기화 방법도 공부해볼 수 있었어요! 😆
다중 터치 이벤트를 감지해서 처리하셨던데 대단합니다! 👍
리뷰 몇 가지 남겼는데 궁금한 점이 있으면 언제든 DM 주세요! 😉

2023-10-11 13:33 UTC, ippnsj commented on app/src/main/java/woowacourse/paint/board/PaintBoard.kt
> +        }
!! 대신 let을 사용해보는건 어떤가요?

2023-10-11 13:33 UTC, ippnsj commented on app/src/main/java/woowacourse/paint/board/PaintBoard.kt
>      private var currentStrokeWidth: Float = 10f
저번에 관련해서 리뷰드렸는데 아직 멧돼지의 답변을 듣지 못했는데 듣고 싶어서 이전 PR에서 남긴 리뷰 링크 남깁니다~!
[이전 PR 리뷰](https://github.com/woowacourse/android-paint/pull/25#discussion_r1349655391)

2023-10-11 13:33 UTC, ippnsj commented on app/src/main/java/woowacourse/paint/board/draw/Oval.kt
> +            MotionEvent.ACTION_UP -> drawOval(pointX, pointY)
두 분기를 합칠 수 있을 것 같아요!

2023-10-11 13:33 UTC, ippnsj commented on app/src/main/java/woowacourse/paint/board/draw/Rectangle.kt
> +            MotionEvent.ACTION_UP -> drawRect(pointX, pointY)
이 둘도 하나로 합칠 수 있겠네요!

2023-10-11 13:33 UTC, ippnsj commented on app/src/main/java/woowacourse/paint/board/PaintBoard.kt
> +        }
Tool과 GraphicObjectType을 분리하면서 when 분기 처리가 두 번 일어나고 있다는 생각이 드는데 이 둘을 분리한 이유가 궁금해요~!

2023-10-11 13:33 UTC, ippnsj commented on app/src/main/java/woowacourse/paint/board/PaintBoard.kt
> +        eraseMode = true
eraseMode인지 아닌지 구분하는 것은 PaintBoard의 책임일까요? 🤔

2023-10-11 13:33 UTC, ippnsj commented on app/src/main/java/woowacourse/paint/board/PaintBoard.kt
> +            GraphicObjectType.OVAL -> getOvalInstance()
when절 없이도 가능한 방법이 있는데 고민해보면 좋을 것 같아요!

2023-10-11 13:33 UTC, ippnsj commented on app/src/main/java/woowacourse/paint/board/PaintBoard.kt
> +            GraphicObjectType.OVAL -> getOvalInstance()
제가 안드로이드 잡담-질답 방에 남긴 질문과도 연관이 있답니다~ㅎㅎ

2023-10-12 01:58 UTC, 2chang5 commented on app/src/main/java/woowacourse/paint/board/draw/Oval.kt
> +            MotionEvent.ACTION_UP -> drawOval(pointX, pointY)
이 부분은 각 상황에서 어떻게 대응할건지 명시적으로 보여주고싶어서 같은 일을 하고있어도 나눠서 작성하였습니다.
또한 조금만 복잡해져도 충분히 로직이 변경될수도 있다고 생각해서요ㅎㅎㅎ

2023-10-12 01:59 UTC, 2chang5 commented on app/src/main/java/woowacourse/paint/board/draw/Rectangle.kt
> +            MotionEvent.ACTION_UP -> drawRect(pointX, pointY)
이 또한 마찬가지입니다.

2023-10-12 02:03 UTC, 2chang5 commented on app/src/main/java/woowacourse/paint/board/PaintBoard.kt
> +        }
이 부분에대해서 저도 현재 비슷해보여서 합칠까 고민도 했는데 Tool 은 GraphicObjectType 보다 넓은 영역으로 잡았습니다. 물론 지금은 요구사항에 없기 때문에 생략한 Bitmap image라던지 Drawable 을 지원한다면 이는 Tool에만 추가될것입니다.
 GraphicObjectType은 그야말로 손으로 그리는 도형만을 뜻합니다.

2023-10-12 02:57 UTC, 2chang5 commented on app/src/main/java/woowacourse/paint/board/PaintBoard.kt
>      private var currentStrokeWidth: Float = 10f
이 부분에 대해서 글로의 의견이 맞다고 생각해서 맞춰서 수정하였습니다.

2023-10-12 02:57 UTC, 2chang5 commented on app/src/main/java/woowacourse/paint/board/PaintBoard.kt
> +        eraseMode = true
수정하였습니다.

2023-10-12 03:07 UTC, 2chang5 commented on app/src/main/java/woowacourse/paint/board/PaintBoard.kt
> +            GraphicObjectType.OVAL -> getOvalInstance()
이 부분에 대해서 저도 로직을 옮길까 생각을 많이하고 로직을 각 도형 내부로 이동시킬까 생각했지만 
현재 이 부분은 도형 자체의 책임이라기 보다는 PaintBoard를 구현하면서 나타난 범용적이지 않은 드래그, 핀치줌을 동시 구현하기위해 생성된 로직이라 객체 내부에 존재하는  것보다 PaintBoard 에 남아서 분기처리하는게 적절하다고 생각합니다.
-> currentGraphicObject은 드래그를 적용하면서 생긴 상태값이기 때문에 드래그가 없다면 사실 필요없는 상태값이며
이러한 특수한 구현을 일반적으로 사용할 수 있는 도형에 적용하는것은 오히려 객체의 자율성을 깨고 서로 물고물리는 관계를 형성한다고 생각합니다.

2023-10-12 06:06 UTC, ippnsj commented on app/src/main/java/woowacourse/paint/board/PaintBoard.kt
> +        }
GraphicObject가 있어서 사실 GraphicObjectType의 역할이 모호하다고 생각하긴 했어요~!
저도 멧돼지의 의견처럼 Tool과 GraphicObject는 분명 차이가 있다고 생각합니다! 😉

2023-10-12 06:12 UTC, ippnsj approved these changes
수고했어요 멧돼지! 🐗
3단계도 화이팅입니당! 😆

2023-10-12 06:34 UTC, merged