[우기] 뷰 챌린지 미션 3단계 제출합니다.
woowacourse/android-paint pull request #54
Opened 2023-10-12 11:06 UTC by boogi-woogi

안녕하세요 뽀또~ 선택요구 사항을 제외하고 3단계는 간단하게 구현해보았습니다ㅎㅎ

먼저 저는 반응형 ui를 구성하기 위해서 여러 dimens.xml 파일을 구성해보았습니다!

dimens파일을 화면 크기별로 나누는 것만으로도 "정말 될까?" 라는 궁금증이 있었고 그것을 해소하기 위해 이 방법을 선택했습니다~

그리고 다크 모드의 대응을 위해 일반, 그리고 다크 모드를 위한 color를 따로 정의했습니다!
![image](https://github.com/woowacourse/android-paint/assets/88770426/c1954f1f-a55a-41da-93f5-c21bb86c6017)
![image](https://github.com/woowacourse/android-paint/assets/88770426/1dd5e17f-5e60-43f8-b64d-a6d269bc6d4c)

2023-10-14 11:08 UTC, hyunji1203 requested changes
우기!! 3단계도 고생많으셨어요!
dimen을 활용해 구현 잘 해주셨더라고요👍
전반적으로 구현 잘 해주셨는데 딱 한가지 필수 기능 요구사항 중 하나를 빼놓은게 있습니다!
`구현 예시를 참고하여 다크모드 전환 시 그림판 보드의 색상과 상태바 색상이 검은색으로 바뀌어야 한다.`
라는 요구사항이 아직 지켜지지 않은 것 같아 이것까지 구현해주시면 될 것 같습니다!ㅎㅎ

2023-10-14 11:08 UTC, hyunji1203 commented on app/src/main/res/layout/activity_main.xml
> +            android:layout_width="0dp"
ConstraintLayout으로 변경 후 0dp 신경 써서 맞춰주신거 👍!!

2023-10-16 06:57 UTC, boogi-woogi commented
헉 뽀또 죄송합니다,,, 조금 더 꼼꼼히 확인했어야 했는데 ㅠㅠ 

다크 모드에서까지 수정완료했습니다ㅎㅎ

우테코 마지막 미션의 마지막 step에서까지 자세하게 봐주셔서 감사합니다🙇‍♂️🙇‍♂️

2023-10-16 14:49 UTC, hyunji1203 approved these changes
우기!!! 너무 고생많으셨어요!
벌써 우기의 마지막 미션의 마지막 단계를 머지할 시간이 다가왔네요..!
마지막 미션 마지막 단계까지 잘 구현해주셔서 **역시 우기~**를 한번 더 외치게 됩니다ㅎㅎㅎ

앞선 우테코 9개월 동안 정말 고생 많으셨고,,,
앞으로 다가올 최종 데모데이 및 레벨5, 그리고 우테코의 마지막까지 우리 화이팅합시다!!💪
그럼 이만 찐 마지막 머지하도록 하겠습니다. 수고하셨습니다👍

2023-10-16 14:49 UTC, merged

2023-10-17 01:05 UTC, boogi-woogi commented
뽀또도 정말 고생하셨고 남은 기간도 화이팅입니다!!💪💪

마지막에는 꼭 원하는 결과 얻으실 수 있을거에요 ㅎㅎ