[예니] 뷰 챌린지 미션 1단계 제출합니다.
woowacourse/android-paint pull request #78
Opened 2024-09-30 11:38 UTC by JoYehyun99

안녕하세요 심지 🙌 
이번 뷰 챌린지 미션 잘 부탁드립니다!

<img width ="250" src = "https://github.com/user-attachments/assets/6cbd7981-c471-4055-af14-44a0fa2298e1" />

2024-10-01 03:22 UTC, sh1mj1 requested changes
수고 많으셨습니다!
현재 요구사항도 단순하고, 딱히 고쳐야 할 부분도 없어 보이네요.

질문 남겨두었는데 천천히 생각하시고 답변 부탁드립니다!
코드 수정이 필요없어보이시면 답변만 주시고 다시 미션 제출해주셔도 됩니다!

2024-10-01 03:22 UTC, sh1mj1 commented on app/src/main/java/woowacourse/paint/DrawingView.kt
> +        isFocusableInTouchMode = true
이 코드가 있어야 하는 이유가 궁금합니다
없어도 제대로 동작하네요!

2024-10-01 03:22 UTC, sh1mj1 commented on app/src/main/res/drawable/shape_oval.xml
이것을 통해 색 선택할 때 동그랗게 만드신 거군요~ 예쁘네요 👍👍👍👍

2024-10-01 03:22 UTC, sh1mj1 commented on app/src/main/java/woowacourse/paint/PaletteViewHolder.kt
> +        val targetColor = ContextCompat.getColor(binding.root.context, color.colorRes)
ContextCompat 을 통해 다양한 안드로이드 버전에서도 색상을 잘 선택할 수 있겠군요~

2024-10-01 03:22 UTC, sh1mj1 commented on app/src/main/java/woowacourse/paint/DrawingView.kt
> +        val DEFAULT_STROKE_COLOR = PaletteColor.RED
이건 private 이어도 될 것 같군용

2024-10-01 03:22 UTC, sh1mj1 commented on app/src/main/java/woowacourse/paint/DrawingView.kt
> +    @SuppressLint("ClickableViewAccessibility")
수업 때 이거 보고 예니 생각이 났어요 ㅋㅋ

2024-10-01 03:22 UTC, sh1mj1 commented on app/src/main/java/woowacourse/paint/DrawingView.kt
> +    }
저는 미션하면서 이 코드에 대해 의문점이 있었어요  
이런 식으로 onDraw 때마다 lines 에 있는 line 들을 계속해서 canvas.drawPath 해도 괜찮을걸까요?

코드로만 보면 이미 선을 그린 곳이 다른 곳에 선을 그릴 때마다 점점 색이 진해져야 하는 것처럼 보이지는 않나요?

2024-10-01 03:22 UTC, sh1mj1 commented on app/src/main/java/woowacourse/paint/MainActivity.kt
> +    private val adapter by lazy { PaletteAdapter(PaletteColor.getAllColors(), this) }
`PaletteColor.entries` 로도 사용할 수 있지 않나요?

2024-10-01 05:31 UTC, JoYehyun99 commented on app/src/main/java/woowacourse/paint/MainActivity.kt
> +    private val adapter by lazy { PaletteAdapter(PaletteColor.getAllColors(), this) }
그렇죠,,,! 굳이 메서드를 정의할 필요는 없었네요 ㅎㅎ

2024-10-01 05:48 UTC, JoYehyun99 commented on app/src/main/java/woowacourse/paint/DrawingView.kt
> +        isFocusableInTouchMode = true
사실,,, 그냥 강의 자료 코드를 그대로 가져와서 생긴 코드인데요,,, 🥹 
조금 찾아보니 포커스 관련 설정을 위한 코드 같은데, 현재 미션 구현에서는 필요해보이진 않아서 삭제하겠습니다~

2024-10-01 06:04 UTC, JoYehyun99 commented on app/src/main/java/woowacourse/paint/DrawingView.kt
> +    }
저는 `onDraw`는  초기화된 캔버스를 받아서 그림을 그리는 친구로 이해하기로 했습니닷
저도 처음에는 이러한 로직이 굉장히 비효율적인 것 처럼 느껴지긴 했습니다 🤔
그리기 이벤트가 생길 때마다 `onDraw`를 통해 처음부터 다시 그린다니,,,!!🫢

2024-10-02 04:20 UTC, sh1mj1 commented on app/src/main/java/woowacourse/paint/DrawingView.kt
> +    }
넵 저도 찾아보니 그렇다고 하더라구요

나중에 필요하다면 추가적인 최적화를 고려할 수도 있겠네요
예를 들어, 선분을 간소화하거나, 일정 수 이상의 선을 그릴 때 이전 선들을 비트맵에 통합할 수도 있을 것 같아요.

2024-10-02 04:21 UTC, sh1mj1 approved these changes
수고 많으셨습니다~
다음 미션 바로 진행하면 될 것 같아요

저도 미션 진행하며 공부하면서 추가적으로 피드백할 수 있도록 하겠습니다.
👍👍👍👍

2024-10-02 04:25 UTC, merged