[베리] 뷰 챌린지 미션 1단계 제출합니다.
woowacourse/android-paint pull request #8
Opened 2023-09-28 15:06 UTC by whk06061

안녕하세요 반달! 🌛
추석 잘 보내고 계신가요~? step4 마지막 미션에서 만나뵙게 되어 반갑습니다~!
미션 1단계 리뷰 요청 보냅니다!
제가 짠 코드의 구조는 다음과 같습니다

---
### CustomCanvas
그림이 그려지는 커스텀 클래스입니다.
### PathPaint
그린 경로와 브러쉬 정보를 data class 로 묶어주었습니다.
### PathHistory
현재까지 그린 그림이 기록될 리스트를 일급 컬렉션으로 감싸주었습니다.

---

추석 연휴 즐겁게 보내세요! 리뷰는 연휴 즐기고 천천히 해주셔도 됩니당 🤗

2023-09-28 17:42 UTC, no1msh requested changes
<img src="https://github.com/woowacourse/android-paint/assets/22425650/c5327040-2429-43dc-ab95-e74959f54823" width="40%">

---

안녕하세요! 베리🍓 ㅋㅋㅋ 잘 구현해주셨습니다. 궁금한점이나 약간은 개선할 점에서 대해서 리뷰해보았습니다! 
확인 해보시구 다시 리뷰요청 주세요~😆

2023-09-28 17:42 UTC, no1msh commented on app/src/main/java/woowacourse/paint/CustomCanvas.kt
> +class CustomCanvas(context: Context, attrs: AttributeSet) : View(context, attrs) {
지금은 오직 xml 상에서만 베리의 `CustomCanvas`를 사용할 수 있어요.
동적 생성을 지원하기 위해선 어떻게 해야할까요? 😆

2023-09-28 17:42 UTC, no1msh commented on app/src/main/res/layout/activity_main.xml
> +    </androidx.constraintlayout.widget.ConstraintLayout>
베리~ 그림 그리는데 집중하고 싶은데 컬러선택, 굵기 선택하는 도구들이 거슬려서 못그리겠어요😭
visibility 처리 해주세요 😎

2023-09-28 17:42 UTC, no1msh commented on app/src/main/res/layout/activity_main.xml
> +            app:layout_constraintBottom_toBottomOf="parent" />
이번미션 요구사항만 보면 컬러가 5개밖에 없는데 왜 스크롤뷰가 아닌 리사이클러뷰로 구현 하셨나요?
재활용될거 같지 않아보이는데요?!
틀렸다는게 아니라 베리의 생각💡을 자유롭게 적어주세요~

2023-09-28 17:42 UTC, no1msh commented on app/src/main/res/layout/activity_main.xml
> +            android:adapter="@{adapter}"
리사이클러뷰의 어댑터를 binding expression으로 지정해주셨네요.
액티비티에서 하지 않고 xml에서 지정해준 이유는 무엇인가요? 베리의 의견이 궁금합니다. 🍓

2023-09-28 17:42 UTC, no1msh commented on app/src/main/java/woowacourse/paint/MainActivity.kt
> +        binding.mainRangeSlider.valueTo = 100.0f
사실 이 부분은 xml 상에서 지정이 가능합니다. 😎

하지만 여기서 생각해봐야할 것은 `과연 어떨 때 값을 xml에서 지정해주는게 좋고 어떨 때 액티비티 or 프래그먼트 등 에서 지정해주는게 좋을까?`입니다.

베리🍓의 기준이 궁금합니다. 🧐

2023-09-28 17:42 UTC, no1msh commented on app/src/main/java/woowacourse/paint/MainActivity.kt
> +            R.color.red, R.color.orange, R.color.yellow, R.color.green, R.color.blue
**이미 지정되어있는 컬러들**을 다루고 있네요. 조금더 편리하게 다룰 순 없을까요? 😁

지금 상황에서는 저 색깔들이 필요할 때 마다 일일이 다 불러와야 하는 불편함이 있습니다. 😢

2023-09-28 17:42 UTC, no1msh commented on app/src/main/res/values/palettecolors.xml
> +</resources>
오 좋은 분리 👍

추가로 이렇게 관리하는 방법도 있습니다.
[TypedArray](https://developer.android.com/guide/topics/resources/more-resources?hl=ko#TypedArray)

2023-10-02 10:35 UTC, whk06061 commented on app/src/main/java/woowacourse/paint/CustomCanvas.kt
> +class CustomCanvas(context: Context, attrs: AttributeSet) : View(context, attrs) {
헉 제가 놓쳤던 부분 짚어주셔서 감사합니다! 🤗

- xml 에서 생성할 때
`CustomCanvas(context:Context, attrs:AttributeSet)`
이 생성자는 xml 상에서 뷰를 inflate 할 때 사용됩니다. xml 파일에서 지정된 속성을 이용하여 뷰를 생성하게 됩니다.

- 코드 상에서 동적으로 생성할 때
`CustomCanvas(context:Context)`
그러나 코드상에서 동적으로 생성을 할 때는 단순히 context 만 필요하기 때문에 위와 같은 생성자가 필요합니다.

따라서 반달 말대로 동적 생성 또한 지원하기 위해서 attrs 의 디폴트값을 null 로 설정해주었습니다!

2023-10-02 10:45 UTC, whk06061 commented on app/src/main/res/layout/activity_main.xml
> +            app:layout_constraintBottom_toBottomOf="parent" />
스크롤뷰를 사용하게 되면 xml 에 컬러칩 뷰들이 여러 개 생기게 되는데, 만약 색깔이 많아진다면 유지보수성하기 힘들 것 같아 리스트뷰나 리사이클러뷰를 고려하게 되었습니다!

그리고 둘 중에 고민하다가 처음엔 ListView 를 사용하려고 했는데 추후에 여러 색깔들이 추가될 수도 있겠다는 생각이 들어 효율성을 위해 RecyclerView 를 사용해주었습니다!

2023-10-02 10:46 UTC, whk06061 commented on app/src/main/res/layout/activity_main.xml
> +            android:adapter="@{adapter}"
저는 최대한 Activitiy 의 코드를 줄이기 위하여 xml 에서 설정할 수 있는 속성값들은 xml 에서 지정해주고 있습니다!

2023-10-02 11:01 UTC, whk06061 commented on app/src/main/java/woowacourse/paint/MainActivity.kt
> +        binding.mainRangeSlider.valueTo = 100.0f
반달 덕분에 xml 에서 지정 가능하다는 사실을 배웠네요!🤗

저는 액티비티나 프래그먼트의 코드를 줄이기 위하여 
xml 에서 설정할 수 있는 속성값들은 모두 xml 에서 설정하여 처리하는 편입니다!!

2023-10-02 15:40 UTC, whk06061 commented on app/src/main/res/layout/activity_main.xml
> +            android:adapter="@{adapter}"
위와 같은 경우에는 굳이 data binding 을 사용하지 않고 액티비티에서 뷰바인딩만을 활용하여 설정해주는 것이 더 간단하겠네요!

2023-10-02 15:41 UTC, whk06061 commented on app/src/main/res/values/palettecolors.xml
> +</resources>
오 색상 값을 한번에 불러오는 방법이 필요했는데 TypedArray 를 사용하는 방법이 있었네요! 감사합니다 반달🤗

2023-10-02 18:33 UTC, whk06061 commented on app/src/main/res/layout/activity_main.xml
> +    </androidx.constraintlayout.widget.ConstraintLayout>
반달의 소원 이뤄드렸습니다 😎

2023-10-02 18:46 UTC, DYGames commented on app/src/main/java/woowacourse/paint/CustomCanvas.kt
> +class CustomCanvas(context: Context, attrs: AttributeSet? = null) : View(context, attrs) {
Custom View 클래스에 Custom 이라는 네이밍이 필요할까요~?
Button, EditText 등 안드로이드 기본 제공 커스텀뷰를 생각해봅시다~!

2023-10-02 19:13 UTC, whk06061 commented
반달의 정성스러운 리뷰 감사합니다 ~
반달의 바램대로 버튼을 클릭했을 때 색상, 크기 조절 뷰의 visibility 를 처리했습니다.
액티비티 코드에 뷰 조작 로직이 있는 것이 마음에 안들어 뷰모델에 책임을 전가시켰습니다.
그래서 일단 뷰모델에는 뷰 visibility 처리 코드만 있습니다~(그림 저장은 2단계에서 미션으로 나올 것 같아서 아직 😚)

2023-10-02 19:15 UTC, whk06061 commented
반달의 정성스러운 리뷰 감사합니다 ~
반달의 바램대로 더 넓은 세상에서 그림을 그릴 수 있도록 수정해주었습니다😎
액티비티 코드에 뷰 visibility조작 로직이 있는 것이 마음에 안들어 뷰모델에 책임을 전가시켰습니다.
그래서 일단 뷰모델에는 뷰 visibility 처리 코드만 있습니다~(그림 저

2023-10-02 19:19 UTC, whk06061 commented on app/src/main/java/woowacourse/paint/CustomCanvas.kt
> +class CustomCanvas(context: Context, attrs: AttributeSet? = null) : View(context, attrs) {
리뷰 남겨주셔서 정말 감사합니다! 반영했습니다 😎

2023-10-03 16:47 UTC, no1msh requested changes
베리 🍓피드백 반영 고생많으셨습니다. ㅎㅎ

몇가지 리뷰 남겨드렸으니 확인해보시구 다시 리뷰요청 해주세요!

이것 까지만 하고 다음 리뷰요청은 머지하겠습니다! 화이팅!😆

2023-10-03 16:47 UTC, no1msh commented on app/src/main/java/woowacourse/paint/Canvas.kt
> +class Canvas(context: Context, attrs: AttributeSet? = null) : View(context, attrs) {
`Default Value`로 코드를 간결하게 만드신 점 너무 좋습니다!😆
다만 지금 상황으론 java에서 사용할 때 문제가 있습니다. default value 관련 문제인데요.
이해가 힘들실 수 있을 거 같아 예시코드와 함께 설명해보겠습니다.

이런 코틀린 클래스가 있다고 가정하고 
![image](https://github.com/woowacourse/android-paint/assets/22425650/cc31fa5a-7c54-4234-9c76-88a526af06a9)

다음과 같이 자바에서`maxSpeed`에 defaultValue가 들어가길 기대하면서 사용하면 에러가 납니다.
![image](https://github.com/woowacourse/android-paint/assets/22425650/37994165-f449-4bb9-aad5-695f223db2af)

하지만 이를 해결해주는 고마운 어노테이션이 있습니다.
![image](https://github.com/woowacourse/android-paint/assets/22425650/9fa1df7b-9088-43a1-bf4d-a8d62112d98a)

이걸 사용하는 자바코드를 다시보면?
![image](https://github.com/woowacourse/android-paint/assets/22425650/b4d43208-5e0a-43ab-8ccd-b29df7e3b0bf)

이처럼 아주 잘돌아가는 것을 보실 수 있습니다.

정리하자면 다음과 같아요. 
1. 지금 상황처럼 생성자 파라미터로 하나는 값을 넘겨줘야하고 하나는 default value를 이용하고 싶은 경우 자바코드에서 에러가 난다. (생성자 파라미터 전부 defaultValue로 사용되길 바라면서 `Car()`로 작성하면 그건 또 자바에서 잘 작동합니다.)
2. 이를 해결하기 위해서는 `@JvmOverloads`를 사용해야한다.
3. 베리는 `@JvmOverloads`이 어떻게 이 상황을 해결하는지 코드를 까보며 확인해본다. 

---

(여기서 부터는 선택적으로 공부해보세용)

추가로 우리는 현재 미션에서 다루진 않았지만, 원래 view의 생성자 중에 `defStyleAttr`도 넘겨줄 수 가 있습니다.
이것 또한 defaultValue로 0을 주고 사용들을 많이 하는데요, 이것 관련한 문제도 밑에 나열할테니 한번 참고하면 좋을 것 같아요!

- 커스텀 뷰에서`@JvmOverloads` 어노테이션을 사용을 지양하라 [참고링크](https://medium.com/@mmlodawski/https-medium-com-mmlodawski-do-not-always-trust-jvmoverloads-5251f1ad2cfe)
- 아니다 적절히 타협해서 사용하면 괜찮다. [참고링크](https://proandroiddev.com/misconception-about-kotlin-jvmoverloads-for-android-view-creation-cb88f432e1fe)

궁금하다면 한번 보시는 것도 소소하게 추천드립니다. 🙂

2023-10-03 16:47 UTC, no1msh commented on app/src/main/java/woowacourse/paint/PaletteAdapter.kt
> +) : RecyclerView.Adapter<PaletteViewHolder>() {
어댑터에 클릭리스너를 넘겨주는 방법엔 여러가지가 있는데요 
vㅔ리는 람다로 넘겨주는 방법을 사용하시는군요 ㅎㅎ
인터페이스로 제공하는 방법도 있습니다만 람다로 넘겨주는 방법을 사용하신 베리의 이유가 궁금합니다!(틀렸다는거 아니에요🙅‍♂️)

2023-10-03 16:47 UTC, no1msh commented on app/src/main/res/layout/activity_main.xml
> +            app:layout_constraintBottom_toTopOf="@+id/main_colors_recycler_view" />
베리 그거 아시나요?.. 저도 멘델한테 들은건데 `Slider`가 있습니다...🤯

둘중 차이를 한번 확인하고 우리 미션에 무엇이 더 어울리는 뷰인지 생각해보면 좋을 것 같아요!
- [Slider](https://developer.android.com/reference/com/google/android/material/slider/Slider)
- [RangeSlider](https://developer.android.com/reference/com/google/android/material/slider/RangeSlider)

2023-10-03 16:47 UTC, no1msh commented on app/src/main/res/layout/activity_main.xml
> +            android:visibility="@{viewModel.paintWidthControllerVisibility ? View.VISIBLE : View.GONE, default = gone}"
뷰가 어떻게 보여야할지 정하는 로직, 다르게 말하면 뷰로직이 작성될 수 있는 곳은 여러군데가 있습니다. 🧐

생각나는대로 나열해보면
- BindingAdapter
- Activity / Fragment
- xml (Binding Expression) 베리가 선택한 방식

이렇게 되는데요. 
이러한 뷰로직이 여러군데로 흩어지게 되면 프로젝트의 크기가 커질 수록 유지보수하기가 힘들다고 생각듭니다.

예시를 들어보면 나중에 이앱을 QA 하는 과정에서 Slider의 visibility 처리가 제대로 안되었다는걸 파악했다고 가정해봅시다.
베리가 이런 뷰로직을 어디에 작성했는지 까먹었다는 전제하에 뷰로직이 있을 법한 곳을 다 뒤져봐야하는 불상사가 생길 수 있습니다.

위에서 말한 불상사를 줄이기 위해서 베리는 어떻게 하는게 좋을지 한번 생각해보시면 좋을것 같아요. 🤯

2023-10-03 16:47 UTC, no1msh commented on app/src/main/java/woowacourse/paint/PathHistory.kt
> +    val paths: List<PathPaint> get() = _paths.toList()
사실 이렇게 해서는 방어적 복사가 이루어지고 있지 않습니다 ㅎㅎ 저도 똑같이 실수 했었습니다. ㅋㅋㅋ
지금은 리스트 껍데기만 바꿔서 반환하고 있습니다. 🙃

2023-10-03 16:47 UTC, no1msh commented on app/src/main/java/woowacourse/paint/PathPaint.kt
> +data class PathPaint(val path: Path, val paint: Paint)
근데 이거 ㅋㅋㅋㅋ 클래스 이름 다른거로 바꿔보아도 좋을 것 같네요 🤣

2023-10-05 02:32 UTC, whk06061 commented on app/src/main/java/woowacourse/paint/Canvas.kt
> +class Canvas(context: Context, attrs: AttributeSet? = null) : View(context, attrs) {
오 자바에서 어떻게 동작을 할지는 미처 고려하지 못했네요 😊 
JvmOverloads 을 사용한 코드를 디컴파일 해본 결과 내부적으로 디폴트값을 받는 생성자와 받지않은 생성자들을 오버로딩하여 생성해주는 것을 확인할 수 있었습니다. 
<img width="826" alt="1" src="https://github.com/woowacourse/android-paint/assets/63198157/003d3816-c62f-4e81-9a09-7be00d91c1a1">
<img width="710" alt="2" src="https://github.com/woowacourse/android-paint/assets/63198157/c8e9a6d9-0f23-403c-86a9-b21fa5d1a174">

놓쳤던 부분이었는데 반달 덕분에 새로운 지식 쌓아갑니다 🤗 남겨주신 링크도 잘 먹겠습니당 😎

2023-10-05 02:38 UTC, whk06061 commented on app/src/main/java/woowacourse/paint/PaletteAdapter.kt
> +) : RecyclerView.Adapter<PaletteViewHolder>() {
인터페이스로 제공하는 방법도 있지만, 지금같이 하나의 이벤트만 전달해주는 상황에서는 굳이 불필요한 인터페이스 객체를 만들 필요성을 느끼지 못하여 심플하게 람다식을 넘겨줬습니다!

2023-10-05 02:46 UTC, whk06061 commented on app/src/main/res/layout/activity_main.xml
> +            app:layout_constraintBottom_toTopOf="@+id/main_colors_recycler_view" />
헉...!!!! 😲 초기값을 세팅할 때 `values` 라는 복수형 이름이 사용된다는 점이 뭔가 수상쩍었는데 일반 Slider 도 있었군요..!!
저희 미션에서는 범위를 설정할 필요가 없다고 생각하여 일반 Slider 를 사용하도록 수정하였습니다!

2023-10-05 02:57 UTC, whk06061 commented on app/src/main/res/layout/activity_main.xml
> +            android:visibility="@{viewModel.paintWidthControllerVisibility ? View.VISIBLE : View.GONE, default = gone}"
반달이 말한 의견에 동의합니다...🫠
기존에는 Slider 의 초기값을 (변수 때문에) 액티비티에서 선언해줬었는데 액티비티와 xml 에 코드가 분산되어있네요🤯 
차라리 xml 에 data binding 으로 초기값 변수를 설정해주고 binding expression 으로 속성값을 설정해주는게 낫겠다는 생각이 듭니다 😁

2023-10-05 03:07 UTC, whk06061 commented on app/src/main/java/woowacourse/paint/PathHistory.kt
> +    val paths: List<PathPaint> get() = _paths.toList()
앗.. 기본적인 걸 놓쳤네요 ㅎ😅 깊은 복사가 이뤄지도록 수정하였습니다 !

2023-10-05 03:14 UTC, whk06061 commented on app/src/main/java/woowacourse/paint/PathPaint.kt
> +data class PathPaint(val path: Path, val paint: Paint)
ㅋㅋㅋㅋDrawing 으로 개명해주었습니다 😎

2023-10-05 03:38 UTC, no1msh approved these changes
베리 1단계 미션 고생많으셨습니다! 
2단계도 화이팅입니다!! 😆

2023-10-05 03:38 UTC, no1msh commented on app/src/main/java/woowacourse/paint/PathHistory.kt
> +    private fun List<PathPaint>.deepCopy() = map { it.copy() }
베리 확장함수로 깔끔하게 표현해주신부분 너무 좋네요! 😆

하지만 아직은 제대로 깊은복사가 이루어지지 않고 있습니다. 
이해를 돕기위해 사진 놓고 갑니다!
![image](https://github.com/woowacourse/android-paint/assets/22425650/3ca9f601-0886-4259-a4ee-03538420c4b4)

2023-10-05 03:39 UTC, merged

2023-10-10 04:20 UTC, DYGames commented on app/src/main/java/woowacourse/paint/drawing/DrawingHistory.kt
> +    private fun List<Drawing>.deepCopy() = map { it.copy() }
List의 DeepCopy 가 DrawingHistory의 역할일까요? 그리고 제네릭을 이용해 구현할 수 있지 않을까요?

2023-10-10 04:20 UTC, DYGames commented on app/src/main/java/woowacourse/paint/drawing/DrawingHistory.kt
> +    fun addDrawing(pathPaint: Drawing) {
타입은 Drawing인데 인자는 pathPaint이네요?

2023-10-10 04:20 UTC, DYGames commented on app/src/main/java/woowacourse/paint/drawing/DrawingHistory.kt
> +class DrawingHistory(private val _drawings: MutableList<Drawing> = mutableListOf()) {
외부에서 생성자로 넘겨준 _drawings에 대한 수정이 가능하지 않을까요?

2023-10-10 04:20 UTC, DYGames commented on app/src/main/java/woowacourse/paint/ui/MainActivity.kt
> +        binding.defaultPaintWidth = DEFAULT_PAINT_WIDTH
static import가 적절하지 않은 것 같아요

2023-10-10 04:20 UTC, DYGames commented on app/src/main/java/woowacourse/paint/ui/custom/Canvas.kt
> +class Canvas @JvmOverloads constructor(context: Context, attrs: AttributeSet? = null) :
JvmOverloads 한 이유가 있을까요?

2023-10-10 04:20 UTC, DYGames commented on app/src/main/java/woowacourse/paint/ui/custom/Canvas.kt
> +    private var paint = Paint()
Drawing 이라는 객체로 표현할수 있지 않을까요?