Step1
woowacourse/android-paint pull request #80
Opened 2024-09-30 12:18 UTC by jinuemong

안녕하세요 올리브
리뷰어로 처음 만나네요 잘 부탁드려요 ! 
화이팅 ~

2024-10-01 15:36 UTC, kimhm0728 requested changes
안녕하세요 누누! 🫒
이번 미션 요구사항이 간단하기도 하고, 워낙 구현을 잘해주셔서 리뷰 남길 부분이 크게 없었습니다.
특히 Line 객체에 단순히 데이터만 담아둔 것이 아니라, 객체에게 적절한 책임을 부여하신 것이 인상깊었어요!!

함께 생각하면 좋을 부분들 코멘트 달아두었으니 확인 부탁드려요!
코멘트들은 어디까지나 제 개인적인 의견이니 꼭 반영하지 않으셔도 되고, 누누의 생각을 자유롭게 들려주세요 😄😄

2024-10-01 15:36 UTC, kimhm0728 commented on README.md
> +- [x] 브러시 굵기를 변경할 수 있다.
README 작성 좋네요!! 👍👍

2024-10-01 15:36 UTC, kimhm0728 commented on app/build.gradle.kts
> +    }
현재는 데이터 바인딩이 아닌 뷰바인딩만 사용하고 있는데, 데이터바인딩 속성을 제거하면 어떨까요??

2024-10-01 15:36 UTC, kimhm0728 commented on app/src/main/java/woowacourse/paint/ColorPaletteAdapter.kt
> +    class ColorPaletteViewHolder(
`ColorPaletteViewHolder`를 다른 파일에 작성하지 않고 `ColorPaletteAdapter`의 nested class로 선언하신 이유가 궁금해요! 다른 파일로 분리하면 읽는 입장에서 더 좋을 것 같습니다~!

2024-10-01 15:36 UTC, kimhm0728 commented on app/src/main/java/woowacourse/paint/MainActivity.kt
> +                activityViewBinding.customCanvas.changeColor(brush)
컬러나 굵기를 변경할 때, `brush`의 `changeColor()`도 호출하고 `customCanvas`의 `changeColor()`도 호출하고 있어서 조금 어색하게 느껴져요. `customCanvas` 내부에서 brush를 들고 있는 건 어떨까요??
`MainActivity`가 `brush` 객체를 들고 있도록 설계하신 누누의 생각이 궁금합니다!!

2024-10-01 15:36 UTC, kimhm0728 commented on app/src/main/java/woowacourse/paint/MainActivity.kt
> +            activityViewBinding.customCanvas.changeLineWidth(brush)
이 부분도 마찬가지입니다!

2024-10-01 15:36 UTC, kimhm0728 commented on app/src/main/java/woowacourse/paint/brush/ColorPalette.kt
> +    BLUE(Color.parseColor("#4350AF")),
`resources`의 `colors.xml`을 활용하지 않고, 컬러 코드를 String으로 사용하신 이유가 궁금해요! `strings.xml`처럼 안드로이드 개발을 할 때는 `colors.xml`을 사용하는 것이 더 자연스러운 것 같다는 개인적인 의견입니다 😄😄

2024-10-01 15:36 UTC, kimhm0728 commented on app/src/main/java/woowacourse/paint/brush/Line.kt
> +    }
저는 이 부분을 커스텀뷰에서 다 구현했는데, 객체를 따로 분리한 것이 너무 신선하고 좋네요!! 
누누의 설계처럼, 하나의 선을 생성하는 건 커스텀뷰가 아닌 다른 객체에게 책임을 위임할 수도 있겠네요. 하나 배워갑니다 👍👍

2024-10-01 15:36 UTC, kimhm0728 commented on app/src/main/java/woowacourse/paint/brush/Line.kt
> +    }
그런데 저는 `Line`(path, paint)보다 `canvas`가 더 상위 객체라고 생각해요. `canvas`는 여러개의 `Line`들이 그려질 수 있는, 큰 도화지같은 친구니깐요.
또한 무언가를 draw하는 주체는 `Line` 객체가 아닌 `canvas`이기 때문에, `CanvasView`에서 직접 `Line`들을 draw 해주도록 수정하면 어떨까요??
draw를 하는 건 `Line`의 책임이 아닌 것 같아요.

`draw()` 함수 내부에서도 `canvas.drawPath()`를 해주고 있으니 더더욱 어색하게 느껴집니다. 😄

2024-10-02 06:17 UTC, jinuemong commented on app/build.gradle.kts
> +    }
헉 넵

2024-10-02 06:20 UTC, jinuemong commented on app/src/main/java/woowacourse/paint/ColorPaletteAdapter.kt
> +    class ColorPaletteViewHolder(
Nested로 선언하면 두 클래스가 관련 있다는 것을 명확하게 나타낼 수 있을 것 같았어요(로직이 적다면).
하지만 가독성이 떨어져보이고, 다음 미션에서 별도에 추가 기능이 추가된다면 복잡해줄 수 있을 것 같네요.
수정해보겠습니다 !!

2024-10-02 06:24 UTC, jinuemong commented on app/src/main/java/woowacourse/paint/MainActivity.kt
> +                activityViewBinding.customCanvas.changeColor(brush)
customCanvas에서 bursh를 들고 있게 되면 customCanvas가 여러 개인 경우 브러쉬를 재생성할 것 같아서 MainActivity에서 들고 있도록 설계해봤어요.
두번 호출하는 느낌이 들어서 어색한 것 같은데, customCanvas에 brush를 주입해주는 방식으로 수정해보겠습니다

2024-10-02 06:37 UTC, jinuemong commented on app/src/main/java/woowacourse/paint/MainActivity.kt
> +                activityViewBinding.customCanvas.changeColor(brush)
헉 CanvasView에 brush를 넣어줄 수 없네요
수정했습니다 ㅠ

2024-10-02 06:47 UTC, jinuemong commented on app/src/main/java/woowacourse/paint/brush/ColorPalette.kt
> +    BLUE(Color.parseColor("#4350AF")),
헉 급하게 하다보니 `colors.xml`쓰는 것을 깜빡했네요
수정해보겠습니다 !!!

2024-10-02 06:49 UTC, jinuemong commented on app/src/main/java/woowacourse/paint/brush/Line.kt
> +    }
감사합니다 !!! 
```kotlin
path.quadTo(endX, endY, (x + endX) / 2, (y + endY) / 2)
```
위 부분에서 숫자 2가 어떻게 보면 매직넘버가 될 수도 있는데, 네이밍이 애매해서 그냥 작성했습니다. 상수화 하는게 좋아보일까요?? 궁금하네요

2024-10-03 02:49 UTC, jinuemong commented
안녕하세요 올리브 다시 요청드립니다 !!
colors.xml 쓰려했는데 Brush.changeColor 할 때 context를 필요하게 되어서 구현이 어려워졌습니다.
현재 구조에서는 못쓸 것 같네요 ㅠ 일단 요청합니다 !!

2024-10-03 06:25 UTC, kimhm0728 commented on app/src/main/java/woowacourse/paint/brush/Line.kt
> +    }
개인적으로는 `(x + endX) / 2`이 어떤 걸 계산하는지 한눈에 파악이 안됐어요. `(x + endX) / 2`를 변수로 따로 빼서 그 변수의 네이밍에 어떤 걸 뜻하는지 내포하는 것도 좋을 것 같아요~! 물론 상수화까지 해주시면 너무 좋구요!

2024-10-03 06:48 UTC, kimhm0728 approved these changes
누누 안녕하세요~!
코멘트, 리뷰 반영된 코드 모두 확인했습니다! 👍
step1은 이만 마무리할게요.
step2, 3도 파이팅입니다 👊

2024-10-03 06:48 UTC, kimhm0728 commented on app/src/main/java/woowacourse/paint/brush/Line.kt
> +    private var linePaint = paint
`Line`에 있는 `draw()` 함수가 사라지면서, 이 프로퍼티 두개도 쓰이지 않게 된 것 같네요~! 삭제해주세요!

2024-10-03 06:48 UTC, kimhm0728 commented on app/src/main/java/woowacourse/paint/canvas/CanvasView.kt
> +            this.color = brush.colorPalette.colorRes
Brush.changeColor 할 때 context가 필요해서 color resources를 활용하지 못했다고 하셨는데요! 

```suggestion
            this.color = ContextCompat.getColor(context, brush.colorPalette.colorRes)
```
`Brush`에서는 resources id만 들고 있고, `Paint`에 color를 적용할 때만 resources id를 실제 color resources로 변경해주면 가능할 것 같아요. `CanvasView`도 `View`이니 자신의 `context`를 가지고 있으니까요!

2024-10-03 06:48 UTC, kimhm0728 commented on app/src/main/java/woowacourse/paint/canvas/CanvasView.kt
> +    private var brush: Brush = Brush()
`CanvasView`에 그림을 그릴 때 필요한 객체들을 모두 가지고 있어서, `CanvasView`를 사용하는 `MainActivity`에서는 세부적인 구현 사항을 모르는 구조로 개선되었네요~! 👍👍

`"customCanvas에서 bursh를 들고 있게 되면 customCanvas가 여러 개인 경우 브러쉬를 재생성"`할 것 같다고 말씀해주셨는데, 저는 하나의 `Activity`나 하나의 `Fragment`에서 `customCanvas`가 여러개 사용될 경우는 없다고 생각해요.(그림판인데 한 화면에 그림판 보드가 여러개인 경우가 있을지?!!!) 그래서 `customCanvas`가 재활용될 때마다 `Brush`가 새로 생성되는 것도 좋은 구조라고 생각합니다.

물론 제 생각일 뿐이고, 사람마다 다를 수 있으니깐요!! 리뷰 반영해주셔서 감사해요! 🫒

2024-10-03 06:48 UTC, merged