[반달] 뷰 챌린지 미션 1단계 제출합니다.
woowacourse/android-paint pull request #9
Opened 2023-09-28 17:01 UTC by no1msh

<img src="https://github.com/woowacourse/android-paint/assets/22425650/cdd01ba6-fdc2-4c2c-a60f-73c534663656" width="30%">

---

안녕하세요 멘델 반달입니다.흐흐
미션 자체 요구사항만 최소한으로 만족시킨다면 금방 끝낼 수도 있었을 것 같은데 여러가지로 욕심이 나서 오래걸렸습니다.
**특히나 구성변경 대응은 안드로이드 개발자로서 참을 수가 없었기에 열심히 해보았습니다. 😎** 

컬러 선택하는 부분을 그냥 스크롤 뷰로 구현할지 리사이클러 뷰로 구현할지 고민을 했었는데, 사고과정과 결론은 다음과 같습니다.
- 추후에 사용자가 직접 컬러를 추가할 수도 있는 기능이 나올 수도 있음.
- 사용자가 직접 추가한 컬러를 RGB 값에 따라 정렬할 수도 있음.

> 결론: 이런 확장성들을 고려하면 리사이클러뷰로 구현 해두는게 나을 것 같다.

--- 

리뷰 기다리겠습니다! 항상 감사드립니다.

2023-09-29 22:10 UTC, rhthrhrl0 requested changes
안녕하세요 반달~ 반달 코드를 보고 직접 실행해보면서 이번 미션에서 반달이 얼마나 고민하고, 사용자 편의성을 고려했는지 느낄 수 있었습니다. 실제로 사용하면서, 진짜 편하다고 느꼈습니다 👍 
코드를 리뷰하면서, 저도 많이 배웠고 다시 공식 문서를 살펴보는 시간을 가질 수 있었습니다. 리뷰 중에 혹시 이해가 안가거나 제가 잘못 이해한 내용이 있다면, 언제든지 개인 연락 주세요~ 가능한 빨리 확인해보겠습니다 :)

2023-09-29 22:10 UTC, rhthrhrl0 commented on app/build.gradle.kts
> +    implementation("androidx.fragment:fragment-ktx:1.6.1")
프래그먼트 ktx는 추가할 필요가 없어보입니다!

2023-09-29 22:10 UTC, rhthrhrl0 commented on app/src/main/java/woowacourse/paint/common/BindingAdapter.kt
> +object BindingAdapter {
object로 감싸고, @JvmStatic을 붙이신 이유가 있는지 궁금해서 글 남깁니다.
@JvmStatic은 object같은 싱글톤 안에 바인딩 어댑터를 선언한다면 필요합니다. 하지만, 코틀린에서는 최상위 함수를 지원해주기 떄문에 최상위 함수로 바인딩 어댑터 함수를 선언 및 정의한다면, @JvmStatic 어노테이션들도 필요없어서 불필요한 코드들이 감소하게 됩니다. 
저 같은 경우는 커스텀 뷰에 대한 속성들을 바인딩 어댑터로 정의해야 할 일이 있을때, 그 커스텀 뷰의 동반 객체 안에 바인딩어댑터를 같이 정의해주는데, 이때, @JvmStatic을 사용합니다. 
지금 이 파일처럼 , 단순한 유틸성의 바인딩 어댑터 함수들은 굳이 동반 객체말고 최상위 함수로 올려도 될 것 같습니다!

2023-09-29 22:10 UTC, rhthrhrl0 commented on app/src/main/java/woowacourse/paint/customview/BrushColor.kt
> +        fun getColorBoxes(@ColorRes selectedColor: Int): List<BrushColorBox> =
Int보다는 BrushColor를 받는 것이 좀 더 이 함수의 존재가 명확하지 않을까요?? 만약 ENUM에 정의되지 않은 컬러리소스를 넣는다면, 어떤 것도 선택되지 않는 리스트가 나올 것 같습니다

2023-09-29 22:10 UTC, rhthrhrl0 commented on app/src/main/java/woowacourse/paint/customview/PaintingView.kt
> +    val strokes: List<Stroke> get() = _strokes.toList()
깊은 복사가 제대로 이루어지지 않는 것 같습니다!

2023-09-29 22:10 UTC, rhthrhrl0 commented on app/src/main/java/woowacourse/paint/customview/PaintingView.kt
> +        isFocusableInTouchMode = true
없어도 잘 동작하는 것 같은데, 혹시 해당 코드들은 어떤 목적으로 사용하신 것이죠? 어떤 예방의 목적이였나요? (저도 해당 내용에 대해 공식문서를 보고 해도 사실 EditText같은 경우 말고는 진짜 언제 쓰는건지 잘 안와닿아서 궁금해서 여쭤보는 것입니다!!)

2023-09-29 22:10 UTC, rhthrhrl0 commented on app/src/main/java/woowacourse/paint/customview/PaintingView.kt
> +        _strokes.addAll(strokes)
여기서  마지막에 invalidate를 안해줘도 이 함수가 괜찮을까요?
현재 코드는 액티비티의 onCreate쪽에서 호출함으로써, 자동으로 invalidate가 되기를 기대하는 것 같습니다. 즉, 상황에 의존하는것 같습니다. 만약 해당 함수가 앱이 실행될때 동적으로 이용된다면, 개발자의 의도와 달리 그림판 뷰가 갱신되지 않을것 같습니다.

2023-09-29 22:10 UTC, rhthrhrl0 commented on app/src/main/java/woowacourse/paint/main/ColorClickListener.kt
> +interface ColorClickListener {
리스너로 유연성을 보장해주는 것이 좋아요! 반달의 코드 스타일이 드러나는 것 같네요

2023-09-29 22:10 UTC, rhthrhrl0 commented on app/src/main/java/woowacourse/paint/main/MainActivity.kt
> +        viewModel.updateStrokes(binding.pvMain.strokes)
부모의  onDestroy보다 먼저 호출하는 이유가 있을까요? 개인적으로 생명주기 함수에서 이런 부모클래스의 함수 호출보다 내가 할 일을 먼저 작성하는 로직은 위험하다고 생각이듭니다! 힐트에서도 부모의 onCreate이후 액티비티에 대한 정상적인 필드 주입이 완료되는 식입니다. 또한, 저 안에서 액티비티의 상태 등의 정보도 변경하기 때문에 가능한, 나중에 호출하는 것을 권장합니다!

2023-09-29 22:10 UTC, rhthrhrl0 commented on app/src/main/java/woowacourse/paint/main/MainActivity.kt
> +        BrushColor.getColorBoxes(clickedBrushColorBox.brushColor.colorRes)
현재 너무 많은 일을 하고 있는 것 같다고 생각이 들고 있습니다. 또한, 가장 중요한 점은 어댑터의 리스트에서 아이템을 가져오고 있는데, 지금 아키텍쳐 패턴이 MVVM이고, 모든 올바른 데이터의 집합은 항상 뷰모델에 있다는 것을 떠올려야 합니다. 
그렇다면, 클릭이라는 이벤트를 뷰모델로 올려주고, 그 뷰모델에서 자신이 가진 데이터를 탐색해서 찾고, 조건문 판단이 필요하다면 이런 비지니스 로직도 뷰모델에서 처리를 하고, 데이터바인딩 혹은 UI 스테이트 혹은 라이브데이터를 활용해서, UI 변경해야 한다는 사실을 뷰모델이 ui로 내려주는 식의 UDF 구조가 좀 더 적합할 것 같습니다. 
![image](https://github.com/woowacourse/android-paint/assets/67176829/4b7590ff-51a8-4bdc-8e30-487163635312)

2023-09-29 22:10 UTC, rhthrhrl0 commented on app/src/main/res/layout/activity_main.xml
> +            app:rangeSliderCurrentValue="@{viewModel.brushThickness}" />
RangeSlider 말고 Slider를 사용하시면, 해당 바인딩 어댑터 속성말고, android:value 속성을 사용하실 수 있습니다. 제가 찾아봤을 때는 저희 미션에는 RangeSlider보다 Slider가 적합해 보였는데, 반달은 어떻게 생각하시나요?? 
저는 RangeSlider는 두 개의 범위 지정을 할 때 유용하다고 느꼈고, 저희처럼, 한쪽 값을 수정해나가는 ui면 Slider가 적합해보인다고 생각했습니다.

2023-09-29 22:10 UTC, rhthrhrl0 commented on app/src/main/java/woowacourse/paint/customview/PaintingView.kt
> +    private fun setupPaint(paint: Paint) {
Paint 객체를 반환하는 구조가 낫지 않을까요? 아니면, 60번째 줄의 
currentStoke = Stroke(Path(), Paint().apply{ setupPaint(this) }) 
하는 것도 괜찮아 보입니다. 
지금 61번째 줄이 이미 만든 객체를 불필요하게 다시 끄집어내서 함수의 인자로 넘기는 형태라서, 받아들여지지 않는 것 같습니다.

2023-10-01 03:32 UTC, no1msh commented on app/build.gradle.kts
> +    implementation("androidx.fragment:fragment-ktx:1.6.1")
맞습니다 멘델ㅋㅋㅋ
저는 근데 이런거도 매번 고민이 되곤 합니다.
지금 당장은 필요없는데 나중에 사용할 것을 미리 추가하는게 맞을까? 하는 고민을 매번합니다. 

고민 끝에 내린 결론은 나중에 사용될 확률이 낮으면 필요하게 될 때 추가하고, 프래그먼트의 경우 프로젝트에서 웬만하면 필연적으로 사용될 확률이 높기 때문에 먼저 추가해두자 라는 결론에 도달하였습니다.

제 의견을 듣고 생각해본 멘델의 의견이 다시 궁금합니다!

2023-10-01 04:46 UTC, no1msh commented on app/src/main/java/woowacourse/paint/customview/PaintingView.kt
> +    val strokes: List<Stroke> get() = _strokes.toList()
아이고~ 우테코 6기로 다시뵙겠습니다.ㅋㅋㅋ
이걸 놓치다니 수정하겠습니다!

2023-10-01 05:06 UTC, no1msh commented on app/src/main/res/layout/activity_main.xml
> +            app:rangeSliderCurrentValue="@{viewModel.brushThickness}" />
아 애초에 Slider가 있는 줄 몰랐습니다.
항상 미션에 예시코드가 있으면 그게 거의 정답인줄 알고 그냥 그대로 썻던걸 반성하게 되네요.
대체 왜 value가 없지 이러고 있었네요 ㅋㅋㅋㅋㅋ

공문에서 찾아보니 다음과 같이 정의가 되어있었군요.

- rangeSlider 
> A range slider can be used to select from either a continuous or a discrete set of values. The default is to use a continuous range of values from valueFrom to valueTo.

- slider
> A widget that allows picking a value within a given range by sliding a thumb along a horizontal line.

지금 미션에서는 멘델이 말씀하신대로 slider가 맞아보이네요!
수정하겠습니다!

2023-10-01 14:22 UTC, no1msh commented on app/src/main/java/woowacourse/paint/main/MainActivity.kt
> +        viewModel.updateStrokes(binding.pvMain.strokes)
헉 명백한 실수입니다. 수정하였습니다ㅜ.ㅜ

2023-10-01 14:55 UTC, no1msh commented on app/src/main/java/woowacourse/paint/common/BindingAdapter.kt
> +object BindingAdapter {
저도 항상 최상위 함수로 구현을 하다가 최근들어 object에 구현하는 것으로 바꾸어봤는데요.
이렇게 함으로써 얻는 장단점은 다음과 같습니다.

장점
- 최상위 public 함수라면 다른 클래스(ex. Activity) 에서 바로 바인딩 어댑터 함수를 호출 할 수 있는데, object로 구현을하면 최소한 object 이름을 작성하고 . 까지 찍어야 호출이 가능해집니다. (최상위 함수의 네임스페이스 충돌 단점을 해결한다 생각합니다.)

단점
- 말씀하신대로 `@JvmStatic` 을 명시해줘야한다는 단점이 있습니다. 

이외에 제가 모르는 장단점도 있겠지만, 지금 상황에서 제 생각엔 `@JvmStatic`을 작성해주는 비용을 들여
> object로 구현을하면 최소한 object 이름을 작성하고 . 까지 찍어야 호출이 가능해집니다. 

이란 장점을 얻는게 더 좋아보였습니다.

---

그리고 멘델이 말씀하신
> 저 같은 경우는 커스텀 뷰에 대한 속성들을 바인딩 어댑터로 정의해야 할 일이 있을때, 그 커스텀 뷰의 동반 객체 안에 바인딩어댑터를 같이 정의해주는데, 이때, @JvmStatic을 사용합니다.

저도 이생각 해보았는데 다른 xml 뷰에서도 똑같이 참조가 가능하더라고요. 이러한 단점은 혹시 해결하셨는지 아니면 BindingAdpater의 고질적인 단점이라 생각하셔서 두셨는지 궁금합니다.

2023-10-01 16:41 UTC, no1msh commented on app/src/main/java/woowacourse/paint/customview/PaintingView.kt
> +        isFocusableInTouchMode = true
역시 LMS에 있는 코드 긁어오다 같이 작성된거 같습니다. 
저도 잘 몰라서 공식문서에 찾아보니 [이런내용](https://developer.android.com/guide/topics/ui/ui-events?hl=ko#TouchMode)이 있더라구용 
관련 된거 같습니다. 

참고로 에뮬레이터에서 키보드 방향키를 이용해 뷰의 포커스를 옮겨 다닐 수 있습니다.(엔터로 클릭도 할 수 있습니다.) 뷰의 포커스를 옮기면 현재 포커스된 뷰가 약간 어두워지는 피드백을 주는데요. `isFocusable`이 없으면 이 피드백을 받을 수 없게됩니다.
아마 접근성 관련 기능인거 같아 더 찾아보니 흥미로운 글이 있어 같이 첨부 해봅니다. [링크](https://techblog.woowahan.com/2660/)

2023-10-01 19:59 UTC, rhthrhrl0 commented on app/build.gradle.kts
> +    implementation("androidx.fragment:fragment-ktx:1.6.1")
저는 추상화 같은거는 미래를 생각해서 되게 선호하는 편인데, 라이브러리 추가는 앱의 다운로드 사이즈에 영향이 실제로 좀 갈 수 있다고 생각을 해서 사용하지 않는 라이브러리는 추가 안하는 걸 선호합니다!!  그런데 사실, 반달의 고민도 충분히 공감은 됩니다 ㅋㅋㅋㅋ 프래그먼트 정도는 얼마든지 안드로이드에서 금방 추가될 수 있는 개념이니까요... 
이게 실수가 아니라 반달이 고민을 하신 코드 한 줄이였군요ㅋㅋㅋ

2023-10-01 20:11 UTC, rhthrhrl0 commented on app/src/main/java/woowacourse/paint/common/BindingAdapter.kt
> +object BindingAdapter {
아하... 다른 코드를 작성할 때 해당 함수의 호출이 자동완성에 뜨는 것을 방지하려고 하신거였군요~!
이거는 그러면, 개발자 취향 차이인 것 같습니다!

그리고, 다른 xml뷰에서 바인딩 어댑터 참조가 가능한 문제는 저는 사실 이게 큰 문제는 아니라고 생각을 하는 편이라서, 신경을 많이 안쓰는 편입니다! 사실 이미 정의된 속성만 해도 너무 많고 거기에 저희가 만든 속성 몇 개가 자동완성추천에 더 뜬다고 해서 큰 문제를 겪었던 적이 없기 때문입니다! 대신,저는 커스텀뷰의 속성을 바인딩 어댑터로 정의하는 경우에 해당 뷰의 이름을 앞에 prefix로 적어주는 식으로 자동완성 실수를 최대한 피하고 있습니다.

2023-10-01 20:27 UTC, rhthrhrl0 commented on app/src/main/java/woowacourse/paint/customview/PaintingView.kt
> +        isFocusableInTouchMode = true
오 분명 그 공식문서를 봤다고 생각했는데, 맨 아래까지 꼼꼼히 보지는 않은 것 같네요. nextFocusUp 저런 속성도 있었군요!
또한, 뷰의 포커스를 옮겨 다닐 때, 포커스된 뷰가 약간 어두워진다는 것도 처음 알았네요!

2023-10-02 07:55 UTC, no1msh commented on app/src/main/java/woowacourse/paint/customview/BrushColor.kt
> +        fun getColorBoxes(@ColorRes selectedColor: Int): List<BrushColorBox> =
반영하였습니다!

2023-10-02 09:07 UTC, no1msh commented on app/src/main/java/woowacourse/paint/customview/PaintingView.kt
> +        _strokes.addAll(strokes)
오 이거참 맞는 말이네요 기존의 방식으로도 물론 동작은 되지만, 멘델 말씀대로 `onCreate()에서의 호출`에 의존적인 형태였네요. 수정하였습니다. 😆

2023-10-02 09:20 UTC, no1msh commented on app/src/main/java/woowacourse/paint/customview/PaintingView.kt
> +    private fun setupPaint(paint: Paint) {
따로 `Paint()`로만 사용하는 곳이 없어 멘델 말씀대로 
> 초기설정이 완료된 Paint 객체를 반환하는 구조

로 변경하였습니다.

2023-10-02 10:25 UTC, no1msh commented on app/src/main/java/woowacourse/paint/main/MainActivity.kt
> +        BrushColor.getColorBoxes(clickedBrushColorBox.brushColor.colorRes)
멘델 아주 좋은 의견입니다. 이해를 돕는 사진까지 감사합니다 ㅎㅎ
추석연휴라 기쁜나머지 정신머리를 놓고 코딩했네요.ㅋㅋ

다시한번 UDF와 MVVM에 대해서 정리를 해봐야겠네요.

한번 확인해보시고 이상하면 또 말씀주세요~

2023-10-02 10:33 UTC, no1msh commented
멘데엘~ 
리뷰 감사합니다. 덕분에 좀 부족한 점이 보여서 고칠 수 있었습니다!
연휴 때 여유롭게 코딩하는게 정말로 즐겁네요! 

변경사항 확인해보시고 이상한점이나 토론하고싶으신거 있으시면 얼마던지 코멘트 작성해주세요~😆

2023-10-02 11:00 UTC, rhthrhrl0 approved these changes
안녕하세요 반달! 리뷰 반영 너무 잘해주셔서 더이상 드릴 코멘트가 떠오르지 않네요! 
고생많으셨습니다~ 바로 머지할게요 👍 남은 연휴 푹 쉬세요~~

2023-10-02 11:00 UTC, rhthrhrl0 commented on app/src/main/java/woowacourse/paint/main/MainActivity.kt
> +        viewModel.updateBrushColorBoxes(brushColor)
구조가 너무 깔끔해진 것 같습니다! 리뷰 반영 너무 잘해주셨네요 👍

2023-10-02 11:00 UTC, merged