[서기] 뷰 챌린지 미션 3단계 제출합니다.
woowacourse/android-paint pull request #96
Opened 2024-10-02 16:23 UTC by Namyunsuk

안녕하세요 예니🐰
2, 3단계도 잘 부탁드려요!!😀

## 태블릿 세로 화면
### 대응 전 / 후
<img src="https://github.com/user-attachments/assets/1d4fbe5d-530f-416a-b9eb-5f1c9534c88a" width="250" height="300"> <img src="https://github.com/user-attachments/assets/0c08521a-8f6a-4417-927c-0d9552c1262f" width="250" height="300">

## 태블릿 가로 화면
### 대응 전 / 후

<img src="https://github.com/user-attachments/assets/8c3e2d09-b813-4079-b6b4-f5b382fcba0c" width="250" height="300"> <img src="https://github.com/user-attachments/assets/7ddb0410-4d35-4091-8b0e-03d50d247301" width="250" height="300">

## 다크모드
### 다크모드 X / O (텍스트 색상이 바뀝니다!)

<img src="https://github.com/user-attachments/assets/0aab11d3-1238-4abe-89b3-9d6f221cdf80" width="250" height="500"> <img src="https://github.com/user-attachments/assets/906b6382-c787-4c97-95d0-8868d9e67309" width="250" height="500">

## 시연 영상

https://github.com/user-attachments/assets/e189d8d1-2f39-4c2f-9fac-a9d5e874546c

2024-10-03 12:52 UTC, JoYehyun99 requested changes
안녕하세요 서기~~ 2,3단계 미션 고생하셨습니다!
빠르게 잘 구현해주셨네요 👏👏
뷰 챌린지 미션인 만큼 관련된 코멘트들 남겼습니다! 확인 부탁드려용 ~👍👍

2024-10-03 12:52 UTC, JoYehyun99 commented on app/src/main/res/layout/activity_main.xml
> +        </androidx.constraintlayout.widget.ConstraintLayout>
현재 `ConstraintLayout` 이 중첩되어 있는 구조인데요! 
`ConstraintLayout` 의 장점을 살려서 중첩이 없도록 수정해봐도 좋을 것 같아요 😊

https://developer.android.com/topic/performance/rendering/optimizing-view-hierarchies#removing

2024-10-03 12:52 UTC, JoYehyun99 commented on app/src/main/java/woowacourse/paint/Brush.kt
> +        path.reset()
path에 addRect 해주기 전에 무조건 reset을 해줘야 하나요? 
(저랑 구현이 달라서 just 궁금증💭)

2024-10-03 12:52 UTC, JoYehyun99 commented on app/src/main/res/layout/activity_main.xml
> +            <include
`include` 키워드를 사용하면 결국 중첩된 구조가 되어버리는데요! 
최대한 중첩된 구조를 제거해도 좋을 것 같아요!! 🥹

2024-10-03 12:52 UTC, JoYehyun99 commented on app/src/main/java/woowacourse/paint/BrushState.kt
> +    PEN("펜"),
string 리소스 파일에도 따로 정의 되어있던데,,,, 해당 string 값은 단지 enum 반환을 위해서 있는 것 같은데 맞나요?_?

클릭리스너 메서드 인자에 string 대신 `BrushState` 값 자체를 넘겨주는 건 어떨까 하는 작은 아이디어 제시해봅니당,,, 
```kotlin
android:onClick="@{() -> onClickPaletteListener.onClickBrushChange(@string/brush_pen)} "
```

2024-10-03 12:52 UTC, JoYehyun99 commented on app/src/main/res/layout/activity_main.xml
> +                android:textColor="@color/default_text_color"
현재 다크 모드 대응을 위해서 텍스트 컬러에 `default_text_color` 를 넣어주고 있는데요!
```kotlin
android:textColor="@color/default_text_color"
```
텍스트의 경우 굉장히 많이 사용될텐데 만약 매번 이렇게 값을 넣어주어야 한다면 실수할 가능성이 매우 높아질 것같아요 🥲
`theme` 같은거로 설정할 수 있지 않을까요???

2024-10-03 12:52 UTC, JoYehyun99 commented on app/src/main/res/layout/activity_main.xml
> +                android:textColor="@color/default_text_color"
현재 태블릿 대응 xml 에 있는 버튼에는 해당 코드가 없는 거로 보아,,, 태블릿 모드는 다크모드가 안되어있는 걸지도 모르겠네요,,,🥲

2024-10-06 10:06 UTC, Namyunsuk commented on app/src/main/java/woowacourse/paint/Brush.kt
> +        path.reset()
직사각형이나 원을 그릴 때 `MotionEvent.ACTION_MOVE ` 상태일 때 reset를 해주지 않으면 아랙 그림처럼 `직사각형 + 펜`이 합쳐져진 것 처럼 그려지더라구요ㅠㅠ
그래서 reset을 사용해주었어요🤣🤣
<img width="95" alt="image" src="https://github.com/user-attachments/assets/5941ead6-161b-4075-9187-7fa74b3478d2">

2024-10-06 10:43 UTC, Namyunsuk commented on app/src/main/res/layout/activity_main.xml
> +            <include
앗 그렇네요!! `merge`태그 사용해서 중첩구조 없애주었습니다~~
해당 커밋: [35a8bf4](https://github.com/woowacourse/android-paint/pull/96/commits/35a8bf4643da3725ead7db1f8006e75dcf7a7e67)
<img width="280" alt="스크린샷 2024-10-06 오후 7 42 23" src="https://github.com/user-attachments/assets/4794958e-0b02-466a-a56a-73bea92b16e6">

2024-10-07 04:52 UTC, Namyunsuk commented on app/src/main/res/layout/activity_main.xml
> +                android:textColor="@color/default_text_color"
예니가 언급해 주신대로 기본 텍스트 색상은 자주 쓰일 것 같네요!!
themes으로 관리하도록 변경해주었어요😊
[d3f4b27](https://github.com/woowacourse/android-paint/pull/96/commits/d3f4b27426120eabe3ba9a34b5b83d342bf36809)

2024-10-07 04:53 UTC, Namyunsuk commented on app/src/main/java/woowacourse/paint/BrushState.kt
> +    PEN("펜"),
String이 아니라 BrushState를 넘기는 방식으로 했더니 불필요하게 만들어준 문자열을 없앨 수 있었네요!! 
[5ea005b](https://github.com/woowacourse/android-paint/pull/96/commits/5ea005bf97b5ff9e236b372e54dad76f90b0bd00)

2024-10-07 08:09 UTC, JoYehyun99 approved these changes
서기! 뷰 챌린지 미션 고생하셨습니다 👍👍
중첩된 레이아웃을 제거하느라 꽤나 번거로우셨을 것 같은데 잘해주셨네요! 🥹
다음 미션도 화이팅입니다 💪💪

2024-10-07 08:09 UTC, merged